### ISSUE TITLE
bug: LSP formatting doesn't work for Helix

### ISSUE THREAD

**Issue by xJonathanLEI** [starkware-libs/cairo#1141]
# Bug Report

**Cairo version:**

`main` head at `a621d15`

**Steps to reproduce:**

First install the language server:

```console
$ cargo install --locked --path crates/languageserver
```

In the Helix editor, set the language server of Cairo:

```toml
name = "cairo"
language-server = { command = "languageserver" }
```

Then open some unformatted Cairo file and try to format the file.

**Current behavior:**

The file does not change.

**Expected behavior:**

The file changes to the formatted text.

**Related code:**

Pretty sure this is causing the issue:

https://github.com/starkware-libs/cairo/blob/a621d159b7c206df59578456f4ba8351ecc5dcfa/crates/languageserver/src/lib.rs#L320-L326

**Other information:**

N/A

**Comment by xJonathanLEI** [comment]
The end position of the edit here is out of bound. I guess the intend here is to indicate a "full document replacement". I'm checking the LSP spec to understand if this is allowed.

**Comment by xJonathanLEI** [comment]
Quoting the [spec v3.17](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textEditArray):

> All text edits ranges refer to positions in the document they are computed on.

I guess `u32::MAX` doesn't count towards "positions in the document". So I guess the bug is on the Cairo LSP side instead of Helix.

**Comment by xJonathanLEI** [comment]
Am working on a fix now. Will submit PR :)

**Comment by spapinistarkware** [comment]
Thanks!
