### ISSUE TITLE
feat: Local Proof Generator & Verifier 

### ISSUE THREAD

**Issue by jayhaizeizai** [starkware-libs/cairo#1182]
# Feature Request

Wish to have a local proof to understand the zk-proof and develop in some local/offline project(such as using bluetooth to transfer zk-proof)

**Describe Preferred Solution**

A compile option to generate proof json and a verifier to verify the json

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [Y ] Yes
- [ ] No

**Comment by spapinistarkware** [comment]
This isn't in the scope of this project right now.
If you want, you can try to take the run and integrate with [giza](https://github.com/maxgillett/giza), in your own repo.
