### ISSUE TITLE
dev: generics type syntax contains turbofish

### ISSUE THREAD

**Issue by lalcmellkmal** [starkware-libs/cairo#1672]
```
fn main() -> Option::<felt> {
    fib(1, 1, 13)
}

/// Calculates fib...
fn fib(a: felt, b: felt, n: felt) -> Option::<felt> {
    get_gas()?;
    match n {
        0 => Option::<felt>::Some(a),
        _ => fib(b, a + b, n - 1),
    }
}
```

I hate to bikeshed but the syntax looks weird with turbofish in type signatures. (Turbofish are expected in expressions though so that part’s fine.) Could it be changed to this for consistency with Rust:

```
fn main() -> Option<felt> {
    fib(1, 1, 13)
}

/// Calculates fib...
fn fib(a: felt, b: felt, n: felt) -> Option<felt> {
    get_gas()?;
    match n {
        0 => Option::<felt>::Some(a),
        _ => fib(b, a + b, n - 1),
    }
}
```

thank you

**Comment by spapinistarkware** [comment]
If anyone wants to contribute in this matter, it would be helpful:)

**Comment by cwkang1998** [comment]
Would love to contribute to this, if no one picked it up yet.

Am a bit new to this so will be a bit slow when working on this, so if its urgent then I'll leave it to someone else.

**Comment by spapinistarkware** [comment]
Sure, you are more than welcome. Not urgent at all.
The main issue right now is that parsing type expressions (`try_parse_type_expr()` fn in parser.rs) is using the `parse_path()` function, which is also used in regular expression parsing - and in regular expressions the `<` can be confused with operators..

I think a fix shoudl involve:
1. At cairo_spec.rs, on the "PathSegmentWithGenericArgs" node, make the `separator` optional.
2. At parser.rs, add a parse_type_path() function that is similar to parse_path(), but doesn't have the '::' thing.
