### ISSUE TITLE
bug: `should_panic` does not work in some cases

### ISSUE THREAD

**Issue by abdelhamidbakhta** [starkware-libs/cairo#1704]
# Bug Report

**Cairo version:**

Commit: 775dded594e182adf09d13a91e269e661150b8e7

**Current behavior:**

`should_panic` does not work if a panic is triggered by a call. when a call to a function panics in a test then the test fails (actually it fails badly, not a failing test, the test panic) even when  adding `should_panic`.

**Expected behavior:**

Test should pass and not fail badly.
**Related code:**

```cairo
#[test]
#[should_panic]
fn reproduce_bug() {
    trigger_panic();
}

fn trigger_panic() {
    let mut data = array_new::<Array::<u128>>();
    let len = array_len::<Array::<u128>>(data);
}

```

**Comment by orizi** [comment]
Note that this was not a bug in should_panic - you got a panic from the internal compiler (a rust panic)
this should_panic just makes tests expect a panic (which your code doesn't actually cause)

**Comment by abdelhamidbakhta** [comment]
> Note that this was not a bug in should_panic - you got a panic from the internal compiler (a rust panic) this should_panic just makes tests expect a panic (which your code doesn't actually cause)

ok nice, closing then. thanks
