### ISSUE TITLE
bug: formatting of struct is incorrect

### ISSUE THREAD

**Issue by abdelhamidbakhta** [starkware-libs/cairo#1705]
# Bug Report

**Cairo version:**

Commit: 775dded594e182adf09d13a91e269e661150b8e7

**Current behavior:**

Formatting of struct is incorrect.
**Expected behavior:**

Formatting of struct is correct/

**Steps to reproduce:**

Current behavior:
![Screenshot 2023-01-09 at 11 37 10](https://user-images.githubusercontent.com/45264458/211289422-bc66dcbf-0608-4b80-9cf9-107c841fe504.png)

Expected:
![Screenshot 2023-01-09 at 11 37 03](https://user-images.githubusercontent.com/45264458/211289452-a710cb8e-2036-469c-9580-af1cc3c743f6.png)

**Comment by gilbens-starkware** [comment]
Fixed in #1776.
