### ISSUE TITLE
bug: cairo-lang-casm cannot be used as an external crate

### ISSUE THREAD

**Issue by CHr15F0x** [starkware-libs/cairo#1785]
# Bug Report

**Cairo version:**

v.0.1.0

**Current behavior:**

`cairo-lang-casm` and other crates depending on `cairo-vm` cannot be used as external crates in other projects.

**Expected behavior:**

`cairo-lang-casm` and other crates depending on `cairo-vm` can be used as external crates.

**Steps to reproduce:**

`cairo-vm` `0.1.1` is a breaking change, the issue and the steps to reproduce have been described in https://github.com/lambdaclass/cairo-rs/issues/730

For example:
```
cargo new --lib example
cd example/
cargo add cairo-lang-starknet
cargo check 
```
Cargo check fails.

**Related code:**

**Other information:**

I imagine this has to be fixed either on `cairo`'s side by further restricting the dependency to `=0.1.0` or on `cairo-vm`'s side by yanking the release and re-releasing as `0.2.0`.

**Comment by spapinistarkware** [comment]
Will be fixed in the next release.

**Comment by spapinistarkware** [comment]
I think this is solved
