### ISSUE TITLE
bug: wrapping array results in `Failed to specialize:`

### ISSUE THREAD

**Issue by tarrencev** [starkware-libs/cairo#2016]
# Bug Report

**Cairo version:**

alpha2

**Current behavior:**

I'm attempting to wrap an array and run a simple test as shown below. Not sure what im doing wrong but the simple test results in
```
thread 'main' panicked at 'Failed to specialize: `dup<query::query::Query::<core::felt>>`'
```

```
use array::ArrayTrait;

struct Query<T> {
    data: Array::<T>,
}

trait QueryTrait<T> {
    fn new() -> Query::<T>;
    fn append(ref self: Query::<T>, value: T);
}

impl QueryImpl<T> of QueryTrait::<T> {
    #[inline(always)]
    fn new() -> Query::<T> {
        Query {
            data: ArrayTrait::new(),
        }
    }
    fn append(ref self: Query::<T>, value: T) {
        let mut data = self.data;
        array_append(ref data, value)
    }
}

impl QueryDrop of Drop::<Query::<felt>>;

#[test]
fn test_query() {
    let mut query = QueryTrait::<felt>::new();
    query.append(1);
}
```

**Expected behavior:**

Should successfully append a value

**Comment by spapinistarkware** [comment]
Definitely a bug, but also note that your code doesn't do what you think it does.
Calling array_append and passing data s ref will change the data variable, but not the self.data member. (You copies it to the var data).
You should recreate self:
self = Query{data}

**Comment by tarrencev** [comment]
Got it, so

```

    }
    fn append(ref self: Query::<T>, value: T) {
        let mut data = self.data;
        array_append(ref data, value)
        self = Query{data}
    }

```

Is that the most efficient implementation? We need to copy data every time?

**Comment by spapinistarkware** [comment]
The memory is immutable, this is just high level syntax, but there is no magic.
What would you do in Cairo0?
WYSIWYG

BTW, you alos need to add
"impl ArrayFeltDrop of Drop::<Array::<felt>>;" right now - again, until we have generic impl arguments.

 I'm debugging the panic though

**Comment by tarrencev** [comment]
hm in cairo 0 we could alloc then incrementally memcopy which would avoid copying all the previous values each time we append. 

i guess that is the behavior when using array directly in cairo 1 but not when it is wrapped like this?

**Comment by spapinistarkware** [comment]
Oh, there is no copy of the array, sorry for the misunderstanding.
