### ISSUE TITLE
Panicked at 'called `Result::unwrap()` on an `Err` value: UnknownType'

### ISSUE THREAD

**Issue by shramee** [starkware-libs/cairo#2043]
# Bug Report
This happens in `try_get_core_ty_by_name()` located in file `cairo-lang-semantic/src/corelib.rs`
`UnknownType` Error looks a bit confusing, which probably refers to Cairo types. And usually just needs to have `cairo-libs` added to the project. This might not be fixed in favour of #1595 solution but just putting it here to have some searchability...

**Cairo version:**

18b55fe243fd52f475cb62b1bf20a1a25e9cbfff

**Current behavior:**

Rather unhelpful error **'Panicked at 'called `Result::unwrap()` on an `Err` value: UnknownType'**.

**Expected behavior:**

Maybe something helpful indicating `corelib` is missing?

**Steps to reproduce:**

Add cairo as dependency and try to something that involves compiling Cairo.

**Related code:**

**Other information:**

**Comment by spapinistarkware** [comment]
This will probably not be relevant soon enough, like you said. For now, I'm closing this.
