### ISSUE TITLE
bug: Trait `core::serde::Serde::<core::starknet::ContractAddress>` has no implementation in the context.

### ISSUE THREAD

**Issue by tarrencev** [starkware-libs/cairo#2114]
# Bug Report

**Cairo version:**

`b51c511ab39dae631362d4157853db46c2c49d64`

**Current behavior:**

Calling a method on a starknet contract trait that accepts a `ContractAddress` as input results in the following:

```
#[abi]
trait IProxy {
    fn initialize(world_address: starknet::ContractAddress);
}
```

```
error: Trait `core::serde::Serde::<core::starknet::ContractAddress>` has no implementation in the context.
 --> IProxyDispatcher:19:9
        serde::Serde::<starknet::ContractAddress>::serialize(ref calldata, world_address);
        ^*******************************************************************************^

Error: failed to compile: lib
```

full repo here: https://github.com/dojoengine/dojo/pull/51

**Comment by spapinistarkware** [comment]
Is this still happening? ContractAddressSerde was added yesterday

**Comment by tarrencev** [comment]
> Is this still happening? ContractAddressSerde was added yesterday

Yeah it was at a commit hash after it was added (`b51c511ab39dae631362d4157853db46c2c49d64`)

**Comment by tarrencev** [comment]
@spapinistarkware @ilyalesokhin-starkware is this on your radar to fix? I can take a look at it if useful

**Comment by spapinistarkware** [comment]
@ilyalesokhin-starkware is looking at it. You can also take a look, it would help:)

**Comment by orizi** [comment]
can you try to add `use starknet_serde::ContractAddressSerde;` in the beginning of the contract?

**Comment by tarrencev** [comment]
> use starknet_serde::ContractAddressSerde

Sure, I gave it a shot and now have the same error as well as an error complaining that it is defined multiple times:


```
error: Trait `core::serde::Serde::<core::starknet::ContractAddress>` has no implementation in the context.
 --> IProxyDispatcher:19:9
        serde::Serde::<starknet::ContractAddress>::serialize(ref calldata, world_address);
        ^*******************************************************************************^

error: The name `ContractAddressSerde` is defined multiple times.
 --> contract:177:9
        use starknet_serde::ContractAddressSerde;
        ^***************************************^

error: The name `ContractAddressSerde` is defined multiple times.
 --> contract:343:9
        use starknet_serde::ContractAddressSerde;
        ^***************************************^
```
