### ISSUE TITLE
dev: improve error message for namespace collision with storage variables

### ISSUE THREAD

**Issue by tserg** [starkware-libs/cairo#2121]
In the ERC20 [example](https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-starknet/test_data/erc20.cairo), if we rename `get_name()` function to `name()`, the following error is thrown:
```
error: The name `name` is defined multiple times.
 --> contract:108:5
    mod name {
    ^********^

error: Expected function, found module.
 --> contract:376:23
            let res = super::name();
                      ^*********^

Error: Compilation failed.
```
However, the error message is not immediately clear as to what the issue is as the code snippets displayed are not in the contract. It will be helpful to point to the `Storage` struct instead.

**Comment by orizi** [comment]
diagnostics improved at https://github.com/starkware-libs/cairo/pull/2332.
Now the warning of the multiple times would appear on the original code:
```

error: Plugin diagnostic: The name `name` is defined multiple times.
 --> lib.cairo:9:9
        name: felt,
        ^**^
```
