### ISSUE TITLE
feat: Generic impl parameters

### ISSUE THREAD

**Issue by spapinistarkware** [starkware-libs/cairo#2151]
Have generic parameters that can hold impls, for example:
```
fn foo<T, impl Drop<T>> (x: T) {
}
```
This is a kind of a constraint on `T`. An instantiator would have to pass a Drop impl for T (a proof it is droppable), or let the compiler infer it by finding an applicable impl at the context.

Without this feature, it is hard to write non-trivial generic code.

**Comment by cwkang1998** [comment]
If no one have picked this up yet, I would love to work on this.

**Comment by spapinistarkware** [comment]
This is actively being worked on, and is one of our priorities:)

**Comment by Pet3ris** [comment]
@spapinistarkware why not support:

```
fn foo<T: Drop> (x: T) {
}
```

I thought the notation `ArrayImpl`, etc. was just a temporary thing, but it seems like Cairo is going for a slightly different design pattern than Rust :).

**Comment by spapinistarkware** [comment]
> @spapinistarkware why not support:
> 
> ```
> fn foo<T: Drop> (x: T) {
> }
> ```
> 
> I thought the notation `ArrayImpl`, etc. was just a temporary thing, but it seems like Cairo is going for a slightly different design pattern than Rust :).

We are doing in a different direction in a few places, yes.
We feel that Drop::<T> is a simpler design. We will probably need some more ergonomics, but other than that, feels ok to me.
