### ISSUE TITLE
bug: Failed setting up runner when array.len() and array.is_empty() are used

### ISSUE THREAD

**Issue by msaug** [starkware-libs/cairo#2176]
# Bug Report

**Cairo version:**
Commit [1991669](https://github.com/starkware-libs/cairo/commit/1991669a0453bd65541ff81a12772bac05130052)

**Current behavior:**
```
Error: Failed setting up runner.

Caused by:
    #27: [1] is undefined.
```

**Expected behavior:**
The program runs without errors.

**Steps to reproduce:**
Execute `cairo-run` on the following Cairo program

**Related code:**
```
use array::ArrayTrait;
fn main() {
    let mut a = ArrayTrait::<felt>::new();
    assert(a.len() == 0_usize, 'Array length is not 0');
    assert(a.is_empty() == true, 'Array is not empty');
}
```

**Other information:**

**Comment by spapinistarkware** [comment]
@liorgold2 this seems to be caused by a wrong drop for UninitializedLocal of the array.
