### ISSUE TITLE
 Naming Conflict

### ISSUE THREAD

**Issue by TheOPtimal** [starkware-libs/cairo#2236]
# Bug Report

The name Cairo is already being used by [Cairo](https://cairographics.org/), a very popular and commonly used 2D graphics library. It even has [it's own Wikipedia page](https://en.wikipedia.org/wiki/Cairo_(graphics))!

The Cairo graphics library is used by GTK and FLTK, two very popular GUI toolkits.

**Comment by orizi** [comment]
Thank you for taking the time to bring this matter to our attention. We appreciate your interest in Cairo and your concern regarding the name.
We understand that the name Cairo is also being used by a popular 2D graphics library, and that it could potentially cause confusion among users. However, we have decided that changing the name of the Cairo project would not be practical at this point, given the significant impact it would have on our existing user base.
