### ISSUE TITLE
feat: PartialEq for ContractAddress

### ISSUE THREAD

**Issue by milancermak** [starkware-libs/cairo#2259]
# Feature Request

ContractAddress should implement PartialEq so we are able to do this:

```rust
let f = contract_address_const::<0>();
let g = contract_address_const::<0>();
assert(f == g, 'no');
```

The feature has already been mentioned/suggested in #2171.

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [x] No

**Comment by orizi** [comment]
Added at https://github.com/starkware-libs/cairo/pull/2275
