### ISSUE TITLE
bug: IContractDispatcher ContractAddress serde

### ISSUE THREAD

**Issue by msaug** [starkware-libs/cairo#2286]
# Bug Report

**Cairo version:**
1.0.0-alpha.3

**Current behavior:**
`IContractDispatcher` tries to access from `serde::ContractAddressSerde` but it's implemented in `starknet::contract_address::ContractADdressSerde`

However, implementing `serde::Serde::ContractAddressSerde` to use in `IContractDispatcher` causes a conflict with the existing definition in `starknet::contract_address::ContractAddressSerde` used in the generated `contract.cairo`

**Expected behavior:**
`ContractAddress` serde is accessible from both IContractDispatcher and the generated `contract.cairo` without clashes.

This can be fixed by adding the line
```
use starknet::contract_address::ContractAddressSerde
```
in `serde.cairo`
in the 

**Steps to reproduce:**

**Related code:**

```
#[abi]
trait IContract {
    fn serde_conflict -> ContractAddress;
```

**Other information:**

**Comment by orizi** [comment]
can you please add the related code to reproduce the issue?
it seems the code you've added is not complete.

**Comment by orizi** [comment]
```
use starknet::contract_address::ContractAddressSerde;
#[abi]
trait IContract {
    fn serde_conflict() -> ContractAddress;
}
```

seems to have worked for me.

**Comment by msaug** [comment]
> ```
> use starknet::contract_address::ContractAddressSerde;
> #[abi]
> trait IContract {
>     fn serde_conflict() -> ContractAddress;
> }
> ```
> 
> seems to have worked for me.

Ah indeed. Specifying the import of ContractAddressSerde at the top-level of the file works.

However, since `ContractAddressSerde` is not explicitly used by the user but used in the intermediary code generated by the compiler, I think it's best if the user doesn't have to import it himself since he doesn't use it directly. This can cause a lot of confusion

**Comment by orizi** [comment]
Generally - this is a usage of a struct - unless we add a search for all impls that may occur anywhere - this cannot be found automatically.
We'd make sure to improve the resulting diagnostics - and hopefully improve the language server itself to provide much better suggestions.
