### ISSUE TITLE
bug: unsupported match arm

### ISSUE THREAD

**Issue by Pet3ris** [starkware-libs/cairo#2313]
# Bug Report

**Cairo version:**

Latest

**Current behavior:**

Invalid match arm `match rounding`

**Expected behavior:**

Should compile

**Steps to reproduce:**

Full reproduction is here: https://github.com/auditless/cairo-erc4626/pull/20/files

**Related code:**

```cairo
#[derive(Copy, Drop, PartialEq, Eq)]
enum Rounding {
    Down: (), // Toward negative infinity
    Up: (), // Toward infinity
    Zero: (), // Toward zero
}

fn is_up(rounding: Rounding) -> bool {
    match rounding {
        Rounding::Up(_) => true,
        Rounding::Down(_) => false,
        Rounding::Zero(_) => false,
    }
}
```

**Other information:**
-

**Comment by orizi** [comment]
note that `PartialEq` and `Eq` are yet to be supported in `derive` - what is the compilation issue you are seeing?

**Comment by Pet3ris** [comment]
Thanks @orizi - unfortunately was getting this issue even without `Eq`, `PartialEq`, you can see the compilation failure here: https://github.com/auditless/cairo-erc4626/actions/runs/4294794596/jobs/7484314619.

![image](https://user-images.githubusercontent.com/224585/221914377-ac033ac1-3547-4841-96eb-588f10340328.png)

**Comment by orizi** [comment]
the cause of the error is that currently match must be in the same order as in the enum.
leaving the issue open until we fix diagnostic - or support any order.

**Comment by orizi** [comment]
Diagnostics improved at https://github.com/starkware-libs/cairo/pull/2324
