### ISSUE TITLE
feat: u256 division

### ISSUE THREAD

**Issue by Pet3ris** [starkware-libs/cairo#2329]
# Feature Request

**Describe the Feature Request**

Support division between `u256` values.

**Describe Preferred Solution**

Provide a `Div<u256>` trait implementation.

**Describe Alternatives**

This could be built out of existing data types and binary operations in Cairo but that seems inefficient.

**Related Code**

-

**Additional Context**

This would enable various mechanisms for share conversion, yield, interest that are essential to operate money markets, vaults and other key DeFi products.

**Comment by cwkang1998** [comment]
Would love to work on this if its not currently being worked on!
