### ISSUE TITLE
bug: erc20.cairo contract doesn't compile – cannot find `LegacyMap` type and struct vars

### ISSUE THREAD

**Issue by Pet3ris** [starkware-libs/cairo#2333]
# Bug Report

**Cairo version:**

Latest

**Current behavior:**

```
error: Type not found.
 --> erc20.cairo:13:19
        balances: LegacyMap::<ContractAddress, u256>,
                  ^*******^

error: Type not found.
 --> erc20.cairo:14:21
        allowances: LegacyMap::<(ContractAddress, ContractAddress), u256>,
                    ^*******^

error: Identifier not found.
 --> erc20.cairo:27:9
        name::write(name_);
        ^**^

... more similar errors
```

**Expected behavior:**

Should compile successfully.

**Steps to reproduce:**

I tried to compile the `erc20` contract taken from the `starkware-libs` repo: https://github.com/auditless/cairo-erc4626/pull/21/files.

**Related code:**

-**Other information:**

You can see the exact compiler failure in this GitHub Actions run: https://github.com/auditless/cairo-erc4626/actions/runs/4304964461/jobs/7506737097.

**Comment by orizi** [comment]
which binary have you ran it with?

**Comment by Pet3ris** [comment]
I've ran `cairo-lang-compiler 1.0.0-alpha.3` locally and this artifact: https://api.github.com/repos/starkware-libs/cairo/actions/artifacts/574350093 in CI.

**Comment by Pet3ris** [comment]
Thanks a lot @orizi - will let you close if no action on compiler messages here!
