### ISSUE TITLE
feat: testing framework improvements for Starknet contracts

### ISSUE THREAD

**Issue by milancermak** [starkware-libs/cairo#2402]
# Feature Request

It would be great if there would be support for the following when testing Starknet contracts:

 * set custom block timestamp
 * set custom block number
 * set custom gas price
 * set custom caller address
 * get the resources consumed by a contract call (no. of steps, no. of builtins used, etc.)
 * a way how to test internal (not `#[view]` or `#[external]`) functions
 
Having at least this basic functionality would help us write thorough test suites for Starknet projects.

**Comment by orizi** [comment]
in `starknet::testing` there are some of the `set` options you asked for.
`#[available_gas(5000)]` on the test allows to provide changing gas to a specifi `#[test]`.
Separating builtins and other costs is currently not possible - but `testing::get_available_gas` would enable you to meter this in a test.
testing business logic is already supported as long as there's no interoperability.

**Comment by Arcticae** [comment]
@milancermak That sounds that something that we at [protostar](https://github.com/software-mansion/protostar) will be making. FYI, works are in progress and we are heading towards cairo1 support :)

**Comment by milancermak** [comment]
@orizi Cheers, I didn't notice `starknet::testing`. Is there a way how to test internal functions as well? I know about `__external`, but what about non-public functions?

@Arcticae super happy about you being right on the heels of Cairo 1 ❤️

**Comment by orizi** [comment]
if you've written a function at a contract module - you can still call it directly - so you'd be able to test it as well.
```
#[contract]
mod Contract {
  fn my_internal_func() {}
}

#[test]
fn testing_my_internal_func() {
   my_internal_func();
}
```

**Comment by milancermak** [comment]
Ah, cool, not sure what I was doing incorrectly.

Closing this issue. Thanks for the help guys 👑
