### ISSUE TITLE
bug: div and rem operators do not work

### ISSUE THREAD

**Issue by milancermak** [starkware-libs/cairo#2408]
# Bug Report

**Cairo version:**  96a077c2

Using `/`, `%`, `/=` or `%=` operators does not work. I tried it with `felt` and `u128`.

Consider this code:

```rust
#[test]
fn test_felt_div() {
    let d: felt = 20;
    assert(d / 5 == 4, '20 / 5 == 4');

    let mut v: felt = 20;
    v /= 5;
    assert(v == 4, '20 / 5 == 4');
}

#[test]
fn test_felt_rem() {
    let d: felt = 20;
    assert(d % 12 == 8, '20 % 12 == 8');

    let mut v: felt = 20;
    v %= 12;
    assert(v == 8, '20 % 12 == 8');
}

#[test]
fn test_u128_div() {
    let mut v: u128 = 20_u128;
    v /= 5_u128;
    assert(v == 4_u128, '20 / 5 == 4');
}
```

Running `cairo-compile` results in the following output:

```sh
error: Skipped tokens. Expected: Module/Use/FreeFunction/ExternFunction/ExternType/Trait/Impl/Struct/Enum or an attribute.
 --> integer.cairo:683:1
0extern fn u64_safe_divmod(a: u64, b: NonZero<u64>) -> (u64, u64) implicits(RangeCheck) nopanic;
^

error: Trait `core::traits::Div::<core::felt>` has no implementation in the context.
 --> foo.cairo:4:12
    assert(d / 5 == 4, '20 / 5 == 4');
           ^***^

error: Trait `core::traits::DivEq::<core::felt>` has no implementation in the context.
 --> foo.cairo:7:5
    v /= 5;
    ^****^

error: Trait `core::traits::Rem::<core::felt>` has no implementation in the context.
 --> foo.cairo:14:12
    assert(d % 12 == 8, '20 % 12 == 8');
           ^****^

error: Trait `core::traits::RemEq::<core::felt>` has no implementation in the context.
 --> foo.cairo:17:5
    v %= 12;
    ^*****^

error: Trait `core::traits::DivEq::<core::integer::u128>` has no implementation in the context.
 --> foo.cairo:24:5
    v /= 5_u128;
    ^*********^

Error: Compilation failed.
```

The [alpha 3 release notes](https://github.com/starkware-libs/cairo/releases/tag/v1.0.0-alpha.3) mention new `/=` and `%=` operators (and, by proxy, I would consider `/` and `%` to be supported as well). This does not seem to be the case.

Even trying to compile a function from [op_eq](https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-parser/src/parser_test_data/op_eq#L7) does not work.

```rust
fn foo() {
    let mut x = 3;
    x += 5;
    x -= 5;
    x *= 5;
    x /= 5;
    x %= 5;
    x = 5;
}
```

Error:

```sh
error: Trait `core::traits::DivEq::<core::felt>` has no implementation in the context.
 --> foo.cairo:6:5
    x /= 5;
    ^****^

error: Trait `core::traits::RemEq::<core::felt>` has no implementation in the context.
 --> foo.cairo:7:5
    x %= 5;
    ^****^

error: Skipped tokens. Expected: Module/Use/FreeFunction/ExternFunction/ExternType/Trait/Impl/Struct/Enum or an attribute.
 --> integer.cairo:683:1
0extern fn u64_safe_divmod(a: u64, b: NonZero<u64>) -> (u64, u64) implicits(RangeCheck) nopanic;
^

Error: Compilation failed.
```

**Comment by orizi** [comment]
for non-felt types - it would work if you add `use integer::U128DivEq;` for felts this wouldn't exist (as we don't want to have confusing operators for `felt` as most user won't need them.
Adding a pr that imports the `Eq` versions into the corelib for all.

**Comment by milancermak** [comment]
> as we don't want to have confusing operators for felt as most user won't need them.

How insistent are you on this decision? Is it not possible to make `/` behave like floor division (`//` operator in Python) and `%` as modulus in Cairo 1? IMO this would be much more acceptable and way less confusing than not to have these operators on `felt` at all. 

In any case, will there be a `div_rem` for `felt`s?

**Comment by clexmond** [comment]
> for non-felt types - it would work if you add `use integer::U128DivEq;` for felts this wouldn't exist (as we don't want to have confusing operators for `felt` as most user won't need them. Adding a pr that imports the `Eq` versions into the corelib for all.

Perhaps it's ok not to have `/` and `%` for `felt` but per @milancermak comment, I think it's a *big* regression to not have `unsigned_div_rem`. It makes dealing with any values `>= 2 ** 128` very difficult (i.e. intermediate overflows). Ex. where I'm having to work around it awkwardly (with loss of precision): https://github.com/influenceth/cubit/blob/main/src/core.cairo#L221

**Comment by orizi** [comment]
support for `/` and `%` for `u256` is the plan, we probably get to it pretty soon.

**Comment by clexmond** [comment]
> support for `/` and `%` for `u256` is the plan, we probably get to it pretty soon.

That's wonderful news! :)
