### ISSUE TITLE
bug: using dependencies from parent module with super doesn't allow access to methods

### ISSUE THREAD

**Issue by tarrencev** [starkware-libs/cairo#2438]
# Bug Report

**Cairo version:**

HEAD

**Current behavior:**

the following:
```
use array::ArrayTrait;
mod b {
    fn inner() {
        let mut arr = super::ArrayTrait::new();
        arr.append(1);
        return ();
    }
}
```

results in the error:

```
<error: Unknown function.
 --> lib.cairo:5:13
        arr.append(1);
            ^****^
```

**Comment by orizi** [comment]
inner modules needs to declare its own uses - as in rust as well.
in your case adding `use super::ArrayTrait;` inside the module should work.

**Comment by tarrencev** [comment]
> inner modules needs to declare its own uses - as in rust as well. in your case adding `use super::ArrayTrait;` inside the module should work.

hm im not sure the behavior is the same, since we are initializing it with `super::ArrayTrait::new()`

i tried this example in rust and it compiles fine:

```
use smol_str::SmolStr;

mod a {
    fn inner() {
        let smol = super::SmolStr::new_inline("");
        let str = smol.as_str();
    }
}
```
