### ISSUE TITLE
bug: Debug with Generic

### ISSUE THREAD

**Issue by gaetbout** [starkware-libs/cairo#2459]
# Bug Report

**Cairo version:**

Tested on: a3f2f3428610267a55fd69f36ec1648a1a33dd7e

**Current behavior:**

Trying to update the Debug Trait to use generic: 

```rust
impl PrintImpl<T, impl TInto: Into::<T>> of Print::<T> {
    fn print(self: T) {
        print_felt(self.into());
    }
}
```

And test it with:
```rust
use debug::Print;
use debug::PrintImpl;

#[test]
fn test_print() {
    assert(true, 'assert(true)');
    // 1.print();
  PrintImpl::print('1');
  // PrintImpl::print(8_u8);
  // PrintImpl::print(16_u16);
  // PrintImpl::print(32_u32);
  // PrintImpl::print(64_u64);
  // PrintImpl::print(128_u128);
  }
```
But when trying to run tests I'm running into:
```shell
Error: Compilation failed without any diagnostics. 
```
Using Into for generic should be working.
When this is solved it should also be possible to impl debug for Array<T> where T impl Into

**Comment by spapinistarkware** [comment]
It's a bug in error reporting. Your specific issue is that Into needs 2 generic params, and it tries to infer the other, and fails.

**Comment by gaetbout** [comment]
As it is a bug about error reporting, I'm assuming it should stay open.
Otherwise feel free to close it!  😄

**Comment by orizi** [comment]
Diagnostics was fixed as well at least in main.
