### ISSUE TITLE
bug: cairo-language-server CPU issue

### ISSUE THREAD

**Issue by gaetbout** [starkware-libs/cairo#2461]
# Bug Report

Even though I close and restart VSCode, some cairo-language-server processes are still active in the backround taking a significant part of the CPU %.
Need to perform:
```bash
killall cairo-language-server
```
Once in a while

**Comment by spapinistarkware** [comment]
I think it might be an issue with the extension.ts code for the vscode plugin. It's creating a new language server on activate(), maybe it;s wrong?
