### ISSUE TITLE
feat: bitwise not

### ISSUE THREAD

**Issue by milancermak** [starkware-libs/cairo#2503]
# Feature Request

**Describe the Feature Request**

So far, there's no support for bitwise not in Cairo 1. [Cairo 0 offered](https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/cairo/common/bitwise.cairo#L93) a `bitwise_not` function. [Rust has `!`](https://doc.rust-lang.org/stable/std/ops/trait.Not.html) that uses the Not trait. Cairo 1 already declares a Not trait, so what's missing is only the implementation of it on the appropriate types.

**Describe Preferred Solution**

```rust
let some_bits = 27_u8; // 0b11011
let not_some_bits = !some_bits;
assert(not_some_bits == 228_u8, 'nope'); // 228 == 0b11100100
```

**Comment by orizi** [comment]
sounds like a nice idea - although my c++ sensitivities confuses me in this case (`!` always sounds boolean to me, not bitwise) - we should ask around a bit around this before deciding (was a bit surprised myself that rust does work that way)

**Comment by milancermak** [comment]
Any news on this?
