### ISSUE TITLE
feat: better support of the "never" type.

### ISSUE THREAD

**Issue by Amxx** [starkware-libs/cairo#2567]
# Feature Request

**Describe the Feature Request**

Support `!` as a type, as [described here](https://doc.rust-lang.org/std/primitive.never.html).

As shown in the code above, this type is usefull in matching that return a type such as 
```rust
let num: u32 = match get_a_number() {
    Some(num) => num,
    None => break,
};
```

**Related Code & Additional Context**

Currently the `panic` function is defined as
```rust 
enum never {} 
extern fn panic(data: Array<felt252>) -> never;
```

but the `never` is not `!`. I tryed declaring an helper that provides a more user friendly interface to `panic`

```rust
fn throw(err_code: felt252) -> never {
    let mut data = ArrayTrait::new();
    data.append(err_code);
    panic(data)
}
```

But I run into trouble when using this `throw` function. I fell this might be caused by `never` not being a proper alternative to `!`

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No
- [x] I'd love to, but I honestly don't know where to start.

**Comment by Amxx** [comment]
> I think never is not supported on a non-inlined function because it has no representation in sierra right now. Maybe that is your issue?

Yes.

**Comment by ilyalesokhin-starkware** [comment]
The panic was fixed, but the resulting code is suboptimal as we generate an unnecessary match enum.

**Comment by orizi** [comment]
it properly worked for a while now.
