### ISSUE TITLE
bug: Invalid path when trying to use ContractAddress::zero()

### ISSUE THREAD

**Issue by milancermak** [starkware-libs/cairo#2668]
# Bug Report

**Cairo version:** bceacc24

Consider this contract:

```
#[contract]
mod YUNoZero {

    use starknet::ContractAddress;
    use starknet::ContractAddressZeroable;
    use zeroable::Zeroable;

    #[view]
    fn zero_addy() -> ContractAddress {
        ContractAddress::zero()
        // Zeroable::zero() // this works
    }
}
```

Compiling it gives the following error:

```
error: Plugin diagnostic: Invalid path.
 --> nozero.cairo:11:26
        ContractAddress::zero()
                         ^**^

Error: Compilation failed.
```

I would expect this to work though. What am I missing?

Using `Zeroable::zero()` instead of `ContractAddress::zero()` works, it compiles just fine.

**Comment by spapinistarkware** [comment]
Type::func() is not something currently supported. Note the zero is a function declared on a trait, and defined in a (named) impl, so you can access it either through Trait::zero() or Impl::zero().
