### ISSUE TITLE
feat: Add support for secp256k1 (eth/bitcoin) curve-based signature operations

### ISSUE THREAD

**Issue by Lukasz2891** [starkware-libs/cairo#2702]
# Feature Request

**Describe the Feature Request**

Add support for secp256k1 (eth/bitcoin) curve-based signature operations as it was implemented in the cairo 0.10.3, especially ```recover_public_key``` from message/message_hash and the given signature. The keccak32 hash function may be needed as a dependency.

**Describe Preferred Solution**

* Implement the secp_* elliptic-curve algebra.
* Add keccak32 hash function
* Implement the ```recover_public_key``` function.

**Related Code**

https://github.com/starkware-libs/cairo-lang/tree/master/src/starkware/cairo/common/cairo_secp

**Comment by orizi** [comment]
We are currently working on it :)

**Comment by FawadHa1der** [comment]
@ozi is there a PR for it?

**Comment by orizi** [comment]
not yet - but we are currently designing the solution, and then we'll code it (this would involve adding some new `extern fn`s.

**Comment by FawadHa1der** [comment]
Thanks for the reply @orizi are we talking before Regenesis or after?

**Comment by orizi** [comment]
Definitely before, this is part of Cairo0 parity.

**Comment by drcapybara** [comment]
is keccak fully implemented in cairo 1.0?

**Comment by Lukasz2891** [comment]
> is keccak fully implemented in cairo 1.0?

There is keccak implemented in rc0.

But I have another question: if the ecdsa support was a part of cairo0-parity, why the ecdsa is still not included in release candidate (0)?

**Comment by FawadHa1der** [comment]
I see this has been merged into the main branch. Testable yet on testnet?

**Comment by orizi** [comment]
This is indeed already available on testnet :) (almost on mainnet)
