### ISSUE TITLE
bug: array_slice panics when sum of lengths of sliced arrays is equal to the base-array length

### ISSUE THREAD

**Issue by Lukasz2891** [starkware-libs/cairo#2703]
# Bug Report

**Cairo version:**

1.0.0-alpha6

**Current behavior:**

```array_slice``` panics with the case, when the array is sliced to 2 parts, which sum of lengths is equal to the base-array length.

```rust
let mut arr = array_new();

arr.append(0x00_u8);
arr.append(0x01_u8);
arr.append(0x02_u8);
arr.append(0x03_u8);
arr.append(0x04_u8);
arr.append(0x05_u8);
arr.append(0x06_u8);
arr.append(0x07_u8);
arr.append(0x08_u8);
arr.append(0x09_u8);

let x = slice_tail(arr, 0_usize, 10_usize);
```

crashes/panics.

**Expected behavior:**

```rust
let x = slice_tail(arr, 0_usize, 10_usize)
```

returns the 2 arrays of which the first one is the base array and the second one is empty.

**Steps to reproduce:**

as above

**Related code:**

as above

**Comment by orizi** [comment]
i don't know where exactly you've got `slice_tail` from.
using:
```
use array::ArrayTrait;

#[test]
fn test() {
    let mut arr = ArrayTrait::new();

    arr.append(0x00_u8);
    arr.append(0x01_u8);
    arr.append(0x02_u8);
    arr.append(0x03_u8);
    arr.append(0x04_u8);
    arr.append(0x05_u8);
    arr.append(0x06_u8);
    arr.append(0x07_u8);
    arr.append(0x08_u8);
    arr.append(0x09_u8);
    
    let x = array::array_slice(@arr, 0_usize, 10_usize);
}
```
worked just fine for me.

**Comment by orizi** [comment]
at latest - note that at alpha6 - array_slice wasn't added yet.

**Comment by Lukasz2891** [comment]
I'll dbl check it tommorrow :)

**Comment by orizi** [comment]
indeed exact end returned None instead of the actual slice - fixing it.

thanks!
