### ISSUE TITLE
bug:  incompatible types when using implicit returns 

### ISSUE THREAD

**Issue by ccolorado** [starkware-libs/cairo#2718]
# Bug Report

**Cairo version:**
1.0

**Current behavior:**

Getting errors when using implicit returns: 

⠉ Testing exercises/options/options1.cairo...
error: If blocks have incompatible types: "core::option::Option::<?1>" and "()"
 --> options1.cairo:25:5
    if time_of_day < 22_usize {
    ^*************************^

error: If blocks have incompatible types: "core::option::Option::<?3>" and "()"
 --> options1.cairo:28:5
    if time_of_day < 24_usize {
    ^*************************^

⠒ Testing exercises/structs/structs3.cairo...
error: If blocks have incompatible types: "core::bool" and "()"
 --> structs3.cairo:36:9
        if self.sender_country != self.recipient_country {
        ^************************************************^

Sample code on this commit.
https://github.com/shramee/starklings-cairo1/commit/ee4dced03c681dda04cd27359c57798ca0f6e8c5

I was working on the [starklings ](https://github.com/shramee/starklings-cairo1)  and I noticed this strange behavior only when using implicit returns within if statements.

As far as I can tell this is an issue with not having explicitly the return keyword.

**Expected behavior:**
Implicit returns should work no mater if inside or outside conditional statements

**Steps to reproduce:**
1. Clone repo https://github.com/ccolorado/starklings-cairo1/
2. Checkout branch https://github.com/ccolorado/starklings-cairo1/tree/head_scratching
3. Include the comment // I AM NOT DONE on the error to reproduce
4. run `cargo run --bin starklings watch`

**Related code:**

**Comment by spapinistarkware** [comment]
I don't understand the issue. Please provide a minimal code sample that reproduces the issue

**Comment by orizi** [comment]
```
    if time_of_day < 24_usize {
        Option::Some(0_usize) 
    }
```
note that this code example is the same as:
```
    if time_of_day < 24_usize {
        Option::Some(0_usize) 
    } else {
        ()
    }
```
So the types are actually incompatible.
In this case you probably want:
```
    if time_of_day < 24_usize {
        return Option::Some(0_usize);
    }
```

**Comment by ccolorado** [comment]
The code samples on the commit are these. 
@orizi I think the behavior might be different.
 
```cairo
  // Example 1
  // [ works ]
  if self.sender_country == self.recipient_country {
      return false;
  }
  return true;

  // [ doesn't work ]
  // if self.sender_country != self.recipient_country {
  //     true
  // }
  // false

  // Example 2
  // [ works ]
  if time_of_day < 22_usize {
      Option::Some(5_usize)
  } else if time_of_day < 24_usize {
      Option::Some(0_usize)
  } else {
      Option::None(())
  }

  // [ doesn't work ]
  // if time_of_day < 22_usize {
  //     Option::Some(5_usize)
  // }
  // if time_of_day < 24_usize {
  //     Option::Some(0_usize) 
  // }
  // Option::None(())
```

**Comment by orizi** [comment]
the examples you gave that didn't work - also shouldn't work.
you should look at every `if` statement as if it has an empty `else` clause.
Since `if` and `else` must return the same type (as they are the same block) - in this case the `if` block must return the unit type `()`, so it should end with `;`.
Note that generally - an implicit return just means that the function returns the return value of the functions block, not just any line without a `;`

**Comment by ccolorado** [comment]
Thanks for the explanation. This wasn't clear to me.
