### ISSUE TITLE
bug: Cairo lang server Crashes

### ISSUE THREAD

**Issue by Mehul0011** [starkware-libs/cairo#2722]
# Bug Report

**Cairo version:**
1.0.0-alpha.6

**Current behavior:**
Cairo lang server crashes multiple times and connection gets closed

**Expected behavior:**
Should not Crash

**Steps to reproduce:**
I dont know what part of the code causes this, as the same extension does not crash on the compiler repo.

**Related code:**

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', crates/cairo-lang-semantic/src/corelib.rs:572:60
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 9:52:05 AM] Connection to server got closed. Server will restart.
[Error - 9:52:05 AM] Request textDocument/semanticTokens/full failed.
Error: Connection got disposed.
```

![image](https://user-images.githubusercontent.com/75808688/229982220-27548bec-6d81-4e79-ab42-2d9631236460.png)

**Comment by mkaput** [comment]
Hey! You have installed Cairo LS from HEAD and use it with Scarb 0.1 project. Please downgrade LS to 1.0.0-alpha.6. You must use precisely the commit tagged as such.

**Comment by Mehul0011** [comment]
Thankyou for the help, that fixed my issue !!

**Comment by mkaput** [comment]
We plan to bundle LS with Scarb, so that this will not happen in the future. We track the work here: https://github.com/software-mansion/scarb/issues/221
