### ISSUE TITLE
feat: add min and max comparison functions

### ISSUE THREAD

**Issue by milancermak** [starkware-libs/cairo#2723]
# Feature Request

Pretty much every modern language has a `min` and `max` function to compare two numerical values and return the smaller or greater one. It would be great if Cairo had them in stdlib as well.

**Describe Preferred Solution**

```rust
let a = 1_u16;
let b = 2_u16;
assert(min(a, b) == 1_u16, '1 < 2');
assert(max(a, b) == 2_u16, '2 > 1');
```

The functions should be available for all integer types in stdlib. Preferably, there should be a way how to have min/max working on user defined types as well.

**Comment by spapinistarkware** [comment]
Should be easy. Anyone wants to take this?

**Comment by zjhmale** [comment]
working on this
