### ISSUE TITLE
feat: add size_of

### ISSUE THREAD

**Issue by milancermak** [starkware-libs/cairo#2733]
# Feature Request

I want to propose adding a `size_of` function to the language that would return the storage slot size of a specific type. 

When writing `StorageAccess` implementations for custom types, it would be great to programmatically get a value for the offset for use in `storage_address_from_base_and_offset` instead of hardcoding it. This is a Starknet specific request, I'm not sure if it would be valuable for pure Cairo.

An example:

```rust
struct Point {
    x: u32,
    y: u32
}

struct Size {
    width: u32,
    height: u32
}

struct Rect {
    origin: Point,
    size: Size
}

let origin = Point { x: 0_u32, y: 0_u32 };
let square = Rect { origin , size: Size { width: 30_u32, height: 30_u32 } };

assert(origin.x.size_of() == 1_usize, 'u32 size 1');
assert(origin.size_of() == 2_usize, 'point size 2');
assert(square.size_of() == 4_usize, 'rect size 4');

// alternatively
assert(size_of(square) == 4_usize, 'rect size 4');
assert(Rect::size_of() == 4_usize, 'rect size 4');
```

**Comment by orizi** [comment]
I'm not sure we really want this - as this depends on the size of the underlying system.
Currently we are felt252 based - but we can be just as well felt64 based.
what is the size of felt252 then?
it is 1 in the current system - but it is 4 on the new system.

**Comment by mkaput** [comment]
Isn't the whole purpose of `sizeof` precisely to deal with changing memory unit sizes depending on compilation target?

I think a slightly more complicated design of `sizeof` could still work in context of the issue described by @orizi: first, the _layout_ of a memory segment over which sizeof is applied has to be described.

```rust
struct Point {
    x: felt252,
    y: felt252,
}

let layout252 = Layout::felt252();
assert(layout252.sizeof::<Point>() == 2_usize, "felt252");

let layout64 = Layout::felt64();
assert(layout64.sizeof::<Point>() == 8_usize, "felt64");
```

This is kinda similar to Rust's [`std::alloc::Layout`](https://doc.rust-lang.org/stable/std/alloc/struct.Layout.html)

**Comment by spapinistarkware** [comment]
@mkaput The idea is that we don't assume the Cairo1 will get recompiled. We want the generated sierra to be felxible, and work for both.
Another problem with this request IMO is that what you want is not really the size of the object. You want the size of its serialization to felt252. I believe the right way to do this, is just to serialize it.

**Comment by mkaput** [comment]
> We want the generated sierra to be felxible, and work for both.

Ah, that makes sense! Indeed, in this case, the most straightforward thing would be to do the serialization.

Performance-wise, I do though see a possibility to define a libfunc that would return the size 🤔 In that scenario, the Sierra code will still be independent of target architecture
