### ISSUE TITLE
feat: build impl of contract interface

### ISSUE THREAD

**Issue by tarrencev** [starkware-libs/cairo#2742]
# Feature Request

Currently when implementing an interface in a contract module, the impl is not exported to the built contract abi.

```
trait IContract {
   fn foo();
}

#[contract]
mod Contract {
   impl ContractImpl of IContract {
      #[view]
      fn foo() {}
   }
}
```

`foo` abi is not generated. it would be great if this was the case, since it allows for compile time enforcement of interface compatibility.

**Describe Alternatives**

Don't have compile time interface compatibility checks

**Comment by orizi** [comment]
I think this is no longer relevant in corrent starknet plugin structure - or implemented with:
```
trait IContract<TCS> {
   fn foo(self: @TCS);
}

#[starknet::contract]
mod Contract {
   #[include(v0)]
   impl ContractImpl of IContract {
      #[external]
      fn foo(self: @ContractState) {}
   }
}
```
