### ISSUE TITLE
bug: cairo-language-server crash 

### ISSUE THREAD

**Issue by notV4l** [starkware-libs/cairo#2759]
# Bug Report

**Cairo version:**

alpha 6

**Current behavior:**

crash with error : Request textDocument/semanticTokens/full failed

**Expected behavior:**

no crash

**Steps to reproduce:**

in my case, i attempted to access an array value with [ ] 

**Related code:**

```
fn main() -> Array<u8> {
    let mut arr: Array<u8> = ArrayTrait::new();
    let first = arr[0];      // <---- this make it crash

    arr
}
```

**Comment by orizi** [comment]
this is solved at head AFAIK - will be fixed on next release which should be rather soon.
