### ISSUE TITLE
bug: Turbofish syntax mandatory in tuple return types

### ISSUE THREAD

**Issue by enitrat** [starkware-libs/cairo#2760]
# Bug Report

**Cairo version:**
c081f05aa67e538e7a51607b1c0ebb47f73dd9f1

**Current behavior:**
The turbofish syntax Array::<T> is mandatory when specifying the types inside a returned tuple

**Expected behavior:**
We should be able to specify `-> (Array<T>)`

**Steps to reproduce:**
```rust
use array::ArrayTrait;
fn main() {
    let arr1 = ArrayTrait::<u128>::new();

    let (arr2, len) = calculate_length(arr1);
}

fn calculate_length(arr: Array<u128>) -> (Array<u128>, usize) {
    let length = arr.len(); // len() returns the length of a String

    (arr, length)
}

```

**Related code:**

**Other information:**
This works correctly
```rust

fn calculate_length(arr: Array<u128>) -> Array<u128> {
    let length = arr.len(); // len() returns the length of a String

    arr
}

```

**Comment by orizi** [comment]
We are aware of this. This is a nice first issue if anyone wants to try and contribute.
This will require the parser to be aware it is parsing a type context even when parsing tuples within it.
