### ISSUE TITLE
feat: long strings syntax for use in attributes

### ISSUE THREAD

**Issue by mkaput** [starkware-libs/cairo#2777]
# Feature Request

**Describe the Feature Request**

Although long strings are far from being implemented in Cairo at runtime, compile-time parts of the language (namely attributes) could already make a good use of them.

**Describe Preferred Solution**

1. Add syntax for `"long string"` literals and allow them in expression context.
2. Reject long literals during expression lowering phase, but leave them intact for attributes.

**Additional Context**

@MaksymilianDemitraszek correct me if I'm wrong, but I recall that there was an idea for some attributes in Protostar that required long strings, wasn't it?

**Comment by orizi** [comment]
no longer relevant - as we actually have "long string" syntax for long strings.
