### ISSUE TITLE
feat: support dw (Define word) from Cairo 0

### ISSUE THREAD

**Issue by theyoga** [starkware-libs/cairo#2784]
# Feature Request

Support `dw` to enable "static data as code" use-cases like in Cairo 0:
https://www.cairo-lang.org/docs/how_cairo_works/define_word.html

**Describe Preferred Solution**

Should provide similar functionality to Cairo 0:
https://www.cairo-lang.org/docs/how_cairo_works/define_word.html

**Comment by spapinistarkware** [comment]
This related to const expressions. Const array, in this case.

**Comment by mkaput** [comment]
#3213 duplicates this
