### ISSUE TITLE
bug: double free error

### ISSUE THREAD

**Issue by 0xAsten** [starkware-libs/cairo#2787]
# Bug Report

**Cairo version:**
1.0

**Current behavior:**
The following code will compile means the `arr0` is still valid?
```
fn main() {
    let arr0 = ArrayTrait::new();
    let arr1 = arr0;

    arr0.span().snapshot.clone().print();
}
```

**Expected behavior:**
I think the `arr0` should be invalidated after `let arr1 = arr0;`. 
When `arr0` and `arr1` go out of scope, they will both try to free the same memory.

**Comment by orizi** [comment]
arr0 and arr1 point to the same thing - if you'd try and use arr1 you'd get an invalidation.
so we probably should enhance this - but there's no bug here.
the `free` would only happen once here.

**Comment by orizi** [comment]
anyway - for now closing the issue as this is isn't a bug - but feel free to add to the conversation if we should actually block this.
(currently it is simply that `arr0` and `arr1` are 2 different names fo rthe same thing.
