### ISSUE TITLE
feat: Support for more ECDSA features

### ISSUE THREAD

**Issue by Leonard-Pat** [starkware-libs/cairo#2797]
# Feature Request

**Describe the Feature Request**

Add more builtin ECDSA functions, notably recover signer from a signed message.
This would allow a the public key to be recovered from a signed message

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [x] No

**Comment by orizi** [comment]
can you please write the signature of the function you actually expect?
because i'm not sure i fully understand the request here - thanks!

**Comment by Leonard-Pat** [comment]
Similar to the old cairo_secp module 
recover_public_key(msg_hash: felt252, r: felt252, s: felt252) -> felt252
With the given r, s and message has you can reocver the public key of the signer

**Comment by archseer** [comment]
@orizi Could we also add signing? That would allow tests to generate signatures for example

**Comment by orizi** [comment]
IIUC signing requires cryptographically secure random number generator - and therefore cannot be performed here.

This can obviously be done at some testing library if some random is provided.
