### ISSUE TITLE
bug: Division operator cant be found on contract

### ISSUE THREAD

**Issue by ermvrs** [starkware-libs/cairo#2818]
# Bug Report

**Cairo version:**

Alpha 7

**Current behavior:**

```
    fn as_u256(high: u128, low: u128) -> u256 {
        u256 { low, high } }
    let happens_amount:u256 = as_u256(3_u128, 2_u128) / as_u256(1_u128, 1_u128);
```

**Error when tried to build**

`error: Plugin diagnostic: Trait has no implementation in context: core::traits::Div::<core::integer::u256>
 --> market.cairo:179:35
        let happens_amount:u256 = as_u256(3_u128, 2_u128) / as_u256(1_u128, 1_u128); `

**Other information:**

I followed the similar use at corelib operator tests.

**Comment by orizi** [comment]
was not replicated on main - so will be fixed at the next release.
