### ISSUE TITLE
dev: Autogenerated files using get_codes

### ISSUE THREAD

**Issue by taco-paco** [starkware-libs/cairo#2868]
As you know some of the existing files are like: `ast.rs`, `kind.rs`, `key_fields.rs` are autogenerated right now. In my opinion, this method lacks transparency and requires consistent monitoring of `cairo_spec.rs`. Additionally, it introduces a dependency on nightly features, which may not be ideal.
I would like to propose an approach that `salsa` uses with `salsa::query_group` procedural macros. 

Where instead we would declare structs directly in `ast.rs` the following way:

```
#[generator::generate_node(node(modifiers, ModifierList), node(arg_clause, ArgClause))]
pub struct Arg;
```

or

```
#[generator::generate_node(Arg, node(modifiers, ModifierList), node(arg_clause, ArgClause))]
```

Thus user will have access to new nodes right away without caring about updating `cairo_codes` and generating new files. As for `kind.rs`, `key_fields.rs` they can be generated using the same approach as `salsa::database` marco does does eg `generator::kind(Arg, ArgClauseUnnamed, ...)` or left for users(devs) to fill since without that compiler will throw error that `Arg` implementation uses unknown `SyntaxKind`

**Comment by spapinistarkware** [comment]
The current method is easy to use and maintain, from my experience. I don't see a need to do something else.
This approaches are also taken in other projects (such as rust-analyzer).
