### ISSUE TITLE
bug: Failed setting up runner. using Span<felt252> and []

### ISSUE THREAD

**Issue by gaetbout** [starkware-libs/cairo#2881]
# Bug Report

**Cairo version:**

Tested at https://github.com/starkware-libs/cairo/commit/55fd9d0f6d4ba4708a69e51672002ca20b411d14

**Steps to reproduce:**

Copy paste this test and run it;
```rust
use box::BoxTrait;
use array::SpanTrait;

#[test]
#[available_gas(20000000)]
fn test_gaetbout_is_annoying_and_found_a_bug() {
    let tx_info = starknet::get_tx_info().unbox();
    let signer = *tx_info.signature[0];
    let signer_r = *tx_info.signature[1];
}

```
When running it produces:
```shell
Error: Failed setting up runner.

Caused by:
    #165: [15] is undefined.
```

However when using `.at(x)` it works as expected.

**Comment by orizi** [comment]
Currently fixed at main.
