### ISSUE TITLE
Generic args in import path. 

### ISSUE THREAD

**Issue by taco-paco** [starkware-libs/cairo#2883]
Hello, while reading `parser.rs` file specifically `expect_use` function I got a question if smth like this is possible?
`use some::path::type<T>;
`. Where T is some type;

This question comes from the fact that `expect_use` eventually calls `parse_path_segment` which inside has the following case.
https://github.com/starkware-libs/cairo/blob/55fd9d0f6d4ba4708a69e51672002ca20b411d14/crates/cairo-lang-parser/src/parser.rs#L1418

If that is the case then probably it would be worth mentioning in docs or a new book, if not then I would assume that this is a bug because it doesn't fall in `use` grammar. So I would expect to see smth like this instead.

```
    fn parse_path_segment_for_use(&mut self) -> (PathSegmentGreen, Option<TerminalColonColonGreen>) {
        let identifier = match self.try_parse_identifier() {
            Some(identifier) => identifier,
            None => {
                return (
                    self.create_and_report_missing::<PathSegment>(
                        ParserDiagnosticKind::MissingPathSegment,
                    ),
                    // TODO(ilya, 10/10/2022): Should we continue parsing the path here?
                    None,
                );
            }
        };
        match self.try_parse_token::<TerminalColonColon>() {
            _ => {
                (PathSegmentSimple::new_green(self.db, identifier).into(), optional_separator)
            }
        }
    }
```

**Comment by orizi** [comment]
It is just checked at the semantic layer and not in the parser level.
This indeed can happen earlier.

**Comment by orizi** [comment]
`use some::path::type<T>;` would fail - as it is not a type clause - so turbofish is required.
turbofish `use some::path::type::<T>;` would fail as well - but only at the semantic level.
