### ISSUE TITLE
bug: trait/impl resolution no longer working with generic types

### ISSUE THREAD

**Issue by enitrat** [starkware-libs/cairo#2899]
# Bug Report

**Cairo version:**
0b0392a461ca035c896308d199681164306f3e00

**Current behavior:**
The following code throws the following error:
```rust
struct Vec<T> {
    items: Felt252Dict<T>,
    len: usize,
}

impl DestructVec<T, impl TDrop: Drop::<T>> of Destruct::<Vec<T>> {
    fn destruct(self: Vec<T>) nopanic {
        self.items.squash();
    }
}

```

```console
Method `squash` not found on type "core::dict::Felt252Dict::<GenericParamType(quaireaux_data_structures::vec::DestructVec::T)>". Did you import the correct trait and impl?
```

The same problem happens with
```rust
fn vec_new<T>() -> Vec<T> {
    let items = Felt252DictTrait::<T>::new();
    Vec { items, len: 0_usize }
}
```
```console
Trait has no implementation in context: core::dict::Felt252DictTrait::<GenericParamType(quaireaux_data_structures::vec::vec_new::T)>
```

**Expected behavior:**
Compilation happens successfully

**Steps to reproduce:**

**Related code:**
Run the code above.

**Other information:**
It used to work before I updated the compiler to the last version. I'm not entirely sure what's causing this issue, but it looks like an issue when resolving the trait methods with generic arguments.

**Comment by orizi** [comment]
The issue is a missing `, impl TFelt252DictValue: Felt252DictValue::<T>` in the generic args - as now dict prevents problematic code by adding this high level request on the value type.
we do need to understand why the diagnostic was so unclear (i found it only after doing several iterations of simplifying the code)
