### ISSUE TITLE
feat: testing events support

### ISSUE THREAD

**Issue by andrew-fleming** [starkware-libs/cairo#2931]
# Feature Request

**Describe the Feature Request**

Add support for testing that our contracts emit events correctly.

**Describe Preferred Solution**

The obvious solution would be to include emitted events in tx receipts, but that also requires having tx receipts in the test runner.

**Describe Alternatives**

Unsure of viable alternative solutions in the short term—just placing this issue so it can be tracked and potentially discussed.

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [x] No

**Comment by spapinistarkware** [comment]
Guidance on how to implement this:
* At crates/cairo-lang-runner/src/casm_run/mod.rs, in StarknetState, add a Mapi form contract address (Felt252) to a vector of logs.
* On corelib/src/starknet/testing.cairo, add a testing function, e.g. `extern fn pop_log(ContractAddress) -> Option<Array<felt252>>;
* At crates/cairo-lang-sierra/src/extensions/modules/starknet/testing.rs, add the sierra function for this test function
* At crates/cairo-lang-runner/src/casm_run/mod.rs, add handling for the hint
* Add a test here crates/cairo-lang-starknet/cairo_level_tests/lib.cairo

**Comment by chirag-bgh** [comment]
I will take this.

**Comment by spapinistarkware** [comment]
Eric already took this

**Comment by chirag-bgh** [comment]
> Eric already took this

Okay np, is there anyting I can work on?

**Comment by spapinistarkware** [comment]
Hmm.. how about adding support for ".0" access for tuples?

**Comment by chirag-bgh** [comment]
> Hmm.. how about adding support for ".0" access for tuples?

That would be interesting! Could you please create a issue for the same?

**Comment by orizi** [comment]
pop_log now exists in starknet/testing.cairo
