### ISSUE TITLE
feat: `continue` for loops

### ISSUE THREAD

**Issue by tserg** [starkware-libs/cairo#2939]
# Feature Request

Currently, there is only `break` for loops. However, there are instances where we want to skip the current iteration but continue with the loop to continue

**Describe Preferred Solution**

Add `continue` for loops

**Comment by spapinistarkware** [comment]
Open for contribution.
This requires:
* Adding the syntax for continue:
  * Change cairo_spec.rs, run the generate-syntax binary, fix parser.
  * Add the statement in the semantic crate (look for the break syntax and do similarly)
  * In lowering crate, at crates/cairo-lang-lowering/src/lower/mod.rs, handle the continue similarly to break, but use `call_loop_func()` to add a recursive call

**Comment by gaetbout** [comment]
I'll try and to this one next week!

**Comment by mkaput** [comment]
> I'll try and do this one next week!

@tserg is already workingo n this in #2947

**Comment by tserg** [comment]
@gaetbout I am new to Rust so if you are interested to work together on this, I'll be most happy to do so!
