### ISSUE TITLE
bug: storing Nullable in Felt252Dict

### ISSUE THREAD

**Issue by greged93** [starkware-libs/cairo#2946]
# Bug Report

**Cairo version:** 81c4eb94

**Current behavior:** Fail to store Nullable<felt252> inside a Felt252Dict. Throws the following error:`Got an exception while executing a hint: Expected integer at address 1:29`.

**Expected behavior:** Expect the ability to store a Nullable<felt252> inside a Felt252Dict

**Steps to reproduce:**

Run the below code with `cairo-test`:
```
#[test]
#[available_gas(2000000)]
fn test_nullable() {
    let mut d: Felt252Dict<Nullable<felt252>> = Felt252DictTrait::new();
    let n: Nullable<felt252> = nullable_from_box(BoxTrait::new(1));

    d.insert(0, n);
}
```

**Comment by orizi** [comment]
The rust implemented hints seems to currently assume all dict values must be integers, which does seem to create some issues - looking over it.
