### ISSUE TITLE
feat: "pub" visibility

### ISSUE THREAD

**Issue by spapinistarkware** [starkware-libs/cairo#2953]
Add "pub" modifier to language items and struct members.

Guidance:
* Add syntax elements in cairo_spec.rs, and run `cargo run --bin generate-syntax`
* Add parsing logic in parser.rs
* Add the visibility modifier on semantic models of items (Example: priv_struct_definition_data() function computes the semantic data for the struct item and members on the `StructDefinitionData` and `Member` structs.
* Change path resolution logic at `crates/cairo-lang-semantic/src/resolve/mod.rs` to report a diagnostic when encountering a non pub segment - when not first segment.
* On compute.rs, when constructing / destructing structs or accessing member, check their visibility as well, and report diagnostics if needed.

**Comment by 0xethsign** [comment]
hey, im willing to take this up
can give some more pointers to start on this?

**Comment by spapinistarkware** [comment]
Read the first message:)

**Comment by Jinwei1987** [comment]
hello, is this issue still open for help?

**Comment by spapinistarkware** [comment]
Yep, still open

**Comment by Jinwei1987** [comment]
I want to give it a go :)

**Comment by spapinistarkware** [comment]
Awsome

**Comment by Jinwei1987** [comment]
I have some initial commit to parse visibility and add to struct member. Compute logic will be added later on. But it will be good that if you could have a review in advance to make sure I do it correctly.

**Comment by Jinwei1987** [comment]
I have some initial commit to parse visibility and add to struct member. Compute logic will be added later on. But it will be good that if you could have a review in advance to make sure I do it correctly.

**Comment by Jinwei1987** [comment]
I have some initial commit to parse visibility and add to struct member. Compute logic will be added later on. But it will be good that if you could have a review in advance to make sure I do it correctly.

**Comment by spapinistarkware** [comment]
Done at #3457. Thanks!
