### ISSUE TITLE
feat: Make Serde non-owning

### ISSUE THREAD

**Issue by spapinistarkware** [starkware-libs/cairo#2955]
Change the Serde trait, and make serialize() has this signature:
```
fn serialize(self:@T, ref output: Array<felt252>);
```
instead of 
```
fn serialize(ref output: Array<felt252>, input: T);
```

This has 2 outcomes:
* serialize needs only the non-owning verison `@T`.
* serialize cna be used as a method on T.

change it in traits.cairo, and fix everything that fails.

**Comment by wraitii** [comment]
I'm looking into this one
