### ISSUE TITLE
feat: Derives with generics

### ISSUE THREAD

**Issue by spapinistarkware** [starkware-libs/cairo#2956]
Today, you can derive some trait impls on types, e.g.:
```
#[derive(Copy)]
struct A {
  a: u8
}
```
But, it doesn't work for items with generics, like this:
```
#[derive(Copy)]
struct A<T> {
  a: T
}
```

The relevant file is derive.rs
You should probably look up the generic parameters from the AST, and add the proper generic arguments in the derived impl. For example:

```
impl ACopy<T, impl TCopy: Copy<T>> of Copy<A<T>>;
```

**Comment by wraitii** [comment]
Working on this
