### ISSUE TITLE
feat: Support u256 literals

### ISSUE THREAD

**Issue by spapinistarkware** [starkware-libs/cairo#3026]
Support literals such as `123_u256`.
Guidance:
* Add an impl for `NumericLiteral<u256>` at integer.cairo.
* On lower/mod.rs, at `lower_expr_literal()`, handle `u256` specifically by introducing a `StructConstruct` statement.

**Comment by greged93** [comment]
hey @spapinistarkware, can I try this one?

**Comment by spapinistarkware** [comment]
Yes
