### ISSUE TITLE
bug: non-deterministically encountering Error: Failed setting up runner. when running cairo-test

### ISSUE THREAD

**Issue by enitrat** [starkware-libs/cairo#3031]
# Bug Report

**Cairo version:**
8a160d3d7c00f7abada689cb3fbc1bb6daba072b

**Current behavior:**
When running  `cairo-test --starknet .`, the test runner fails with error 
```
Error: Failed setting up runner.

Caused by:
    Failed calculating gas usage, it is likely a call for `gas::withdraw_gas` is missing.
```

It's very weird, because it doesn't happen everytime. I'm writing tests against deployed contracts, using the following code: 
```rust
use starknet::syscalls::deploy_syscall;
use starknet::class_hash::Felt252TryIntoClassHash;
use starknet::contract_address::contract_address_const;
use starknet::ContractAddress;
use starknet::testing;
use starknet::get_contract_address;
use traits::Into;
use traits::TryInto;
use option::OptionTrait;
use result::ResultTrait;
use array::ArrayTrait;
use debug::PrintTrait;


use simple_vault::vault::Vault;
use simple_vault::vault::IVaultDispatcher;
use simple_vault::vault::IVaultDispatcherTrait;
use tests::mocks::mock_erc20::MockERC20;
use tests::mocks::mock_erc20::IMockERC20Dispatcher;
use tests::mocks::mock_erc20::IMockERC20DispatcherTrait;
use openzeppelin::token::erc20::IERC20Dispatcher;
use openzeppelin::token::erc20::IERC20DispatcherTrait;

fn setup() -> (IMockERC20Dispatcher, IVaultDispatcher) {
    // Set up.

    // Deploy mock token.

    let user1 = contract_address_const::<0x123456789>();

    let mut calldata = ArrayTrait::new();
    let name = 'Mock Token';
    let symbol = 'TKN';
    calldata.append(name);
    calldata.append(symbol);

    let (token_address, _) = deploy_syscall(
        MockERC20::TEST_CLASS_HASH.try_into().unwrap(), 0, calldata.span(), false
    ).unwrap();

    let mut calldata = ArrayTrait::<felt252>::new();
    calldata.append('Mock Token Vault');
    calldata.append('vwTKN');
    calldata.append(token_address.into());
    let (vault_address, _) = deploy_syscall(
        Vault::TEST_CLASS_HASH.try_into().unwrap(), 0, calldata.span(), false
    ).unwrap();

    let token = IMockERC20Dispatcher { contract_address: token_address };
    let vault = IVaultDispatcher { contract_address: vault_address };

    (token, vault)
}

#[test]
#[available_gas(2000000000000)]
fn test_atomic_deposit_withdratest_atomic_deposit_withdraww() {
    let (underlying, vault) = setup();
    let alice = contract_address_const::<0x123456789>();
    testing::set_contract_address(alice);
    underlying.mint(alice, 100.into());
    // //TODO fix: calling underlying.approve() here causes a failed calculating gas usage here
    underlying.approve(vault.contract_address, 100.into());

   //  snip
}
 ```

I haven't been able to isolate the problem, as it worked fine when I used tried to setup a smaller repo with just ERC20 + testing mocks for mint/approval. I can provide more context with the full repository if required, but it's changing constantly and subject to a lot of changes.
**Expected behavior:**
The test runs fine

**Steps to reproduce:**

**Other information:**

Halfway through redacting this, I actually re-tested to see what happened when I uncommented the `underlying.approve(vault.contract_address, 100.into());`, and it ran; but after removing the `TODO` comment above, it stopped running. This non-determinism is quite odd 🤔 . I can't figure out how to reproduce it reliably. The code and its dependencies don't rely on any recursive function or loop.

The non-determinism is the most surprising part, as randomly commenting - uncommenting lines seems to fix it for a while, before modifying the file again and breaking it.

**Comment by orizi** [comment]
I can't really replicate this as i don't really have the `use`s available - can you maybe create an example without additional files?
thank you!

**Comment by enitrat** [comment]
Thanks for looking into this @orizi. As I said I couldn't set up a minimal reproducible example, and was not able to isolate the bug.

Here is a repository you can look at: https://github.com/enitrat/cairo-runner-bug
Here's what happens when I try to run `cairo-test`. In the example below, I ran only the test that caused the issue, which is located in `tests/cairo-test/test/test_vault.cairo`, 3 times in a row, without changing anything to any file.

<img width="643" alt="image" src="https://user-images.githubusercontent.com/60658558/236150284-7ba18271-f931-4ba5-85c5-e97220144a01.png">

As you see, it worked twice, but failed once. I know it's not very useful given that it could come from a lot of places, but it's the best I can provide for now :/

**Comment by orizi** [comment]
will look now - thanks!

**Comment by enitrat** [comment]
It's super weird: I worked on some stuff today and moved some files, and the error in the test I mentioned previously is gone. I can't figure out why. 

But, it still occurs for another test at two specific locations:
https://github.com/enitrat/cairo-runner-bug/blob/mathieu_challenge_vault/test/cairo-test/tests/test_erc4626.cairo#L302
and
https://github.com/enitrat/cairo-runner-bug/blob/mathieu_challenge_vault/test/cairo-test/tests/test_erc4626.cairo#L326

**Comment by orizi** [comment]
it seems that at least for now it consistently fails at main :\

**Comment by enitrat** [comment]
> it seems that at least for now it consistently fails at main :\

_it works on my machine !_
Joke apart, I just updated to the last main, and now it consistently fails at main as well. Could the last commits related to cost calculations be related to this?

**Comment by enitrat** [comment]
Is there anything I can do to ease the bug-tracking process? 
I really don't know how I can isolate the bug. I tried to, with no success.
Perhaps it's related to the complexity of the tests, the amount of tests to run, or the "inheritance" relation between contracts which is a bit hacky.

**Comment by clexmond** [comment]
I have the exact same issue with cubit. Easily reproducible by just trying to run `make test` with https://github.com/influenceth/cubit

To see the non-determinism, try commenting out various test suites, some combos will run, some won't with seemingly no pattern.

**Comment by orizi** [comment]
i managed to remove some of the nondeterminism in the compilation - still attempting to create a non huge example.

**Comment by tserg** [comment]
A new observation:
- The tests worked after splitting into smaller files. However, if I just add a single line to a setup function calling `hash::pedersen`, then some files fail again. Moving the test functions in these files back into a larger file resolved the issue for some reason.

**Comment by OthmanSefraoui** [comment]
I am facing the same issue, and it's impossible to isolate the problem.

**Comment by orizi** [comment]
After removing all the bad randomness (now the bug get recreated only by the actual order stated in the `.toml` file).
It seems the actual cause is that the used solver we used to solve gas equations was too weak in some cases, so the ordering of the functions caused have a different number of variables that when over a certain threshold made the solver fail.
(validated through changing the solver to a more heavy solver, which worked)

My plan now is to reduce the size of the equations by solving "leaf" functions first and going up.

**Comment by orizi** [comment]
having a less naive algorithm for adding constraints seemed to have sufficed for now.
attached a pr.

please feel free to test other large projects on it and tell me what you see.
I apologise for the long wait.

**Comment by clexmond** [comment]
> having a less naive algorithm for adding constraints seemed to have sufficed for now. attached a pr.
> 
> please feel free to test other large projects on it and tell me what you see. I apologise for the long wait.

All tests running and passing on cubit, amazing!
