### ISSUE TITLE
feat: return with no expression.

### ISSUE THREAD

**Issue by spapinistarkware** [starkware-libs/cairo#3034]
"return;" should be equivalent to "return ():".

Add syntax to cairo_spec.rs and parser.rs.
Fix what breaks.

**Comment by gaetbout** [comment]
I'll look into it

**Comment by spapinistarkware** [comment]
I think it's actualy easier to change both :)

**Comment by milancermak** [comment]
You're welcome @gaetbout 😁

**Comment by gaetbout** [comment]
Hey @spapinistarkware  I'm struggling a bit (just doing return atm):
I'm modifying:
```rust
    .add_struct(StructBuilder::new("StatementReturn")
        .node("return_kw", "TerminalReturn")
        .node("expr", "Expr")
        .node("semicolon", "TerminalSemicolon")
    )
```
to 
```rust
.add_struct(StructBuilder::new("StatementReturn")
    .node("return_kw", "TerminalReturn")
    **.node("optinal_expr", "OptionExpr")**
    .node("semicolon", "TerminalSemicolon")
)
```
then running the command 
`cargo run --bin generate-syntax`
To update the AST

Then I go to `parser.rs` to update:
```rust
SyntaxKind::TerminalReturn => {
    let return_kw = self.take::<TerminalReturn>();
    let expr = self.parse_expr();
    let semicolon = self.parse_token::<TerminalSemicolon>();
    Some(StatementReturn::new_green(self.db, return_kw, expr, semicolon).into())
}
```
To update it to something like:
```rust
SyntaxKind::TerminalReturn => {
    let return_kw = self.take::<TerminalReturn>();
   let optional_expr = if self.peek().kind == SyntaxKind::**???** { // Should it be StatementExpr
        self.parse_expr();
    } else {
        **???**
    };
    let semicolon = self.parse_token::<TerminalSemicolon>();
    Some(StatementReturn::new_green(self.db, return_kw, expr, semicolon).into())
}
```

I tried a bunch of stuff but can't figure out what to do 🙁 ...
Any help would be ... Helpful 😄

**Comment by gaetbout** [comment]
I'm at this:
https://github.com/starkware-libs/cairo/compare/main...gaetbout:cairo:feat/returnEmpty
Could you let me know if I'm on the right path?

**Comment by spapinistarkware** [comment]
Look at how let stmt parsing works, it should be similar.

When u introduce an optional expr node, u should get these nodes:
OptionExpr OptionExprSome and OptionExprNone.
The latter have .into() to the former.

So, in the parser, at each branch of then if u create one of these and
use.into()

**Comment by gaetbout** [comment]
That's the thing I don't have any of those two being generated.
I must be missing something

**Comment by gaetbout** [comment]
Status update:
I have the syntax working and compiling but I'm encountering a bug in this specific case:
```rust
fn some_fn(){
   let mut a = 12;
   loop {
      if a == 14 {
         break;
      }
      a =  a + 1;
   }

error: Variable not dropped. Trait has no implementation in context: core::traits::Drop::<core::never>. Trait has no implementation in context: core::traits::Destruct::<core::never>.
 --> bool_test.cairo:25:5
    loop {
    ^****^
```
Looking into it.

**Comment by yuvalsw** [comment]
This is a lowering error. Assuming you didn't change anything in the lowering phase, this is unrelated.
If you break with a value, does it work?

**Comment by gaetbout** [comment]
if I break with (); it does work. 
Trying to look into the lowering differences
