### ISSUE TITLE
feat: Default trait

### ISSUE THREAD

**Issue by spapinistarkware** [starkware-libs/cairo#3046]
Add the Default trait, similar to rust

**Comment by wraitii** [comment]
Should this include a breaking-change for Array and Dict?

**Comment by spapinistarkware** [comment]
Yes

**Comment by spapinistarkware** [comment]
Do you mean Felt252DictValue? If so, then it's something else.

**Comment by wraitii** [comment]
No I mean `trait Default<T>` in `traits.cairo`. I have 0 idea what it's used for though.

**Comment by spapinistarkware** [comment]
You are right. We should probably Implement it for Dict and Array:)
