### ISSUE TITLE
feat: u256 support dictionary type ( as value )

### ISSUE THREAD

**Issue by rkdud007** [starkware-libs/cairo#3064]
# Feature Request

**Describe the Feature Request**

Add dictionary implementation for u256 value type.  

**Describe Preferred Solution**

Add another trait bounds for Felt252Dict<T> where T implements Serde.
https://github.com/starkware-libs/cairo/blob/49aae266b3dd11f6e1b7ec899d8473fce089b1e1/corelib/src/dict.cairo#L40
`impl Felt252DictImpl<T, impl TDefault: Felt252DictValue<T>, impl TSerde: Serde<T>> of Felt252DictTrait<T> {}
`
Serde serializes your T in an Array<felt> and then you just loop to insert the values v_i it in the dict.

**Describe Alternatives**

**Related Code**

there is example from kakarot-ssj that implement u256 in dictionary
https://github.com/sayajin-labs/kakarot-ssj/blob/4afa1e90629811ed8ab58b5c20d46a7f26b25341/src/stack.cairo#L117

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by orizi** [comment]
Sorry for the late reply.

This shouldn't work.
Only types that are contained in a single cell can be the values for such a dictionary.
Consider making a `Nullable<u256>` as the value of the dictionary.
In the future, we hope to have a generic dictionary hiding both the keys and the values. to work for all (keys by some hashing, values behind a nullable)
