### ISSUE TITLE
bug: broken cairo-test since 2f690790

### ISSUE THREAD

**Issue by milancermak** [starkware-libs/cairo#3117]
# Bug Report

**Cairo version:** 2f690790

I have a test suite for a project I'm working on. When running `cairo-test --starknet .` I get the following error:

```sh
Error: Failed setting up runner.

Caused by:
    Failed calculating gas usage, it is likely a call for `gas::withdraw_gas` is missing.
```

The same command was working yesterday. I've triaged the error to the commit 2f690790. When using a build from the commit before (399eecde), everything works.

I haven't been able to isolate the issue to a simple test case that would aid reproducing the error.

**Comment by milancermak** [comment]
So I've fixed the error in our test suite by splitting a single test fn into two smaller ones. It wasn't really complex, just 20 asserts testing PartialOrd nad PartialEq on a custom type we have. Weird. Keeping the issue open in case you want to investigate, but feel free to close.

**Comment by milancermak** [comment]
Uh, that's strange, since you ran into it before the commit I mention above was even made, so that probably doesn't have anything to do with it? 😳

**Comment by enitrat** [comment]
Now it's even more broken, it won't run at all. Before, it used to run sometimes

**Comment by orizi** [comment]
i think it should work now (after the fix of https://github.com/starkware-libs/cairo/issues/3031) - can you please check?

thanks!

**Comment by milancermak** [comment]
Yes, fixed. Thanks!
