### ISSUE TITLE
bug: language server crashes on pattern matching statements for non felt types

### ISSUE THREAD

**Issue by drcapybara** [starkware-libs/cairo#3118]
# Bug Report

**Cairo version:**

scarb 0.2.0-alpha.1 (25f716afe 2023-05-02)
cairo: 1.0.0-rc0 (https://crates.io/crates/cairo-lang-compiler/1.0.0-rc0)

**Current behavior:**

When creating a simple pattern matching statement using only 0 and _ cases, the scarb language server crashes

**Expected behavior:**

The scarb language server should not crash when making a pattern matching statement.

**Steps to reproduce:**

create a pattern matching statement in any file in any module, for example, the factorial function:

`fn factorial(n: u32) -> u32 {
    match n {
        0 => 1,
        _ => n * factorial(n - 1),
    }
}`

The "Problems" tab in vscode will automatically open and show the language server crashing.

**Comment by drcapybara** [comment]
editing to clarify that it seems to be only affecting non felt types for this issue. perhaps it is that non felts are not supported yet for pattern matching?

**Comment by orizi** [comment]
it is exactly it - adding a diagnostic for it.
