### ISSUE TITLE
dev: Div, DivEq, felt252_try_as_non_zero for felt252

### ISSUE THREAD

**Issue by taco-paco** [starkware-libs/cairo#3157]
`Div`, `DivEq` traits and `felt252_try_as_non_zero` helper function aren't implemented for `felt252` in `lib.cairo`

**Comment by orizi** [comment]
Div isn't implemented for felt252 on purpose - to prevent users from performing division without fully understand the meaning of felt division.
Will add a Felt252TryIntoNonZero impl for the other part.

**Comment by taco-paco** [comment]
Got it. `Felt252TryIntoNonZero` was also done in attached to issue pr can just remove the other part

**Comment by taco-paco** [comment]
> Div isn't implemented for felt252 on purpose - to prevent users from performing division without fully understand the meaning of felt division.

So in cairo 1 multiplication/division of felts are still calculated via modular arithmetic but other integers use regular n-bit division?

**Comment by orizi** [comment]
exactly.
