### ISSUE TITLE
type inferrence regression between 1.0.0 and 1.1.0-alpha0

### ISSUE THREAD

**Issue by milancermak** [starkware-libs/cairo#3177]
# Bug Report

**Cairo version:** 1.1.0-alpha0

**Current behavior:**

I was running the [quaireaux](https://github.com/keep-starknet-strange/quaireaux) test suite (`make test`). When using Cairo version 1.0.0, it passed successfully. After switching to 1.1.0-alpha0, I encountered the following error:

```sh
~/projects/cairo/target/release/cairo-test .
error: Type annotations needed. Failed to infer ?5
 --> merkle_tree.cairo:59:46
                    if current_node.into() < (*proof_element).into() {
                                             ^*********************^

Error: failed to compile: .
```

It's stemming [from here](https://github.com/keep-starknet-strange/quaireaux/blob/main/quaireaux/data_structures/src/merkle_tree.cairo#L59). Seems the compiler can no longer infer it should compare u256 that were into()-ed from felt252?

**Expected behavior:**

I was expecting this test suite to run successfully using v1.1.0-alpha0 as it did before with v1.0.0. 

**Steps to reproduce:**

1) make sure you're running cairo 1.0.0
2) clone the quaireaux repo
3) run `make test` in the project
4) switch to cairo 1.1.0-alpha0
5) run `make test` again, observe failure

**Comment by orizi** [comment]
this is caused by expansion of the corelib - this shouldn't work.
`if current_node.into() < (*proof_element).into()`
previously ("by chance") there was only a single relevant `into` function mapping to the same type - now there are more - so you need to help the compiler to know what is the actual type.

**Comment by milancermak** [comment]
Got it, thanks.
