### ISSUE TITLE
feat: crate keyword

### ISSUE THREAD

**Issue by taco-paco** [starkware-libs/cairo#3178]
# Feature Request

**Describe the Feature Request**

Have `crate` keyword as in Rust.

**Describe Preferred Solution**

using `crate` instead of possibly long crate names + its more explicit that imports are from current package.

**Describe Alternatives**

**Related Code**

`crates/cairo-lang-semantic/src/resolve/mod.rs`

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [X] Yes
- [ ] No

**Comment by Jinwei1987** [comment]
does help is needed for this issue?

**Comment by enitrat** [comment]
@orizi bumping this

**Comment by orizi** [comment]
checking if this can happen without particular breaking changes.
