### ISSUE TITLE
bug: `calldata` parameter clash in abi

### ISSUE THREAD

**Issue by andrew-fleming** [starkware-libs/cairo#3192]
# Bug Report

**Cairo version:** 1cf52c077a37e3d727fe300991e71198e8ceb34c

**Current behavior:** 

This bug occurs in ABIs when defining a method with the parameter name `calldata` e.g. 

```
#[abi]
trait IContract {
    fn foo(calldata: felt252);
}
```

This is the returned error:

```
error: Unexpected argument type. Expected: "@core::felt252", found: "@core::array::Array::<?0>".
 --> IContractDispatcherTrait:13:44
        serde::Serde::<felt252>::serialize(@calldata, ref calldata);
                                           ^*******^

error: Unexpected argument type. Expected: "@core::felt252", found: "@core::array::Array::<?0>".
 --> IContractDispatcherTrait:35:44
        serde::Serde::<felt252>::serialize(@calldata, ref calldata);
                                           ^*******^
```

**Expected behavior:**

The expected behavior would be for the ABI method's `calldata` parameter not to clash with the `calldata` variable in [dispatcher.rs](https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L76).

**Steps to reproduce:**

1. `starknet-compile` the following code:
```
// contract.cairo

#[abi]
trait IContract {
    fn foo(calldata:felt252);
}

#[contract]
mod Contract {
    #[external]
    fn bar(){}
}
```

2. After receiving the error, change `calldata` to `_calldata` (or anything else) in IContract's `foo`.

**Other information:**

It appears to be an easy fix with simply changing the `calldata` variables in dispatcher.rs to a name that's unlikely to clash. I propose using `ABI_CALLDATA` or something along those lines.

**Comment by taco-paco** [comment]
> It appears to be an easy fix with simply changing the calldata variables in dispatcher.rs to a name that's unlikely to clash. I propose using ABI_CALLDATA or something along those lines.

Maybe we can introduce compiler-reserved forms of [namings like in C++](https://en.cppreference.com/w/cpp/language/identifiers)("in declarations" section) like double-underscore names and so on? Because as you noticed some people can still choose `ABI_CALLDATA` naming. 
So we can reserve names with `__` and use smth like `__calldata`

**Comment by andrew-fleming** [comment]
> Maybe we can introduce compiler-reserved forms of [namings like in C++](https://en.cppreference.com/w/cpp/language/identifiers)("in declarations" section) like double-underscore names and so on? Because as you noticed some people can still choose ABI_CALLDATA naming.
So we can reserve names with __ and use smth like __calldata

Great idea! I think that's a much better solution

**Comment by taco-paco** [comment]
@spapinistarkware @orizi what do you think?

**Comment by enitrat** [comment]
> So we can reserve names with __ and use smth like __calldata

Good idea, and that's already how it's done in other parts of the starknet plugin (e.g. events)

**Comment by orizi** [comment]
looks good - reviewed the changes - some minor comments.
