### ISSUE TITLE
feat: import everything from the module. "::*" Support

### ISSUE THREAD

**Issue by taco-paco** [starkware-libs/cairo#3194]
# Feature Request

**Describe the Feature Request**

Enable importing everything from module using "::*".

**Describe Preferred Solution**

In the module were such import is used I get access to all items inside imported module.

**Describe Alternatives**

**Related Code**

`use some::module::*;`

**Additional Context**

My assumption would be changes in `us.rs::priv_use_semantic_data` to return array of `resolved_item` and consequently `resolve_generic_path` shall also return an array. In resolver on `*` segment we get all importable items from the module using `db.module_items`(? maybe some filtration needed). Add `ast::UsePath::Glob` and so on

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by spapinistarkware** [comment]
We decided we don't want this for now. It makes it harder for the reader to understand what actually is used in a module.
We have use grouping with `use x::{a,b,c}`, and hopefully we will have good language server support for auto import.

**Comment by mkaput** [comment]
Hmm, if there will be good language server support, then perhaps grouping (or _nesting_ as that's the word used frequently also) is also unnecessary? See how well Java works without it.

Though Java has wildcards which are helpful if you have like hundreds of Enum cases to import in a lexer or something.
