### ISSUE TITLE
feat: Add function similar to Rust's `format!` with felt252

### ISSUE THREAD

**Issue by ColinWttt** [starkware-libs/cairo#3199]
# Feature Request

**Describe the Feature Request**

Add function similar to Rust's `format!` with felt252

Rust
```format!("Hello, {}!", "world");   // => "Hello, world!"```
Cairo
```format('Hello, {}!', 'world');   // => "Hello, world!"```

**Describe Preferred Solution**
No

**Describe Alternatives**
No

**Related Code**
 Creat LP token with the name of tokens.
```
let token_0 = 'ETH';
let token_1 = 'USDC';
let name = format('{} / {} LP',token_0,token_1 );   // => "ETH / USDC LP"
```

**Additional Context**

Target:
 1. Custom short string to write in storage 
 2. Custom Debug info to output.

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [x] No

**Comment by orizi** [comment]
format! macro released in the latest 2.4.0 release.
