### ISSUE TITLE
consts

### ISSUE THREAD

**Issue by ArielElp** [starkware-libs/cairo#3213]
Introduce the notion of consts that are written to the program's bytecode. In the special case of arrays, this is analogous to cairo0's `dw`.

Introducing consts entails:
- Adding the notion of `Constable` type to the Sierra-->CASM compiler
- For each such type, define how it is serialized in the program
- Add the ability to read/write the constants to/from a dedicated segment of the program
- Add high-level syntax for consts

**Comment by orizi** [comment]
```
struct A {
    a: u128,
    b: u256,
}

const CONSTANT1: Option<A> = Option::Some(A { a: 123, b: 456 });
const CONSTANT2: A = A { a: 789, b: 101112 };
const CONSTANT_SPAN: [Option<A>; 3] = [Option::None, CONSTANT1, Option::Some(CONSTANT2)];
```
Usages as:
`BoxTrait::new(CONSTANT1)` and `CONSTANT_SPAN.span()` would result in proper `dw`s.
