### ISSUE TITLE
Strings (phase I)

### ISSUE THREAD

**Issue by ArielElp** [starkware-libs/cairo#3218]
In the first phase, we will add byte arrays to the language.

Users will be able to initialize byte arrays via a syntax similar to `let err = b"this is a long error string"`.

Byte arrays answer many of the standard blockchain use of strings, such as storing constant URLs in a contract. Additionally, asserts will now be able to pass byte arrays that encode an ASCII string rather than a short string (31 bytes) which is usually not enough to describe the error.

We will introduce a String type supporting standard string operations in the second phase. Under the hood, it will be implemented with byte arrays.

**Comment by orizi** [comment]
Supported.
