### ISSUE TITLE
feat: implement Serde for dispatchers

### ISSUE THREAD

**Issue by ftupas** [starkware-libs/cairo#3240]
# Feature Request

**Describe the Feature Request**

It would be great if the Cairo compiler could implement the `Serde` trait for contract and library dispatchers to be able to pass it as calldata when doing contract or library call syscalls. This is to make inner calls more convenient, for example:

So for Contract A and B, Instead of this
```Rust

const EXECUTE_ENTRYPOINT: felt252 = 0x0240060cdb34fcc260f41eac7474ee1d7c80b7e3607daff9ac67c7ea2ebb1c44; // hash("execute")

#[external]
fn execute(class_hash: starknet::ClassHash, world: starknet::ContractAddress, calldata: Span<felt252>) -> Span<felt252> {
    let mut calldata_arr = calldata.snapshot.clone();
    calldata_arr.append(world_address.into());

    let res = starknet::syscalls::library_call_syscall(
        class_hash, EXECUTE_ENTRYPOINT, calldata_arr.span()
    ).unwrap_syscall();
    res
}
```

```Rust
#[external]
fn execute(world_address: starknet::ContractAddress) {
    world = IWorldDispatcher { contract_address: world_address }; // Instantiate IWorldDispatcher
    world.foo("bar"); // Call foo
}
```

It could be good to do this
```Rust
#[external]
fn execute(class_hash: starknet::ClassHash, world: IWorldDispatcher, calldata: Span<felt252>) -> Span<felt252> {
  let mut calldata_arr = calldata.snapshot.clone();
  world.serialize(ref calldata_arr);

  let res = starknet::syscalls::library_call_syscall(
      class_hash, EXECUTE_ENTRYPOINT, calldata_arr.span()
  ).unwrap_syscall();
  res
}
```

```Rust
#[external]
fn execute(world: IWorldDispatcher) {
    world.foo("bar"); // Call foo directly
}
```

**Describe Preferred Solution**

In this [file](https://github.com/starkware-libs/cairo/blob/9203b803f13061506068d472aa67e190eb5cf67e/crates/cairo-lang-starknet/src/plugin/dispatcher.rs), derive Serde for contract and library dispatchers like so

```Rust
#[derive(Copy, Copy, Serde)]
struct {contract_caller_name}
    contract_address: starknet::ContractAddress,
}}

#[derive(Copy, Drop, Serde)]
struct {library_caller_name} {{
    class_hash: starknet::ClassHash,
}}
```
**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [X] Yes
- [ ] No

**Comment by orizi** [comment]
I'm not sure serde-ing and storage-accessing is a pattern we'd like to support for dispatchers, as it seems sort of weird to me.
@spapinistarkware - I'd like to hear more ideas on the matter.

**Comment by spapinistarkware** [comment]
I want to support it. In solidity we have something like IERC20 instances stored in storage, which is a typesafe way to call a contract, and represent a dynamic dispatch for an ERC20 contract.
Dispatcher is the same.

Another point that demonstrates why it makes sense: in the future it might contain impl offset.

**Comment by ftupas** [comment]
> I want to support it. In solidity we have something like IERC20 instances stored in storage, which is a typesafe way to call a contract, and represent a dynamic dispatch for an ERC20 contract. Dispatcher is the same.
> 
> Another point that demonstrates why it makes sense: in the future it might contain impl offset.

Yeah having this typesafety in calling other contracts improve dev ergonomics and security imo. Could you please expound more on the impl offset? (I haven't had this in mind and would like to know more 🙂)
