### ISSUE TITLE
feat: we need to see actual error instead of ('ENTRYPOINT_FAILED'), while working with dispatchers

### ISSUE THREAD

**Issue by yusufferdogan** [starkware-libs/cairo#3242]
# Feature Request

while I am working with dispatchers, in the tests, I want to see the actual error, for example, I called a update_value method in the tests and if an error occurs in this update_value method I should see the actual error like `value must be bigger than 5 ` etc

I should see the actual error that occurred in the method 

I should see the actual error that occurred in the method 

see the actually error instead of  
`- panicked with [23583600924385842957889778338389964899652 ('ENTRYPOINT_FAILED'), ].
`

`

    #[external]
    fn sendToken(to: ContractAddress, value: u256) {
        let approve_amount = _erc20_dispatcher().allowance(
            get_caller_address(), get_contract_address()
        );
        _erc20_dispatcher().transfer_from(get_caller_address(), to, value);
   }
   
   #[test]
#[available_gas(2000000)]
fn test_send_token() {
     //deploy with deploy_syscall
    let (token_address, foo_address) = setup();
    let token = IERC20Dispatcher { contract_address: token_address };
    let foo = IFooDispatcher { contract_address: foo_address };

    let user1 = contract_address_const::<0x123456789>();

    let to: ContractAddress = contract_address_const::<0>();
    let amount: u256 = 50.into();

    set_contract_address(user1); // `caller_address` in contract will return
    token.approve(foo_address, amount);
    foo.sendToken(to, amount);

}
`
gives me `test_send_token - panicked with [23583600924385842957889778338389964899652 ('ENTRYPOINT_FAILED'), ].`
**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [x] No

**Comment by orizi** [comment]
which version are you using?
this should be already solved at `main`.
if it is - can you please give a more complete example? (this seems kinda broken on which code is included and which is excluded)

**Comment by williamweb3** [comment]
My code is "let caller: ContractAddress = get_caller_address();
        let thisaddress: ContractAddress = get_contract_address();
        IERC20Dispatcher { contract_address: ierc20_address }.transfer_from(caller, thisaddress, amount);"
 also got same error like this "
Error in the called contract (0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7):
Entry point 0x3704ffe8fba161be0e994951751a5033b1462b918ff785c0a636be718dfdb68 not found in contract with class hash 0x2760f25d5a4fb2bdde5f561fd0b44a3dee78c28903577d37d669939d97036a0."

**Comment by orizi** [comment]
Should be fixed on 2.5.* - feel free to reopen if it isn't.
