### ISSUE TITLE
dev(vscode-cairo): dont automatically use scarb's language server if scarb path is not configured

### ISSUE THREAD

**Issue by lambda-0x** [starkware-libs/cairo#3246]
context: https://github.com/shramee/starklings-cairo1/pull/127

i was seeing extension panic because of not having `Scarb.toml` in the root, turned out extension automatically detect if scarb is installed and uses its language server which is not always expected. 

say someone is working on a project that doesn't use scarb but they have it installed for other projects

**Comment by mkaput** [comment]
That's already being worked on in #3235
