### ISSUE TITLE
dev: Lack of Changelog in v1.1.0 release

### ISSUE THREAD

**Issue by franalgaba** [starkware-libs/cairo#3284]
Hi,

Recently the version `v1.1.0` has been released. With this new version we have seen many changes in terms of compilation of the Cairo programs but there are no details provided in the Changelog of the release of the updates in the code.

Could you provide a detailed Changelog for the latest version releases so we can adapt these changes into our codebases?

Thank you for all the work and support 🙏

**Comment by orizi** [comment]
Updating with the full release notes.

Thanks!
