### ISSUE TITLE
feat: support test macro for contract functions  

### ISSUE THREAD

**Issue by tserg** [starkware-libs/cairo#3286]
# Feature Request

**Describe the Feature Request**

It is useful at times to have contract functions that are only exposed for testing, and are not compiled outside of tests.

**Describe Preferred Solution**

Extend the test macro to functions

```
#[contract]
mod Foo {

    #[external]
    fn foo() -> u128 {
        ...
    }

    #[external]
    #[cfg(test)]
    fn bar() -> u128 {
        ...
    }
}
```

**Describe Alternatives**

We could dynamically inject the additional code into the contract with some scripts before running a test command, but it would be nice to have it work natively with Cairo test runner.

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by orizi** [comment]
this should already work - although i won't recommend using it - as the order of the run of plugins is not ensured.
(the config plugin would run before the starknet plugin as far as i know, but trusting the ordering seems like bad practice)
