### ISSUE TITLE
help needed: How to get a proper value of keccak256 for one u8?

### ISSUE THREAD

**Issue by Lukasz2891** [starkware-libs/cairo#3290]
let have:

```rust
let number = 0x23;
```

The proper value of keccak256 for that value is `0xace738c68088218d015fbdce138f062893d86818ac98932f7ce2907c5976fbde` (see: https://toolkit.abdk.consulting/ethereum#recover-address)

I was trying to achieve the value in different ways:

```rust
   let mut keccak_input: Array::<u64> = Default::default();

    keccak_input.append(???); 
    add_padding(ref keccak_input);

    let result = starknet::syscalls::keccak_syscall(keccak_input.span()).unwrap_syscall();

    result.print();
```

Also was trying to achieve it by using ```keccak_u256s_le_inputs``` and ```keccak_u256s_be_inputs``` for numbers `u256 { low: 23, high: 0 }` and also reversed `u256 { high: 0x230000000000000000000000000000, low: 0 }`, also for u64-length numbers `u256 { high: 0x23000000000000, low: 0 }` and `u256 { high: 0, low: 0x23000000000000 }` but no way resutls the proper value.

Could you help me in that?

**Comment by Lukasz2891** [comment]
Bump!

**Comment by ilyalesokhin-starkware** [comment]
You should be able to do something like:
let mut input = array![];
let res = keccak::cairo_keccak(ref input, number, 1);

**Comment by orizi** [comment]
@Lukasz2891 is it working for you? I so - please close the issue.

**Comment by Lukasz2891** [comment]
Related to #3508
