### ISSUE TITLE
vsce package  - Cannot find name 'Window'.

### ISSUE THREAD

**Issue by rvorias** [starkware-libs/cairo#3295]
Adding "dom" to this list solved my packaging.

https://github.com/starkware-libs/cairo/blob/77ae28f996c0960ce5cfc926703f60bae8d5db5a/vscode-cairo/tsconfig.json#L6

**Comment by mkaput** [comment]
Hey! I've checked the source code and I cannot see any references to the global `window` symbol. Closing. Please reopen if that's still a problem for you.
