### ISSUE TITLE
bug: Inconsistent references annotations

### ISSUE THREAD

**Issue by milancermak** [starkware-libs/cairo#3299]
# Bug Report

**Cairo version:** 77ae28f9

**Current behavior:**

Running `cairo-test --starknet .` in my project results in an error:

```
Error: Failed setting up runner.

Caused by:
    #18908: Inconsistent references annotations.
```

The problem is I have not been able to create a minimal reproducible example so far. I've only been able to isolate the error - if I remove a `loop` from one particular function, the code compiles fine. In this sense, it's eerily similar to #3031. I'm already using the new contract syntax, so the function is inside a `IFoo<Storage>` impl and in the loop, it's calling a function that's inside `StorageTrait`, if that helps in any way 😅 

**Expected behavior:**

Code compiles.

**Steps to reproduce:**

**Related code:**

Will try to come up with an isolated scenario... 🤞

**Comment by moodysalem** [comment]
related to https://github.com/starkware-libs/cairo/issues/3345

**Comment by orizi** [comment]
https://github.com/starkware-libs/cairo/issues/3345 will be solved today (PR is opened).
Please update here if it solved your issue as well.

**Comment by orizi** [comment]
If you can work from main - please check if this works now.
Otherwise - please use the newest release (will be released soon) and update here.

**Comment by milancermak** [comment]
Can't verify if the issue is solved because I don't have the code where we encountered this error anymore (we stopped migrating to the new syntax for the time being). Optimistically closing.
