### ISSUE TITLE
bug: test runner complains about `[starknet::Storage]` namespace

### ISSUE THREAD

**Issue by glihm** [starkware-libs/cairo#3301]
# Bug Report

**Cairo version:**

Current HEAD of the repo: 77ae28f996c0960ce5cfc926703f60bae8d5db5a

**Current behavior:**

When building with `cargo build --workspace --release`, and then executing
the test running `cairo-test --starknet ~/path`, I have this error:

```
Plugin diagnostic: 'Storage' struct must be annotated with #[starknet::storage]..
```

**Expected behavior:**

`#[storage]` must be enough.

**Steps to reproduce:**

`git clone https://github.com/starkware-libs/cairo`
`cargo build --workspace --release`
`./target/release/cairo-test --starknet ~/path/to/test.cairo`

**Related code:**

I am new to this I'll try to identify the code related to that. From what I understand that
the plugin of starknet is well detected but it's complaining like if a `use` or something similar
was missing.

**Other information:**

This problem is not present when compiling at the tag `v1.1.0` and doing the same steps.

**Comment by rkdud007** [comment]
seems like recently ( 5 days ago ish) compiler has changed a bit. Now need to use #[starknet::Storage] instead of #[storage]. I want to know about the reason why change contract compiler quite lot.

**Comment by glihm** [comment]
Thanks @rkdud007 and yes after checkings it's due to rework. Thanks for commenting, I'll close. :)
