### ISSUE TITLE
feat: add starknet testing methods for measuring performance and snapshotting

### ISSUE THREAD

**Issue by moodysalem** [starkware-libs/cairo#3365]
# Feature Request

I want to measure the performance of my code. Right now the only way I have available is to reduce available gas for a test until it fails. I would prefer to be able to add a gas test and snapshot the results to a file.

**Describe Preferred Solution**

The gas method should just tell me how much available gas is left

The snapshot method could be a debug method and the test runner would output to a colocated file (eg math_test.cairo.snap in the same directory as math_test.cairo). Important to output to file instead of just print because it should be committed to repo so it's easy to see how a pr changes the performance of the code

**Describe Alternatives**

None really

**Comment by orizi** [comment]
`testing::get_available_gas` exists and is available for tests only.

**Comment by moodysalem** [comment]
The other part of this request is snapshots, is that available somewhere?

**Comment by moodysalem** [comment]
This also seems like it might be broken. This prints `0` on main. I tried also printing `y` and adding `#[available_gas(300000)]` and got the same result

```
use testing::get_available_gas;

#[test]
fn test_exp2_gas() {
    let gas = get_available_gas();
    exp2(12);
    let gas_after = get_available_gas();
    (gas - gas_after).print();
}
```

**Comment by orizi** [comment]
We do not plan on adding file access capabilities to the compiler generally, but maybe one of the external testing frameworks are planning on some sort of builtin benchmarking support.
Or we can just add a `#[bench]` function that would make the test output some additional data.

Do note generally - that compiler improvements may change vastly the amount of taken gas in some instances.

**Comment by orizi** [comment]
The runner itself already tracks:
* The constant cost of the called test.
* The amount of gas actually consumed by the test.
So it is generally sensible for a testing framework to expose something.

The main difference is that 'debug' is generally useful for some local experimentation - adding more sort of hooks will start overloading a lot of things, and we needed it for our debugs.
Generally - when some runner framework has a communication protocol between some extension of actually running the code and a Cairo level library, it would be able to add whatever they actually want.
