### ISSUE TITLE
feat: report a compile error when using wrong attribute

### ISSUE THREAD

**Issue by milancermak** [starkware-libs/cairo#3401]
# Feature Request

**Describe the Feature Request**

The compiler should report an error when compiling code witch uses an unknown attribute.

As an example, this compiles just fine:

```rust
#[inilne(always)]
fn foo() -> u8 {
    1
}
```

But there's a typo in the attribute - it's `inilne` not `inline`. Easy to do, easy to miss during review and the resulting code isn't what the author intended.

**Describe Preferred Solution**

Compiling should fail with a clear error message pointing to the typo in the attribute.

**Comment by orizi** [comment]
On main now - `always(inline)` will fail.
