### ISSUE TITLE
bug: Sierra function declarations generated for loops are lacking namespacing

### ISSUE THREAD

**Issue by javra** [starkware-libs/cairo#3425]
# Bug Report

**Cairo version:**

1.1.0

**Current behavior:**

Compiling with `cairo-compile -r` gives declared functions proper namespacing but the namespaces lack for auxiliary Sierra functions generated for loops.

**Expected behavior:**

Generate better names for the auxiliary Sierra functions which  cannot clash with functions in other modules of the same name.

**Steps to reproduce:**

Take for example a snippet `feltloop.cairo`:
```cairo
fn foo() -> felt252 {
    let mut x : felt252 = 0;
    loop {
        if (x == 12) {
            break();
        };
        x += 3;
    };
    return x;
}
```

`cairo-compile -r feltloop.cairo` produces a Sierra file containing the following declarations:
```
feltloop::feltloop::foo@0([0]: RangeCheck, [1]: GasBuiltin) -> (RangeCheck, GasBuiltin, core::PanicResult::<(core::felt252,)>);
foo[expr10]@22([0]: RangeCheck, [1]: GasBuiltin, [2]: felt252) -> (RangeCheck, GasBuiltin, core::PanicResult::<(core::felt252, ())>);
```
The second function should be called `feltloop::feltloop::foo[expr10]` instead.

**Comment by orizi** [comment]
Was fixed a while back - sorry for the late update.
