### ISSUE TITLE
`set_contract_address` won't persist through `call_contract_syscall` calls in tests 

### ISSUE THREAD

**Issue by martriay** [starkware-libs/cairo#3432]
# Bug Report

**Cairo version:**
1.0.0-rc0

**Current behavior:**

Faking current contract address with `set_contract_address` is picked up by `call_contract_syscall` once and then is dropped in subsequent `call_contract_syscall` executions.

**Expected behavior:**

Contract address should persist across an arbitrary number of `call_contract_syscall` calls.

**Related code:**

While testing the [`try_selector_with_fallback` method we’re implementing for the dual interface dispatcher module](https://github.com/OpenZeppelin/cairo-contracts/blob/d5a98e55c2b4480970307374b89fb83a329d756a/src/openzeppelin/utils.cairo#L11-L24) we need to fake the caller address with `set_contract_address` so the target contract picks it up with `get_caller_address`:

```cairo
set_contract_address(OWNER);  // <- to fool call_contract_syscall
try_selector_with_fallback(...);
```

In `A` the contract address is properly set as `OWNER` as expected, but in `B` is any other value (`1` in my case):

```cairo
fn try_selector_with_fallback(
    target: ContractAddress, snake_selector: felt252, camel_selector: felt252, args: Span<felt252>
) -> SyscallResult<Span<felt252>> {
    // A  < ------------------------------ IT'S OWNER HERE
    match call_contract_syscall(target, snake_selector, args) {
        Result::Ok(r) => Result::Ok(r),
        Result::Err(r) => {
            // B < ------------------------------ IT'S 1 HERE
            if *r.at(0) == 'ENTRYPOINT_NOT_FOUND' {
                return call_contract_syscall(target, camel_selector, args);
            } else {
                Result::Err(r)
            }
        }
    }
}
```

**Steps to reproduce:**

Run this test, uncommenting one of the `panic()` calls one at the time to inspect the value of `get_contract_address` at different points of the execution.

```cairo
use starknet::class_hash::Felt252TryIntoClassHash;
use starknet::testing::set_contract_address;
use starknet::contract_address_const;
use starknet::call_contract_syscall;
use starknet::get_contract_address;
use core::result::ResultTrait;
use starknet::ContractAddress;
use starknet::SyscallResult;
use option::OptionTrait;
use array::ArrayTrait;
use array::SpanTrait;
use traits::TryInto;
use traits::Into;

//
// Test
//

#[test]
#[available_gas(2000000)]
fn test_foo() {
    let target = deploy(NonImplementingMock::TEST_CLASS_HASH, ArrayTrait::new());
    let selector = 0x88beda87451d1856f68d577c0b8da40f7cff6d24f3983f06086e56332c147f; // some random selector
    let caller = contract_address_const::<333333>();

    set_contract_address(caller);
    try_selector_with_fallback(target, selector, selector, ArrayTrait::new().span());
}

fn try_selector_with_fallback(
    target: ContractAddress, snake_selector: felt252, camel_selector: felt252, args: Span<felt252>
) -> SyscallResult<Span<felt252>> {
    match call_contract_syscall(target, snake_selector, args) {

        // get_contract_address().panic(); <--- panics with '333333'

        Result::Ok(r) => Result::Ok(r),
        Result::Err(r) => {

            // get_contract_address().panic(); <--- panics with '1'

            if *r.at(0) == 'ENTRYPOINT_NOT_FOUND' {
                return call_contract_syscall(target, camel_selector, args);
            } else {
                Result::Err(r)
            }
        }
    }
}


//
// Contract
//

#[contract]
mod NonImplementingMock {
    #[view]
    fn nope() -> bool {
        false
    }
}

//
// Utils
//

fn deploy(contract_class_hash: felt252, calldata: Array<felt252>) -> ContractAddress {
    let (address, _) = starknet::deploy_syscall(
        contract_class_hash.try_into().unwrap(), 0, calldata.span(), false
    )
        .unwrap();
    address
}

trait PanicTrait<T> {
    fn panic(self: T);
}

impl ContractAddressPanicImpl of PanicTrait<ContractAddress> {
    fn panic(self: ContractAddress) {
        panic_with_felt252(self.into());
    }
}

```

**Comment by spapinistarkware** [comment]
Not sure what you are running, but I'm getting
```
[DEBUG]                                 (raw: 333333)

[DEBUG]                                 (raw: 333333)
```

**Comment by martriay** [comment]
> Also, I saw you use an old compiler version (for example, without the new contract syntax).

Upgrading the compiler version would require us to migrate everything to the new syntax which would require big refactors in existing PRs. Today we can't use the new syntax due to the lack of support for storage components, which we need since we compose contract implementations for extensibility. That being said you're right, I'm using `1.0.0-rc0` (updated OP with this). Will try with `1.1.0` to see if it works.

> Also, note that you can use .print(), instead of .panic().

Tried it but they weren't getting printed for some reason, not sure why. They do now, in the code sample you shared with me (slightly modified to use contracts i had in context):

```
#[test]
#[available_gas(30000000)]
#[should_panic(expected: ('Failure', 'ENTRYPOINT_FAILED', ))]
fn test_entrypoint_failed() {
    starknet::get_execution_info_syscall().unwrap_syscall().unbox().contract_address.print();
    starknet::testing::set_contract_address(OWNER());
    starknet::get_execution_info_syscall().unwrap_syscall().unbox().contract_address.print();
    let mut calldata = ArrayTrait::new();

    let (snake_dispatcher, snake_target) = setup_snake();
    
    starknet::call_contract_syscall(snake_target.contract_address, 'name', calldata.span());
    starknet::get_execution_info_syscall().unwrap_syscall().unbox().contract_address.print();
    snake_target.name();
}
```

The output:
```
[DEBUG]                                 (raw: 0)

[DEBUG]                                (raw: 10)

[DEBUG]                                 (raw: 1)
```

**Comment by orizi** [comment]
It seems it works at latest - but for some reason fails at 1.1.0 - trying to debug what is going on there.

**Comment by orizi** [comment]
Well I see the offending code - in cases of revert by any reason (be it a missing selector or just a failure in the call) - the caller and contract address were not restored.

It was fixed a while ago - and is correct in `2.0.0` and in `main`.

**Comment by martriay** [comment]
we even have a diagram 😅, blue PRs are opened and most of it depends on this bug getting resolved

![image](https://github.com/starkware-libs/cairo/assets/1703831/eaa8e840-7cbd-445a-a3eb-eb5d3f0c5250)

**Comment by orizi** [comment]
v1.1.1 [artifacts are currently being created](https://github.com/starkware-libs/cairo/actions/runs/5398648770).
as well as uploads to crates.io.

**Comment by martriay** [comment]
thank you very much!
