### ISSUE TITLE
bug: Testing of package named keccak conflicts with corelib

### ISSUE THREAD

**Issue by maciektr** [starkware-libs/cairo#3434]
# Bug Report

**Cairo version:**
1.1.0

**Current behavior:**
Sharing an issue discovered by Scarb user (https://github.com/software-mansion/scarb/issues/417). 

**I wonder if this is something that could be fixed, or should we just validate module names to not overlap with corelib?**

Running test with `cairo-test` for a crate named `keccak` compiles test for corelib's keccak module, which fails with a compilation error (as crate `keccak` defined by the user does not have the same functionality as the corelib one. 

**Expected behavior:**

Tests from corelib would not run. 

**Steps to reproduce:**

1. Create cairo project with following files: 
```
// cairo_project.toml
[crate_roots]
keccak = "src"
```
```
// src/lib.cairo
#[test]
fn test_scarb_keccak() {}
```
2. Run tests with `cairo-test .` 

**Other information:**
- https://github.com/software-mansion/scarb/issues/417

**Comment by mkaput** [comment]
I think what should happen is that all corelib modules should be reachable by absolute `core::*` path, for example `core::keccak` instead of `keccak`...
