### ISSUE TITLE
bug: Expected variable data for statement not found.

### ISSUE THREAD

**Issue by azteca1998** [starkware-libs/cairo#3445]
# Bug Report

**Cairo version:**

v2.0.0-rc0

**Current behavior:**

Compiling a program generates invalid Sierra which cannot be executed.

The failure is:
```
Error: Failed setting up runner.

Caused by:
    #51: Expected variable data for statement not found.
```

**Expected behavior:**

Compiling a program generates a valid Sierra that can be executed successfully.

**Steps to reproduce:**

  1. Attempt to run the program below with `cairo-run program.cairo`.
  2. Watch it crash.

**Related code:**

```
fn factorial(mut n: felt252) -> felt252 {
    let mut value = n;
    loop {
        if n == 0 || n == 1 || n == 2 {
            break value;
        }

        n -= 1;
        value *= n;
    }
}

fn main() -> felt252 {
    factorial(1000)
}
```

**Other information:**

The generated sierra generates the following statement (n. 7)

    enum_match<core::PanicResult::<(core::felt252, core::felt252, core::felt252)>>([5]) { fallthrough([10]) 18([11]) };

which either falls through or jumps to statement 18.

Statements 18 to 24 are as follows:

```
return([17], [18], [19]);
branch_align() -> ();
enum_init<core::PanicResult::<(core::felt252,)>, 1>([11]) -> ([20]);
store_temp<RangeCheck>([3]) -> ([21]);
store_temp<GasBuiltin>([4]) -> ([22]);
store_temp<core::PanicResult::<(core::felt252,)>>([20]) -> ([23]);
return([21], [22], [23]);
```

By tracking the state variables from the start of the function we know that when entering the statement 7 the state contains the variables `{3, 4, 5}`, from which it takes `5` and jumps to either the next statement after pushing `10`, or statement 18 after pushing `11`.

Statement 18 expects a state with `{17, 18, 19}`, which doesn't match the output state of statement 7. Instead, statement 19 expects `{3, 4, 11}` which is the output of the second branch of statement 7. Because of that, I'm positive the second branch of statement 7 should point to statement 19 instead of 18.

**Comment by ilyalesokhin-starkware** [comment]
Fixed by #3437
