### ISSUE TITLE
feat: Choose between decimal or hex for debug prints in cairo-run

### ISSUE THREAD

**Issue by feltroidprime** [starkware-libs/cairo#3459]
Hello 

Would it be possible to choose between those two representation in a cairo-run argument like `cairo-run --debug-print {hex, dec}` ? 

Thank you for your attention.

**Comment by ilyalesokhin-starkware** [comment]
What are debug prints?

**Comment by feltroidprime** [comment]
Hello
I am referring to the ones you get when using 
`use debug::PrintTrait;`

for example `'Hello, world444!'.print();`
shows 

`[DEBUG] Hello, world444!                (raw: 96231036770510888505662878050726196257)`

**Comment by orizi** [comment]
What is the use-case?
In the future we plan to have a printer for strings specifically - which would make all of this obsolete (as for debug you'd format anything into a string, so you'd print whatever you'd want)
