### ISSUE TITLE
feat: Implement `PartialOrd` for `ContractAddress` Type

### ISSUE THREAD

**Issue by iddriss** [starkware-libs/cairo#3463]
# Feature Request

**Describe the Feature Request**
This is a request for the addition of the `PartialOrd` trait for the `ContractAddress` type. This feature is crucial in scenarios where we need to sort or compare `ContractAddress` instances. Specifically, it should support the `<=, >=, >, < ` operators. There's  a `PartialEq` trait  for `ContractAddress`, but that limits the comparison of `ContractAddress` to `==` & `!=`.

**Describe Preferred Solution**
I propose to add an implementation of `PartialOrd` for the `ContractAddress` type. Since `contract_address_to_felt252` doesn't have the `PartialOrd` the implementation would utilize a conversion of `ContractAddress` to `u256` (using the `contract_address_to_felt252` function and `into()` method) for the comparison operations.

**Describe Alternatives**

An alternative would be to provide separate utility functions for comparing ContractAddress instances. However, this approach is less idiomatic and less convenient than implementing PartialOrd.

**Related Code**

Example usecase:
```cairo
...
fn sort_tokens(
        tokenA: ContractAddress, tokenB: ContractAddress
    ) -> (ContractAddress, ContractAddress) {
        assert(tokenA != tokenB, 'identical addresses');
        let mut token0 = contract_address_const::<0>();
        let mut token1 = contract_address_const::<0>();

        if tokenA < tokenB {
            token0 = tokenA;
            token1 = tokenB;
        } else {
            token0 = tokenB;
            token1 = tokenA;
        }
        assert(token0.is_non_zero(), 'invalid token0');
        (token0, token1)
    }
```

Instead of:

```cairo
...
if u256_from_felt252(
    contract_address_to_felt252(tokenA)
) < u256_from_felt252(
    contract_address_to_felt252(tokenB)
) { 
    token0 = tokenA;
    token1 = tokenB;
} else {
    token0 = tokenB;
    token1 = tokenA;
}
```

**Additional Context**
During the development of the AMM contracts, we noticed the requirement for sorting `ContractAddress` instances. To efficiently and correctly perform such an operation, being able to compare `ContractAddress` instances directly would be highly beneficial. Implementing `PartialOrd` for `ContractAddress` will make the code more readable and idiomatic, and enable us to use standard intuition for sorting and comparing.

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes

**Comment by orizi** [comment]
do note that you can already do that generally, but inefficiently:
```
let a: u256 = a.into().into();
let b: u256 = b.into().into();
a < b
```

I'm not sure how much better are the other options for this implementation.
