### ISSUE TITLE
Keccak - solidity compatability

### ISSUE THREAD

**Issue by ArielElp** [starkware-libs/cairo#3477]
After adding the ability to compute keccak on `Array<u256>`, we want to enrich the corelib functionality such that one can reproduce the same hashes as with solidity's `abi.ecnode()`.

More specifically, users will be able to feed `Keccak` an `Array<u64>` and another argument specifying how many bytes to use from the last element.

**Comment by yuvalsw** [comment]
https://github.com/starkware-libs/cairo/pull/3508
