### ISSUE TITLE
Match improvements

### ISSUE THREAD

**Issue by ArielElp** [starkware-libs/cairo#3479]
Various improvement to `match` expressions:
- allow arbitrary ordering of the variants when matching an enum
- support match over tuples
- otherwise arm ( `_ => {...}`) for enums
- support match over ints/uints
- or patterns
- low-level optimizations for the assembly generated by match over a continuous range (these will only be included in the next Sierra upgrade)

Not included yet:
- Inner patterns, e.g. `A::One(B::Two(x)) => x`

**Comment by orizi** [comment]
All the included in the `Various improvement` were released on 2.5.0.
