### ISSUE TITLE
Secp-r1 curve operations

### ISSUE THREAD

**Issue by ArielElp** [starkware-libs/cairo#3483]
Secp-r1 support will enable Starknet to work with standard mobile phone's hardware for signing, greatly improving the UX of interacting with the chain.

Currently, Secp-r1 operations are supported in the test-runner, but aren't proved. This requires work in the Starknet OS to fully integrate (until this point, the secpr1-related libfuncs can't move to the experimental list of allowed_libfuncs).

**Comment by orizi** [comment]
Supported.
