### ISSUE TITLE
feat: abstract serialization away from testing contract methods

### ISSUE THREAD

**Issue by andrew-fleming** [starkware-libs/cairo#3555]
# Feature Request

**Describe the Feature Request**

When testing Starknet contracts in cairo v2, we currently have to serialize calldata before passing it to methods. It'd be great if this process was handled on the language-level instead of being the dev's responsibility. The two big reasons why this will benefit dx are:
1. It enforces types in the testing environment.
2. It makes tests easier to read/write.

**Describe Preferred Solution**

The preferred solution would enforce types on calldata when passing calldata to contract methods.

**Describe Alternatives**

An alternative (that I'm already using) is to define structs for calldata, serialize the struct instance, and pass the result to the contract method. This enforces types and is less messy to read/write; however, it's still preferred for dx that the serialization is abstracted away.

**Related Code**

This is the manual approach:

```
let mut calldata = ArrayTrait::new();
calldata.append(SPENDER_ADDR().into());
calldata.append(VALUE_U256().low.into());
calldata.append(VALUE_U256().high.into());
ERC20::__external::approve(calldata.span());
```

This is the mentioned alternative solution:

```
#[derive(Drop, Serde)]
struct ApproveArgs {
    spender: ContractAddress,
    value: u256,
}

test_foo() {
    let args = ApproveArgs {
        spender: SPENDER_ADDR(),
        value: VALUE_U256()
    };
    let calldata = serialized_element(args);
    ERC20::__external::approve(*@calldata);
}
```

And this is the preferred way (the actual feature request):

```
ERC20::__external::approve(SPENDER_ADDR(), VALUE_U256());
```

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by orizi** [comment]
which sort of tests are you specifically talking about?
1. If it is basic business logic tests - you can directly call the function.
2. if it is a contract or library call - you can use a dispatcher (which will abstract away all the serialization)
3. if it is a `constructor` call - this is indeed an issue with the current environment - which will hopefully be addressed further soon.

**Comment by andrew-fleming** [comment]
Sorry for not being clear, the tests in question are indeed business logic tests, but I was approaching them like this:

```
use contracts::MyContract;

#[test]
#[available_gas(2000000)]
fn test_foo() {
    MyContract::__external::foo();
}
```

Accessing the contract methods this way requires calldata to be serialized. There's better testing strategies we can use a la `contract_state_for_testing`, so I'll close this issue. Thanks for the response :)
