### ISSUE TITLE
feat: pub use

### ISSUE THREAD

**Issue by Jinwei1987** [starkware-libs/cairo#3595]
# Feature Request

**Describe the Feature Request**

Add pub visibility to use and hide all non-pub use

**Describe Preferred Solution**

Add visibility modifier for use in the cairo_spec.rs.
Change the logic of resolver to check the visibility of the use.

**Related Code**
mod inner {
   pub use inner::X;
   use inner::Y;   
 
   mod inner {
        pub struct X {...}
        pub struct Y{...}
    }
}

use inner::X; // this is valid
use inner::Y; // this is invalid

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [X] Yes
- [ ] No

**Comment by mkaput** [comment]
I would also like to highlight, that I think starknet compiler should also build re-exported contracts, am I correct?

**Comment by Jinwei1987** [comment]
Do you mean in the case of nested contract? In this case if nested contract being re-exported, probably should be treated as multiple contracts in the single file.

**Comment by mkaput** [comment]
> Do you mean in the case of nested contract? In this case if nested contract being re-exported, probably should be treated as multiple contracts in the single file.

Yes and yes. Although CLIs do not support this, it doesn't mean this is unsupported and this actually works very well elsewhere, for example in Scarb.

**Comment by Jinwei1987** [comment]
> > Do you mean in the case of nested contract? In this case if nested contract being re-exported, probably should be treated as multiple contracts in the single file.
> 
> Yes and yes. Although CLIs do not support this, it doesn't mean this is unsupported and this actually works very well elsewhere, for example in Scarb.

Then yes for sure, reexport contract shall be implemented with “pub use”.

**Comment by Jinwei1987** [comment]
https://github.com/starkware-libs/cairo/blob/cairo-major-update/crates/cairo-lang-starknet/src/contract_class.rs
@mkaput so you want to extend line 115 in contract_class.rs to accept multiple contracts in single crate?

**Comment by mkaput** [comment]
> https://github.com/starkware-libs/cairo/blob/cairo-major-update/crates/cairo-lang-starknet/src/contract_class.rs @mkaput so you want to extend line 115 in contract_class.rs to accept multiple contracts in single crate?

I don't know if that's wanted by Cairo team, @orizi would have to chime in here :) What I suggest is making sure the `find_contracts` function works handles this properly. That's the API endpoint that the ecosystem is using.

**Comment by orizi** [comment]
We don't have any issues with multiple contracts in a single crate - just *when creating the json for submitting to starknet* we cannot have more than on available contract - so we need to either:
1. Have only a single available contract
2. State specifically which contract would you like (using `--contract-path`.)

**Comment by Jinwei1987** [comment]
@mkaput I think find_contracts has handled nested contracts in the same crates. I don't think it is a good idea to make "pub use" to reexport contracts from other crates and generate sierra and casm files.

**Comment by mkaput** [comment]
> I don't think it is a good idea to make "pub use" to reexport contracts from other crates and generate sierra and casm files.

Could you please elaborate, why do you think so? My point of view is now purely to ensure that this feature is consistent, as we found a better solution of generation of artefacts to be implemented outside the compiler.

**Comment by Jinwei1987** [comment]
> > I don't think it is a good idea to make "pub use" to reexport contracts from other crates and generate sierra and casm files.
> 
> Could you please elaborate, why do you think so? My point of view is now purely to ensure that this feature is consistent, as we found a better solution of generation of artefacts to be implemented [outside the compiler](https://github.com/software-mansion/scarb/issues/460).

For reexport I mean `use` could be recursively resolved as items. I think `use` in rust works in the same way. For the following reasons I don't think to use `use` to compile contracts in other crates into artifacts is a good idea.
1) Actually the logic recursively resolving `use` as items has been implemented. Currently every `use` is pub use. Adding visibility to it is a good to hide unwanted reexports. If we are talking consistency, we probably should let it as it is right now.
2) Resolving as items is a recursive process. If we implement `use` to compile contract in other crates, it will compile every single contract in the dependencies in the `use` statements. This is every expensive and I don't think people want this at all. I think most of time we use `use` just to import some libraries, so that we don't implement same things multiple times and save some efforts.
3) The compiler right now actually accept a path which could potentially contains multiple crates, and it will search every module under the crates for contracts. So like Scarb it think it completely has the ability to compile all the contracts in a single workspace into artifacts. 

The I will re-word this issue to remove `reexport`, because reexport has been actually implemented.

**Comment by orizi** [comment]
newest edition on main now supports pub.
