### ISSUE TITLE
feat: Refactor Option::None(()) to Option::None for enum init.

### ISSUE THREAD

**Issue by neotheprogramist** [starkware-libs/cairo#3627]
While reviewing the codebase, I've noticed that there's an occurrence of `Option::None(())` in the code. While this technically works, it would be more idiomatic and consistent to use `Option::None` for enum init.

Here's an example of the current usage:
```cairo
match array_pop_front(ref self) {
    Option::Some(x) => Option::Some(x.unbox()),
    Option::None => Option::None(()),
}
```

I suggest changing it to:
```cairo
match array_pop_front(ref self) {
    Option::Some(x) => Option::Some(x.unbox()),
    Option::None => Option::None,
}
```

**Comment by orizi** [comment]
This requires new actual support in the language of unit variant construction with no arguments.
So it isn't just about using another feature, this is an actual enhancement for the language.
