### ISSUE TITLE
`AccountContract` is missing `#[starknet::interface]`

### ISSUE THREAD

**Issue by moodysalem** [starkware-libs/cairo#3630]
https://github.com/starkware-libs/cairo/blob/b47729624df54bcb3691c62a4d875a8d48f6220e/corelib/src/starknet/account.cairo#L10

Because of this, no dispatcher/trait is generated. Should they be?

**Comment by moodysalem** [comment]
also why isn't this version from 3 weeks ago published in 2.0.1? 🤔

**Comment by orizi** [comment]
generally our compiler release process for a starknet version:
we start with some `major.minor.0-rc0`
we add required fixes while updating only the rc version `major.minor.0-rc<i>`.
when we decide we are done we release `major.minor.0` - and then only do fixes that are a must in the patch version `major.minor.patch`.
