### ISSUE TITLE
bug: Partial move / struct member access becomes complete move across conditional boundary

### ISSUE THREAD

**Issue by akirillo** [starkware-libs/cairo#3658]
# Bug Report

**Cairo version:**

2.0.2

**Current behavior:**

It is my understanding (from the Rust type system) that for a struct which has copyable members, accessing those members does not constitute a move of the struct itself.

This seems to be the case in Cairo as well, since e.g. the following code compiles:

```rust
#[derive(Drop)]
struct MyStruct {
    copyable: u8,
    non_copyable: Array<u8>,
}

#[generate_trait]
impl MyStructImpl of MyStructTrait {
    fn repro(ref self: MyStruct) {
        let copyable = self.copyable;
        self.uses_self();
    }

    fn uses_self(ref self: MyStruct) {}
}
```

However, when the subsequent usage of the entire struct is inside of an `if` branch, suddenly the compiler considers the entire struct to have previously been moved.

I.e. this:
```rust
#[derive(Drop)]
struct MyStruct {
    copyable: u8,
    non_copyable: Array<u8>,
}

#[generate_trait]
impl MyStructImpl of MyStructTrait {
    fn repro(ref self: MyStruct) {
        let copyable = self.copyable;
        if true {
            self.uses_self();
        }
    }

    fn uses_self(ref self: MyStruct) {}
}
```

Fails with the following error message:
```shell
error: Variable was previously moved. Trait has no implementation in context: core::traits::Copy::<core::array::Array::<core::integer::u8>>
 --> repro.cairo:10:24
        let copyable = self.copyable;
                       ^**^
```

**Expected behavior:**

I wouldn't expect the presence of a conditional branch to affect the ownership semantics here, and am as of yet unsure how to work around this...

**Comment by orizi** [comment]
Linked PR solves the issue.
