### ISSUE TITLE
bug: unexpected `move` + conditional + array combination

### ISSUE THREAD

**Issue by pscott** [starkware-libs/cairo#3678]
# Bug Report

**Cairo version:**

cairo: 2.0.1

**Current behavior:**

After taking a snapshot of a struct, calling `clone` on that struct doesn't work properly.

**Expected behavior:**

We should be able to call `clone()` on a struct even if it has been snapshot before.

**Related code:**

```rust
use array::ArrayTrait;
use clone::Clone;

#[derive(Clone, Drop)]
struct Foo {
    f: felt252,
    arr: Array<felt252>,
}

fn check(f: @felt252) -> bool {
    true
}

fn main() {
    let foo = Foo {f: 0, arr: array::ArrayTrait::new()};

    if check(@foo.f) {
      let cl = foo.clone();
    }
}
```

**Other information:**

Interesting things to note:
1. One can fix this issue by using `check((@foo).f)` rather than `(@foo.f)`. (Thanks @enitrat ). So it's actually a **syntax** error, not a functional error?
2. Another way of fixing this is :
```rust
let snap = @foo;
if (check(snap.f) {
  let cl = foo.clone();
}
```
3. If you remove the `if`, it also works (but it's not the same, functionality-wise):
```rust
let b = @foo.f;
let cl = foo.clone();
```
this makes me think it might be related to https://github.com/starkware-libs/cairo/issues/3658 

4. Removing the `arr` field of `Foo` removes the error. So this has to do with non-copyable elements I believe.

**Comment by ilyalesokhin-starkware** [comment]
Fixed by #3739
