### ISSUE TITLE
feat: using composite types as map keys

### ISSUE THREAD

**Issue by milancermak** [starkware-libs/cairo#3684]
# Feature Request

It would be awesome if there was an automagical way how we could use custom composite types as keys in `LegacyMap`.

For example, I have this type:

```rust
struct Pool {
    tokenA: ContractAddress,
    tokenB: ContractAddress,
    fee: u128
}
```

and I want to use it as a key in a storage variable, e.g. `is_enabled: LegacyMap<Pool, bool>`.

**Describe Preferred Solution**

I think the best solution would be if there was a something like a `MapKey` trait that would transform the type into a `felt252` by hashing all its members, which could then be used in the `LegacyMap`. This should, of course, be automatically implemented by the Starknet plugin via a derive arg:

```rust
trait MapKey<T> {
    fn as_map_key(self: T) -> felt252;
}

#[derive(MapKey)]
struct Pool {
    tokenA: ContractAddress,
    tokenB: ContractAddress,
    fee: u128
}

//
// MapKey derive would create an impl block of MapKey<Pool>, e.g.
//

impl PoolMapKeyImpl of MapKey<Pool> {
    fn as_map_key(self: Pool) -> felt252 {
        let mut members: Array<felt252> = Default::default();
        members.append(self.tokenA.into());
        members.append(self.tokenB.into());
        members.append(self.fee.into());

        poseidon_hash_span(members.span())
    }
}

//
// and then in my contract
//

fn disable_pool(ref self: ContractState, pool: Pool) {
    self.is_enabled.write(pool, false);
}
```

**Describe Alternatives**

I know I can use a tuple as a key in the `LegacyMap` declaration, but that has its limits.

**Comment by orizi** [comment]
Keys for `LegacyMapping` are all types that implement `LegacyHash`.

currently there's no `derive` for it - but it is already in the works.

**Comment by milancermak** [comment]
Possible now thanks for `#[derive(Hash)]`, closing.
