### ISSUE TITLE
bug: negative signed integers 

### ISSUE THREAD

**Issue by dbejarano820** [starkware-libs/cairo#3726]
# Bug Report

**Cairo version:** 2.1.0-rc0

**Current behavior:** Not able to implement negative ints

<img width="763" alt="image" src="https://github.com/starkware-libs/cairo/assets/58019353/871eb16a-263b-4eba-8402-ba89e72b087b">
<img width="315" alt="image" src="https://github.com/starkware-libs/cairo/assets/58019353/82c5688e-6149-4fcd-8ac8-4f1df739b92d">
<img width="710" alt="image" src="https://github.com/starkware-libs/cairo/assets/58019353/104067b8-3c4a-4882-ac29-42e28d533eac">

**Expected behavior:**  Be able to use negative integers

**Steps to reproduce:**

**Related code:**

```
let x: i32 = -1;
```

**Comment by orizi** [comment]
this is not a bug - support for signed  integers is yet to be added.
