### ISSUE TITLE
Sort external `mod` and `use` directives in cairo-formatter

### ISSUE THREAD

**Issue by ericnordelo** [starkware-libs/cairo#3729]
# Feature Request (cairo-formatter)

Move external `mod` (defined in other files) and/or `use` lines to the top of the wrapper mod, sorted by some criteria.

**Describe Preferred Solution**

Convert this:

```
#[starknet::contract]
mod ReentrancyMock {
    use starknet::get_contract_address;

    #[storage]
    struct Storage {}

    use starknet::ContractAddress;
}
```

into this:

```
#[starknet::contract]
mod ReentrancyMock {
    use starknet::ContractAddress;
    use starknet::get_contract_address;

    #[storage]
    struct Storage {}
}
```

or this:

```
mod B;
use B::some;
mod C;
mod A;
use something;
use C::some;
```

into this:

```
mod A;
mod B;
mod C;

use something;
use B::some;
use C::some;
```

**Describe Alternatives**

I like alphabetical sort, but we could have a different criteria (like line length), or even a config file allowing us to change criterias.

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by orizi** [comment]
i think being rust-like is probably the most sensible - so alphabetical.

In order to this - the formatter would need to look at the concept of a full module items  - and decide to actually sort them.
note that if you already do this - merging uses is probably similar enough as well (`use a::b; use a::c;` --> `use a::{b, c}`).

**Comment by orizi** [comment]
@ericnordelo - are you trying to take over this task? - and if so - do you require assistance?

**Comment by ericnordelo** [comment]
> @ericnordelo - are you taking over this task? - and if so - do you require assistance?

Yes, I will submit the PR tomorrow, and we can improve the solution from that if you agree.
