### ISSUE TITLE
bug: Error calling external function from another external function in the same implementation

### ISSUE THREAD

**Issue by meirbank** [starkware-libs/cairo#3730]
# Bug Report

**Cairo version:** 2.0.1

**Current behavior:**

Error calling external function from another external function in the same implementation:

error: Method `start` not found on type "@vesting_wallet::vesting_wallet::VestingWallet::ContractState". Did you import the correct trait and impl?

**Expected behavior:**

Ability to call an external function from another external function

**Steps to reproduce:**

Compile the code below in the same external implementation

**Related code:**

```
        fn start(self: @ContractState) -> u64 {
            self._start.read()
        }

        fn duration(self: @ContractState) -> u64 {
            self._duration.read()
        }

        fn end(self: @ContractState) -> u64 {
            self.start() + self.duration()
        }
```

**Comment by orizi** [comment]
note that `self` is only supported as a method from function that are at an impl.
so - assuming you've had:
```
#[starknet::contract]
mod c {
    #[storage]
    struct Storage { _start: u64, _duration: u64 }
    fn start(self: @ContractState) -> u64 { self._start.read() }
    fn duration(self: @ContractState) -> u64 { self._duration.read() }
    fn end(self: @ContractState) -> u64 { self.start() + self.duration() }
}
```
you'd need instead:
```
#[starknet::contract]
mod c {
    #[storage]
    struct Storage { _start: u64, _duration: u64 }
    #[external(v0)]
    #[generate_trait]
    impl Impl of Trait {
        fn start(self: @ContractState) -> u64 { self._start.read() }
        fn duration(self: @ContractState) -> u64 { self._duration.read() }
        fn end(self: @ContractState) -> u64 { self.start() + self.duration() }
    }
}
```

**Comment by orizi** [comment]
@meirbank - can you please make sure i understood the bug correctly and if so close it?
thanks!

**Comment by meirbank** [comment]
Hello. While it is possible I am simply mistaken or missing something obvious, I don't think that was the bug. To reproduce this, you can:

(1) Fork https://github.com/meirbank/eth-paris-2023

(2) Change line 55 in https://github.com/meirbank/eth-paris-2023/blob/main/src/vesting_wallet.cairo, from:
`self._start.read() + self._duration.read()`
to
`self.start() + self.duration()`

(3) scarb build

As you can see these functions are within an implementation.

**Comment by orizi** [comment]
you are missing a `use path::to::interface::interface_trait;` from inside the module (as traits that are not in scope cannot be resolved).

in your particular case - just adding `use interface::IVestingWallet;` in the contract module suffices.
