### ISSUE TITLE
feat: 

### ISSUE THREAD

**Issue by Brian605** [starkware-libs/cairo#3774]
# Feature Request

**One Off cairo Installer option**

**Something like cairo install that checks for rust installation and then installs cairo**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ Tick] Yes
- [ ] No

**Comment by orizi** [comment]
do you mean a script for developers of the cairo repo initiation?
otherwise - again all they need is just to use scarb - no need for anything regarding rust.
