### ISSUE TITLE
feat: Support starknet-foundry tests in Cairo-LS

### ISSUE THREAD

**Issue by maciektr** [starkware-libs/cairo#3777]
# Feature Request

`snforge` test collection allows for placing tests inside `tests` folder next to the `src` directory. Such test files are not imported into the package, thus Cairo-LS does not support them fully, e.g. jumping to implementation.

**Describe Preferred Solution**

Set crate roots for files from `/tests` directory. Not sure yet if cairo-ls should assume this behaviour by convention. 

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by maciektr** [comment]
Scarb does not compile tests at the moment (cc @MaksymilianDemitraszek), thus I am not sure if this is a Scarb responsibility to resolve paths to those tests 🤔. I think we have yet to decide which component of the ecosystem should be responsible for this.

**Comment by orizi** [comment]
This is about *project definition* (which tells the LS what to do) - if we want Scarb to automatically add this to the project definition - it should do this.

In all other cases (not using scarb) - if we add in the `cairo_project.toml` file `tests = "tests"` line - it will be in the language server.

**Comment by maciektr** [comment]
I will close and move this issue then, thanks for your clarification!
