### ISSUE TITLE
Declare fail: Error: OSError: [Errno 8] Exec format error

### ISSUE THREAD

**Issue by fico308** [starkware-libs/cairo#3796]
# Bug Report

**Cairo version:**
cairo: v0.12.0
starknet: v2.0.0

**Current behavior:**
Declare fail when I set `allowed-libfuncs-list.name = "all"`
```
> starknet declare --contract nft.json --account fico

Error: OSError: [Errno 8] Exec format error: '/Users/fico/cairo_venv/lib/python3.9/site-packages/starkware/starknet/compiler/v1/bin/starknet-sierra-compile'
```

**Expected behavior:**
Declare success

**Steps to reproduce:**

1. `starknet-compile src/nft.cairo --allowed-libfuncs-list-name all > nft.json`
2. `starknet declare --contract nft.json --account fico`

**Related code:**

nft.cairo
```
use keccak::keccak_u256s_be_inputs;

fn sign(self: @ContractState, user: ContractAddress) -> u256 {
            let chain_id = get_tx_info().unbox().chain_id; /// felt252
            let nft_core = contract_address_to_felt252(contract_address_const::<0>());  /// ContractAddress
            let mut input = Default::default();
            input.append(chain_id.into());
            input.append(nft_core.into());
            input.append(contract_address_to_felt252(user).into());
            keccak::keccak_u256s_le_inputs(input.span())
}

```
Scarb.toml
```
[package]
name = "nft"
version = "0.1.0"

[dependencies]
starknet = "2.0.0"

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "all"
```

**Other information:**

OS: MacOS (Apple M1 Max)

**Comment by cymqqqq** [comment]
Hi, maybe you can use scarb to build and starkli to declare and deploy your contract?

**Comment by fico308** [comment]
> Hi, maybe you can use scarb to build and starkli to declare and deploy your contract?

I've tried and got a new error
```
> starkli declare nft.json

Error: EOF while parsing a value at line 1 column 0
```

**Comment by cymqqqq** [comment]
Hi @fico308 , you can not use starkli to declare a JSON file directly, you must first use "scarb build" command to generate a sirrea middle file, and then use "starkli declare" command to generate your class hash, such as my operation:
starkli declare target/dev/starknet_contracts_Ownable.sierra.json --network goerli-1 --compiler-version 2.0.1.
notes: Before this, you must have a keystore.json and account.json file for performing the above operation.(both starkli declare && starkli deploy)

**Comment by fico308** [comment]
@cymqqqq Thanks for your response, the previous error is caused by I didn't create a valid deployer account by starkli. I just create a new deployer and follow your step to deploy contract and I got a new error:
```
> scarb build

> starkli declare target/dev/nft.sierra.json
Declaring Cairo 1 class: 0x029d506cd6edf0cae2e9280ff965d9c4e3bbf610ae93b5f3b3406ba46527cd13
Compiling Sierra class to CASM with compiler version 2.0.1...
CASM class hash: 0x04e72e03ebab6563faa8d89fc805c84af6905459c0d408b00173d39086b9e6ab
Error: code=-32603, message="Internal error: StarknetErrorCode.COMPILATION_FAILED: Compilation failed. Error: Libfunc keccak_syscall is not allowed in the libfuncs list '/usr/local/lib/python3.9/site-packages/starkware/starknet/compiler/v1/testnet_libfuncs.json'.
 Run with '--allowed-libfuncs-list-name all' to allow all libfuncs.
"

> starkli declare target/dev/galxenft_StarNFT.sierra.json --allowed-libfuncs-list-name=all

error: unexpected argument '--allowed-libfuncs-list-name' found
tip: to pass '--allowed-libfuncs-list-name' as a value, use '-- --allowed-libfuncs-list-name'
Usage: starkli declare --account <ACCOUNT> <FILE>
For more information, try '--help'.

> starkli declare target/dev/galxenft_StarNFT.sierra.json -- --allowed-libfuncs-list-name=all

error: unexpected argument '--allowed-libfuncs-list-name=all' found
Usage: starkli declare [OPTIONS] --account <ACCOUNT> <FILE>
For more information, try '--help'.

**Comment by cymqqqq** [comment]
Hi @fico308 , can you check your version of scarb? Because until now, only version 0.5.1 of scarb can be declared by starkli command. I have met this error before, so I reinstalled the 0.5.1 version, so you can check it first. :)

**Comment by cymqqqq** [comment]
Can you try this "starkli declare target/dev/nft.sierra.json --network goerli-1 --compiler-version 2.0.1"?

**Comment by fico308** [comment]
Same error

Fico
Galxe

**Comment by fico308** [comment]
Same error

**Comment by cymqqqq** [comment]
Hi, do you rebuild your cairo code when you reinstall scarb 0.5.1? If not, you can use scarb 0.5.1 to rebuild it again, and then use starkli declare to try it again.

**Comment by cymqqqq** [comment]
"I've tried scarb v0.5.1, build succeeds but declare still fails", you mean you rebuild again your cairo code when you reinstall the scarb 0.5.1, right?

**Comment by fico308** [comment]
yes, I rebuild the contract before declare;

I got some info from other people, they say the unsafe libfuncs not allowed on testnet, maybe it's the root cause.

**Comment by cymqqqq** [comment]
Ok, so maybe it's the second reason for the error "Error: code=InvalidContractClass, message="Compiled versions older than 1.1.0 are not supported. Got version 1.2.1."
Summary:
1. scarb version problem(I meet this error)
2. unsafe libfuncs

**Comment by enitrat** [comment]
Hi @fico308, here is the description of your error and some troubleshooting steps to follow. 

Note that the cairo-lang is now deprecated and you should use [Starkli](https://github.com/xJonathanLEI/starkli) instead.

``` 
Error: OSError: [Errno 8] Exec format error: '/opt/homebrew/lib/python3.9/site-packages/starkware/starknet/compiler/v1/bin/starknet-sierra-compile'
``` 

This error is generated when cairo-lang attempts to compile your Sierra code using an imported Rust binary, 'starknet-sierra-compile'. However, in some instances, the imported binary may not be compatible with your system architecture.

The solution is to replace the incompatible Rust binary with a locally built version. The following steps can guide you through this process:

*Build the 'starknet-sierra-compile' binary locally.* We did this before when we set up our environment by cloning the starknet repository and building the binary. If you have not done this yet, please refer to the Setting Up Your Environment subchapter.

*Replace the incompatible binary in the Python package.* The locally built 'starknet-sierra-compile' binary can be moved into the Python package directory. Here's an example of how to do this:

``` 
cp ~/.cairo/target/release/starknet-sierra-compile /opt/homebrew/lib/python3.9/site-packages/starkware/starknet/compiler/v1/bin/starknet-sierra-compile
```

**Comment by fico308** [comment]
@enitrat Thanks for your reply, I replaced the file and now only have the InvalidContractClass error;

In addition, I would like to ask if I want to implement the hash function (hash some function arguements for signature verification), is there any other function implemented on testnet&mainnet besides keccak?

**Comment by enitrat** [comment]
@fico308 if you want to hash things in a Starknet-native way (keccak is more expensive on SN), then you can use `pedersen` of `poseidon`. To use pedersen you can use the [LegacyHash](https://github.com/starkware-libs/cairo/blob/main/corelib/src/hash.cairo) trait
