### ISSUE TITLE
feat: Add sierra debug infos

### ISSUE THREAD

**Issue by LucasLvy** [starkware-libs/cairo#3826]
# Feature Request

For coverage (and I assume other things) we'll need to remap the sierra instructions to the original cairo code.
Similarly to how casm debug infos worked (mapping pc => casm instruction location) a mapping from sierra instruction (location ?) => cairo instruction location would do the trick.

**Comment by orizi** [comment]
this now exists as part of the compilation to sierra process.
`SierraProgramDebugInfo` has the information about a `StableLocation` (which correspond to a span of the original code) per sierra statement.
