### ISSUE TITLE
test-runner hanging forever

### ISSUE THREAD

**Issue by ericnordelo** [starkware-libs/cairo#3828]
# Bug Report

**Cairo version:**

2.0.2

**Current behavior:**

The test-runner sometimes hangs forever (I've left it there for around ten minutes). It seems not to be related to the tests, but to the code to compile (it hangs after adding code, not tests, and this code is not even tested).

**Expected behavior:**

Show some kind of error, or run successfully. Maybe logging some output to debug why it hangs could be helpful.

**Steps to reproduce:**

Clone this [openzeppelin-contracts fork from this commit](https://github.com/ericnordelo/cairo-contracts/commit/dea4d9c84abf4713e56d3bf077b261230c89890b). Rune `make install`, and then `make test`.

**Related code:**

The hanging is fixed by adding `mod integers;` in the structs file (a re-export missing), but I think the test-runner should give some feedback regarding this, instead of hanging.

**Comment by orizi** [comment]
Fixed in linked PR a while ago.
