### ISSUE TITLE
feat: Add a get_nonce syscall

### ISSUE THREAD

**Issue by ClementWalter** [starkware-libs/cairo#3834]
# Feature Request

**Describe the Feature Request**

When sending a transaction, it's possible to retrieve the caller account nonce with the. `get_tx_info`. However, in a view function, there is actually no way to get this information.

**Describe Preferred Solution**

Add a syscall to return the value `get_nonce(address)`.

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by orizi** [comment]
I don't think i understand - can you add the exact code you would have called in a transaction?

**Comment by ClementWalter** [comment]
I'd like to get the current nonce of a given address in view calls. Currently, this information is only available for the caller only in execute, in the `TxInfo`

**Comment by ArielElp** [comment]
Hey, this is more of a Starnet question and not really compiler-related (if we'll decide to prioritize support for this in the sequencer and OS, then adding a Cairo syscall is the small final step in the process). I suggest opening a discussion in the community forum to see if we can find compelling enough use cases.

IMO this is not urgent, as we already have a few syscalls we're looking to add which I think have clearer use-cases: `is_declared(class_hash)` and `get_class_hash_at(address)`.
