### ISSUE TITLE
bug: duplicate function declaration is skipped

### ISSUE THREAD

**Issue by DavideSilva** [starkware-libs/cairo#3835]
# Bug Report

**Cairo version:**
```cairo: 2.0.2 (https://crates.io/crates/cairo-lang-compiler/2.0.2)```

**Current behavior:**
Compiler does not warn about duplicate function implementations when using the `#[external(v0)` attribute on specific function implementations

**Expected behavior:**
Compiler should warn about duplication function implementations like it does when using the `#[external(v0)]` attribute on trait implementation blocks

**Steps to reproduce:**

The following code does not compile, as expected, with a warning saying the `get_name` function is defined multiple times

```rust
#[starknet::interface]
trait IMyFirstContract<ContractState> {
    fn get_value(self: @ContractState) -> u64;
}

#[starknet::contract]
mod MyFirstContract {
    #[storage]
    struct Storage {
        value: u64
    }

    #[constructor]
    fn constructor(ref self: ContractState) {
        self.value.write(1)
    }

    #[external(v0)]
    impl PublicFunctions of super::IMyFirstContract<ContractState> {
        fn get_value(self: @ContractState) -> u64 {
            self.value.read()
        }
    }

    #[external(v0)]
    impl OtherTraitImplementation of super::IMyFirstContract<ContractState> {
        fn get_value(self: @ContractState) -> u64 {
            self.value.read()
        }
    }
}
```

However, if we move the `#[external(v0)]` declarations to the top of the functions instead, it compiles without any warning

```rust
impl PublicFunctions of super::IMyFirstContract<ContractState> {
    #[external(v0)]
    fn get_value(self: @ContractState) -> u64 {
        self.value.read()
    }
}
                                                                          
impl OtherTraitImplementation of super::IMyFirstContract<ContractState> {
    #[external(v0)]
    fn get_value(self: @ContractState) -> u64 {
        self.value.read()
    }
}
```

In fact, this also compiles when we move just one of the `#[external(v0)]` declarations to one of the functions and keep the other on the trait implementation block.

Is this intended behaviour or a bug?

**Comment by orizi** [comment]
I think this isn't a bug - as these don't appear in the same manner in the ABI.
So it mostly depends on how we consider the structure of the ABI, is a function named: `<ImplName>::<Method>` is completely separate than just the `<Method>`.
@ArielElp  @spapinistarkware WDYT?

**Comment by DavideSilva** [comment]
Well, I guess you are right when you say they don't appear in the same manner in the ABI 😅 
Adding `#[external(v0)]` to each individual function of a trait implementation doesn't make the functions appear in the ABI

```json
[
  {
    "type": "constructor",
    "name": "constructor",
    "inputs": []
  },
  {
    "type": "event",
    "name": "my_first_contract::my_first_contract::MyFirstContract::Event",
    "kind": "enum",
    "variants": []
  }
]
```

**Comment by orizi** [comment]
`#[abi(per_item)]` and `#[abi(embed_v0)]` now exist for proper declarations of impls.

**Comment by milancermak** [comment]
@orizi what does `#[abi(per_item)]` do? How does it differ from `#[abi(embed_v0)]`?

**Comment by orizi** [comment]
per_item - actually per item - meaning the functions are all in the same impl for comfort - but that is it - each function should be marked by itself (can be marked as external, constructor, l1_handler, or nothing).
embed_v0 - this is an impl of a starknet interface - and should be added as a total unit.
