### ISSUE TITLE
bug: u256 constants will cause `Error Failed setting up runner`

### ISSUE THREAD

**Issue by enitrat** [starkware-libs/cairo#3837]
# Bug Report

**Cairo version:**
`cairo: 2.1.0-rc2`

**Current behavior:**
Testing the following code results in 

```shell
❯ scarb test
testing temp ...
Error: Failed setting up runner.

Caused by:
    Failed calculating gas usage, it is likely a call for `gas::withdraw_gas` is missing.
error: process did not exit successfully: exit status: 1
```

**Expected behavior:**
Either the compilation should fail because it is an unsupported feature, or the test runner should run properly.

**Steps to reproduce:**
```rust
#[test]
#[available_gas(2000000000)]
fn fail_setting_up_runner() {
    let x = CONST_256_POW_32 + 1;
}
```

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Comment by orizi** [comment]
opened twice. https://github.com/starkware-libs/cairo/issues/3838
