### ISSUE TITLE
feat: Add `deref_or` and `destruct` to `Nullable`, add `destruct` to `Box`

### ISSUE THREAD

**Issue by enitrat** [starkware-libs/cairo#3854]
# Feature Request
- Add a `fn deref(self: Nullable<T>, value: T) -> T` to `NullableTrait` to either deref a Nullable<T> or return the provided value
- Add the `Destruct` implementation in `nullable.cairo`
- Add the `Destruct` implementation in `box.cairo`
**Describe the Feature Request**

**Describe Preferred Solution**
```rust
    fn deref_or(self: Nullable<T>, default: T) -> T {
        match match_nullable(self) {
            FromNullableResult::Null => default,
            FromNullableResult::NotNull(value) => value.unbox(),
        }
    }
```    
```rust
impl NullableDestruct<T, impl TDestruct: Destruct<T>> of Destruct<Nullable<T>> {
    fn destruct(self: Nullable<T>) nopanic {}
}
```
```rust
impl BoxDestruct<T, impl TDestruct: Destruct<T>> of Destruct<Box<T>> {
    fn destruct(self: Box<T>) nopanic {}
}
```

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by orizi** [comment]
The destruct part would probably require additional features in the language,
Since we'd have several implementations of Destruct in the droppable cases (as `Drop` creates a default `Destruct` impl)
Solutions:
1. Impl ranking for when inferring a type
2. Enforcing *not* having a particular impl available (in this case, when implementing destruct, no `Drop<T>` can be available.

**Comment by orizi** [comment]
you'd need to have a specific one - not a generic one.

The issue is this:

If you have both a Drop and Destruct for the nullable - type, anywhere that requires a destruct, would have 2 impls of destruct for nullable, and would not know which one to choose.

**Comment by enitrat** [comment]
Okay, indeed that's whay I ended up doing; thanks :)
