### ISSUE TITLE
feat: methods taking snapshots should snapshot the highest-level struct

### ISSUE THREAD

**Issue by enitrat** [starkware-libs/cairo#3869]
# Feature Request

**Describe the Feature Request**
It would be great if we could abstract explicitly taking snapshots at the "correct level" when calling methods on structs that expect snapshots. Consider this code example, which does not compile.

```rust
#[derive(Drop)]
struct CallContext {}

#[generate_trait]
impl CallContextImpl of CallContextTrait {
    fn foo(self: @CallContext) {}
}

#[derive(Drop)]
struct ExecutionContext {
    call_ctx: CallContext, 
}

fn bar(ref ctx: ExecutionContext) {}

#[test]
#[available_gas(200000)]
fn test() {
    let mut ctx = ExecutionContext { call_ctx: CallContext {} };
    ctx.call_ctx.foo();
    if 1 == 0 {
        bar(ref ctx);
    };
}
```

`foo` takes a `self: @CallContext` as a parameter, but is a member of the ExecutionContext struct. The way I understand it here is that what happens implicitly is that `foo` is called as `@(ctx.call_ctx).foo`, meaning that we access the `call_ctx:CallContext` member on `ctx` itself.
It would be better if what was implicitly done was `(@ctx).call_ctx.foo()` instead, so that we're actually accessing `call_ctx:@CallContext` on a snapshot of `ctx`.
With this second solution, the code would compile properly.

It's not always clear why we have this `Variable was previously moved`; especially here given that the error message appears as
```shell
error: Variable was previously moved. Trait has no implementation in context: core::traits::Copy::<method_snapshots::CallContext>
 --> lib.cairo:22:5
    if 1 == 0 {
    ^*********^
 ```
 which is not easy to debug.

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by spapinistarkware** [comment]
Your example compiles on main. Can you check?
Also, it already works as you mentioned. x.a.b.c.foo() is foo((@x).a.b.c)

**Comment by enitrat** [comment]
> Your example compiles on main. Can you check?

Re-tried with Scarb nightly, and it works now :)
