### ISSUE TITLE
feat: Implement One Trait Analogous to Rust's in Cairo

### ISSUE THREAD

**Issue by neotheprogramist** [starkware-libs/cairo#3881]
**Feature Proposal**

Considering our existing implementation of the [Zeroable trait](https://github.com/starkware-libs/cairo/blob/main/corelib/src/zeroable.cairo), it would be beneficial to add an analogous One trait to our Cairo compiler.

**Background**

In Rust, there exists a [One trait](https://docs.rs/num-traits/latest/num_traits/identities/trait.One.html) that serves a similar purpose for the multiplicative identity. An analogous trait in Cairo would enrich our library and provide consistent utility alongside the [Zeroable trait](https://github.com/starkware-libs/cairo/blob/main/corelib/src/zeroable.cairo).

**Desired Behavior**

The task is to design and implement a One trait in the Cairo compiler that aligns with the concept of Rust's [One trait](https://docs.rs/num-traits/latest/num_traits/identities/trait.One.html). This should include the essential functions and features to make it as effective as the Rust version.

**Comment by orizi** [comment]
Fixed by #4254 - thanks @enitrat
