### ISSUE TITLE
feat: single member struct shorthand

### ISSUE THREAD

**Issue by milancermak** [starkware-libs/cairo#3908]
# Feature Request

**Describe the Feature Request**

I'd like to have a simplified way how to instantiate a struct with just a single member.

**Describe Preferred Solution**

If a struct has only a single member, it's superfluous to pass its name when creating an instance of said struct.

```rust
let token = contract_address_const::<0xbeef>();

// like this

IERC20Dispatcher { token }.balance_of(get_caller_address());

// instead of this

IERC20Dispatcher { contract_address: token }.balance_of(get_caller_address());
```

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [] No

I can give it a go if someone can tell me where to start.

**Comment by orizi** [comment]
I don't think we should support this.
If we do - should be something like rusts direct wrapper types:
```
struct SingleUnnamedValue(OtherType);
```

In your particular case i'd do either:
```
IERC20Dispatcher { contract_address: contract_address_const::<0xbeef>() }.balance_of(get_caller_address());
```
or 
```
let contract_address = contract_address_const::<0xbeef>();
IERC20Dispatcher { contract_address }.balance_of(get_caller_address());
```

**Comment by milancermak** [comment]
I know I can do the alternatives presented above and that's precisely why I'm suggesting this feature. Typing out the `contract_address` every time is unnecessarily verbose. Plus the second suggestion doesn't work well when you have to deal with more than one dispatcher in the same function (think calling ETH and BTC tokens).

In this dispatcher case, the wrapper type wouldn't work, since dispatchers are often different, e.g. IERC20Dispatcher, IERC721Dispatcher, etc.

**Comment by orizi** [comment]
Construction should match declaration - so this should not be supported.
If adding an additional member makes you write a completely different construction it is quite weird IMO.
If we want a short construction for a type - a `::new` method should be implemented for it.

**Comment by orizi** [comment]
> FWIW, Rust's [tuple structs](https://doc.rust-lang.org/book/ch05-01-defining-structs.html#using-tuple-structs-without-named-fields-to-create-different-types) would fit my use case nicely.

That was my first point in my original answer.

**Comment by orizi** [comment]
Closing - as this would be only for tuple structs - which isn't a feature currently planned.
