### ISSUE TITLE
bug: redundant ENTRYPOINT_FAILED when asserting across many contract calls

### ISSUE THREAD

**Issue by wraitii** [starkware-libs/cairo#3954]
# Bug Report

**Cairo version:**

2.2.1

**Current behavior:**

When an assertion fails in a test, there is an ENTRYPOINT_FAILED for each entrypoint that was crossed, not only the failing one. This quickly makes stack-traces using e.g. dojo quite annoying.
This is made worse by the fact that `should_panic` expects the full list of all ENTRYPOINT_FAILED.

I currently have some tests cases that have 4, 5, 6 or even 7 ENTRYPOINT_FAILED in a row, making testing rather awkward.

**Expected behavior:**

I'm not entirely sure if ENTRYPOINT_FAILED is useful at all if there is another assertion, but there probably should only be one?
Alternatively, should_panic should probably be allowed to match on any exception, not all of them ? 

**Steps to reproduce:**

You need a test that calls a contract and some Dispatcher calls, then an assertion that fails. See e.g. https://github.com/briqNFT/briq-protocol/blob/dojo/src/tests/test_set_nft.cairo

**Comment by orizi** [comment]
I don't really see how we can avoid it, you probably would like to know if you are panicking inside a contract, and not in your code, so each and every failing call needs to add this.
failing at the 5th recursive call is different than failing in the 4th.

You generally can not used should panic but handle it at the call directly (using the "safe" dispatcher), and do whatever you want to test there.

Having more options in the should panic parameter is a possible feature as well - but we are unlikely to go for it any time soon.
This can be a community contribution if anyone wants to.

**Comment by wraitii** [comment]
> You generally can not used should panic but handle it at the call directly (using the "safe" dispatcher), and do whatever you want to test there.
I don't understand what you mean by this? Is this the regular `#[starknet::interface]`-derived Dispatcher ?

**Comment by orizi** [comment]
Two dispatchers are generated from `#[starknet::interface]`:
`MyABIDispatcher` - has the same signatures as it the interface.
`MyABISafeDispatcher` - has the same signatures as in the interface - but wrapped with a `starknet::SyscallResult`.
