### ISSUE TITLE
feat: warn for unused return value for specific types

### ISSUE THREAD

**Issue by lambda-0x** [starkware-libs/cairo#3960]
# Feature Request

**Describe the Feature Request**

Give a compiler warning for unused return type from a function call. Because in cairo code we generally don't want to panic so its conventional to use `Result` type in alot of places.

It can be easy to miss a returned `Result` and propagate it further, which can lead to logical bugs in the problem which are subtle to find.

**Describe Preferred Solution**

We can implement something similar to [`must_use`](https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-must_use-attribute) attribute in rust. This will add ability for user specified types to give a warning as well.

**Describe Alternatives**

If adding an attribute is not possible for now, we should at least warn for core types like `Result`, and maybe others.

**Related Code**

**Additional Context**

See https://github.com/kkrt-labs/kakarot-ssj/pull/182 for one such case.

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

Would love to help but I am not a compiler dev :)

- [ ] Yes
- [x] No

**Comment by milancermak** [comment]
@lambda-0x FWIW, [Caracal](https://github.com/crytic/caracal) has an `unused-return` detector. Maybe that will be beneficial to you?
