### ISSUE TITLE
bug: error Variable was previously moved

### ISSUE THREAD

**Issue by orangeryang** [starkware-libs/cairo#3984]
# Bug Report

**Cairo version:**

2.1.0

**Current behavior:**

error: Variable was previously moved. Trait has no implementation in context: core::traits::Copy::<core::array::Array::<cc_map::generator::dungeons_generator::DungeonsGenerator::Room>>
 --> dungeons_generator.cairo:90:17
        return (rooms, floor);
                ^***^

**Expected behavior:**

It should goes well right?

**Steps to reproduce:**

just scarb build or cairo lsp will show that

**Related code:**

```
#[starknet::contract]
mod DungeonsGenerator {
    use core::traits::{Into, TryInto};
    use core::option::OptionTrait;
    use core::array::SpanTrait;
    use starknet::ContractAddress;
    use array::ArrayTrait;

    #[storage]
    struct Storage {}

    #[derive(Copy, Drop, starknet::storage)]
    struct Room {
        x: u128,
        y: u128,
        width: u128,
        height: u128
    }

    #[constructor]
    fn constructor(ref self: ContractState) {}

    fn generate_rooms() -> (Array<Room>, Array<u128>) {
        let mut floor: Array<u128> = ArrayTrait::new();
        let mut num_rooms = 10;
        let mut safe_check = 256;
        let mut rooms: Array<Room> = ArrayTrait::<Room>::new();
        loop {
            if num_rooms == 0 {
                break;
            }
            let rooms_span = rooms.span();
            if safe_check == 0 {
                break;
            }
            safe_check = safe_check - 1;
        };
        return (rooms, floor);
    }
}
```

**Other information:**

**Comment by LucasLvy** [comment]
It's not a bug, `Array<T>` doesn't implement copy https://github.com/starkware-libs/cairo/blob/5b613fd7234886eb4b0c8fc167d8d8bc2ae5fe7b/corelib/src/array.cairo#L8-L9
You might want to use a snapshot for that

**Comment by Again1013** [comment]
Hi Lucas

      Thanks for the reply first of all~

      And yes the Array<T>​ doesn't implement copy​, so I use the span​ of it.
      
      So using span()​ in the loop means the array move​ into the loop​, so I can't have it in the return​. Is it right?​

________________________________
发件人: Lucas @ StarkWare ***@***.***>
发送时间: 2023年8月30日 12:27
收件人: starkware-libs/cairo ***@***.***>
抄送: Again1013 ***@***.***>; Author ***@***.***>
主题: Re: [starkware-libs/cairo] bug: error Variable was previously moved (Issue #3984)


It's not a bug, Array<T> doesn't implement copy https://github.com/starkware-libs/cairo/blob/5b613fd7234886eb4b0c8fc167d8d8bc2ae5fe7b/corelib/src/array.cairo#L8-L9
You might want to use a snapshot for that

**Comment by orizi** [comment]
It is a known issue with using vars snapshot within a loop.
To fix this temporarily you can take `let rooms_snap = @rooms;` and use it instead of rooms in the loop.
