### ISSUE TITLE
bug: cairo-fmt fails to correctly format destructuring structs.

### ISSUE THREAD

**Issue by wraitii** [starkware-libs/cairo#4030]
# Bug Report

**Cairo version:**

2.2.0

**Current behavior:**

Destructuring structs is currently formatted as such:
```
let SomeStruct{a,
b,
c,
.. } =
    thestruct();
```

While this is a little funny, it's also quite broken.

**Expected behavior:**

I would expect something saner, at least more like 
```
let SomeStruct{
    a,
    b,
    c,
    ..
} = thestruct();
```

**Comment by orizi** [comment]
fixed on main.
