### ISSUE TITLE
feat: remove unused import with scarb fmt

### ISSUE THREAD

**Issue by rcatalan98** [starkware-libs/cairo#4033]
# Feature Request

Automatically removed unused import with `scarb fmt`

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [x ] No

**Comment by mkaput** [comment]
I don't think this should be the job of the formatter. The principle of formatters is that they do not change code semantics. I believe we rather need to have a compiler lint for unused deps & a fixer app (callable as `scarb fix` by end users).

**Comment by rcatalan98** [comment]
> I don't think this should be the job of the formatter. The principle of formatters is that they do not change code semantics. I believe we rather need to have a compiler lint for unused deps & a fixer app (callable as `scarb fix` by end users).

Makes sense probably like what we have in Rust with Clippy, with just a warning that could be introduced in the CI.

**Comment by orizi** [comment]
Closing - as currently there is no relevant tool for that - closing for the time being.
(as this will obviously be one of the aims of such an analyzer)
