### ISSUE TITLE
feat: bitwise operations on `felt252`

### ISSUE THREAD

**Issue by enitrat** [starkware-libs/cairo#4044]
# Feature Request

**Describe the Feature Request**

While direct usage of felt252 is discouraged, additional operations on this type would enable more optimal storage packing in Cairo contracts.

Specifically, implementing division and bitwise operations for felt252 would allow developers to pack values into the full 251 bits that a Starknet storage slot provides. It is already possible to do so by casting to u256, but it might not be efficient.

**Describe Preferred Solution**
An implementation of `Div` and `BitAnd` for `felt252`

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by orizi** [comment]
felt252 should not support any of these actions.
it isn't a binary structure or an integer.

**Comment by Th0rgal** [comment]
> felt252 should not support any of these actions. it isn't a binary structure or an integer.

This makes sense, but for other binary operations like unsigned_div_rem we have an equivalent binary type (u128) supporting what used to be possible before. According to the code documentation of bitwise operations in Cairo 0 the binary type is a 251 bits integer: https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/cairo/common/bitwise.cairo

Would it be possible to add a `u251`? A binary type both cheap in storage and computation?

**Comment by orizi** [comment]
we may have such type at some point (bytes31, which is somewhat similar, already exists) but no current plans without specific performance issues.
