### ISSUE TITLE
feat: Prevent Language Server from importing traits included to prelude

### ISSUE THREAD

**Issue by enitrat** [starkware-libs/cairo#4047]
# Feature Request

**Describe the Feature Request**

Using the Language Server with its autocomplete features will automatically add the required imports. However, it is no longer relevant for all std methods post release 2.2.0, as some of them are now included in the prelude. 

![image](https://github.com/starkware-libs/cairo/assets/60658558/d918c5ac-bf47-438b-9d4f-9d305a4b9486)

Pressing "enter" here would autocomplete with `into()` and add the `core::traits::Into` import. This import is no longer required.

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by orizi** [comment]
Fixed at 2.7.1.
