### ISSUE TITLE
feat: Implement `Default` for `ContractAddress` to Simplify Struct Initialization

### ISSUE THREAD

**Issue by ametel01** [starkware-libs/cairo#4057]
# Feature Request

**Additional Context**
In the [satoru repository](https://github.com/keep-starknet-strange/satoru/tree/main), initialising large custom structs with a default empty value is cumbersome when any of the fields is of type `ContractAddress`. Currently, a bespoke `Default` implementation is required for each struct that includes a `ContractAddress` field.

Implementing `Default` for `ContractAddress` would simplify this process significantly, allowing us to leverage the `#[derive(Default)]` attribute directly in the struct declarations.

I acknowledge there could be specific reasons for not having a `Default` implementation on `ContractAddress`, but implementing it would streamline struct initialisation.

**If the feature request is approved, would you be willing to submit a PR?**
- [x] Yes
- [ ] No

**Comment by orizi** [comment]
I generally don't really like having a default for something with a value where the default itself is not really usable.
If you still really want it note that you CAN do the following:
have some module with this impl:
`custom_defaults.cairo`:
```
impl ContractAddressDefault of Default<ContractAddress> {
     fn default() -> ContractAddress {
          contract_address_const::<0>()
     }
}
```

and doing:
`impl ContractAddressDefault = custom_defaults::ContractAddressDefault;`
before your type that has this default.
```
#[derive(Default)]
struct Foo {
    a: ContractAddress,
}
```
