### ISSUE TITLE
feat: bracketless `break` expressions in match arms

### ISSUE THREAD

**Issue by delaaxe** [starkware-libs/cairo#4078]
# Feature Request

**Describe the Feature Request**

Use blockless `break` or `return` expressions in match arm.

**Describe Preferred Solution**

Currently this valid rust code throws the compile error "Unsupported feature" because of the missing brackets around `break`:

```rust
loop {
    match arr.pop_front() {
        Option::Some(item) => self.append(item),
        Option::None => break,
    };
}
```

Shoud also work with expressions:

```rust
let x = loop {
    match arr.pop_front() {
        Option::Some(item) => state = state.update(item),
        Option::None => break state.finalize(),
    };
}
```

**Additional Context**

Same issue with `return`. I can help implement this if someone points me in the right directions.

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [X] Yes
- [ ] No

**Comment by orizi** [comment]
Added another option - as we are not sure if we want to allow return, break and continue as proper expressions.
maybe just a single line format is enough to remain short.

**Comment by delaaxe** [comment]
> as we are not sure if we want to allow return, break and continue as proper expressions.

Curious about what's causing the uncertainty?

**Comment by orizi** [comment]
it allows weird statements such as `if { return 5 }` (without the `;`) just for the just a little bit nicer formatting in match arms.
adding new syntax is easier than disallowing old syntax, so this is probably preferable for now (enforcing the braces, but allowing them to be a single line in the formatting of a match arm.

**Comment by delaaxe** [comment]
couldn't this work with a "whitelist" approach where break/return expressions would *only* be allowed in match expressions (and any other places they're currently allowed in)?

**Comment by orizi** [comment]
this sort of mix and match between in what context these sort of things is allowed has a good chance to create unexpected edge-cases, and if the benefit is not large i'm not really in favor of doing that (after the formatter change, it no longer adds lines)
