### ISSUE TITLE
bug: Incorrect parsing of bitwise not operation on integers

### ISSUE THREAD

**Issue by uponah** [starkware-libs/cairo#4111]
**Cairo version:**

commit: 245fd510608989e73936ec52f3dffd471aa1b50f

**Current behavior:**

I find in the [Appendix B](!https://book.cairo-lang.org/appendix-02-operators-and-symbols.html) of Cairo documentation that Cairo supports bitwise not operation, `!`, on integers. However, in reality, Cairo incorrectly parses the `!` operator on integers as the not operation on booleans.

For example, the following code would fail to compile:

```rust
fn main() {
    let t: u32 = !3;
}
```

```text
error: Trait has no implementation in context: core::traits::Not::<core::integer::u32>
 --> bit_not.cairo:2:18
    let t: u32 = !3;
                 ^^

Error: failed to compile: bit_not.cairo
```

**Expected behavior:**

The `!` operator should be parsed as the bitwise not operation on integers.

**Steps to reproduce:**

Save error-triggering code into `[your_file_name].cairo`, and run `cairo-run --single-file [your_file_name].cairo`.

**Related code:**

```rust
fn main() {
    let t: u32 = !3;
}
```

**Other information:**

**Comment by orizi** [comment]
this should not compile - `3` isn't boolean.
you maybe mean `~3`.
