### ISSUE TITLE
feat: compile to ir

### ISSUE THREAD

**Issue by HappyTsing** [starkware-libs/cairo#4131]
# Feature Request

I'm currently attempting some static analysis on Cairo contracts. May I ask if you provide any tools for compiling them into an intermediate representation like an AST? I'm frustrated to find that there doesn't seem to be a readily available tool for this.

**Comment by orizi** [comment]
As @mkaput said - the builtin tools are the compiler crates - in particular - you probably want to use the crates:
`cairo-lang-parser` - provides a salsa db for queries on the syntax model of cairo.
`cairo-lang-semantic` - provides a salsa db for queries on the semantic model of cairo.
