### ISSUE TITLE
bug: unable to use bool as value in Felt252Dict

### ISSUE THREAD

**Issue by Th0rgal** [starkware-libs/cairo#4132]
# Bug Report

**Cairo version:** 2.2.0

**Current behavior:**
From my understanding of the cairo-book we can build a Dict with felt252 keys and any type for values, but when I try to use bool (for example) as values, it doesn't work:
This code runs smoothly:
```rs
let mut circular_lock: Felt252Dict<felt252> = Default::default();
```
But this one crashes
```rs
let mut circular_lock: Felt252Dict<bool> = Default::default();
```
Here is the log from scarb:
```
     Running cairo-test referral
testing referral ...
thread 'main' panicked at 'Got failure while specializing type.: TypeSpecialization { type_id: GenericTypeId("Felt252Dict"), error: UnsupportedGenericArg }', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cairo-lang-sierra-generator-2.2.0/src/db.rs:197:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process did not exit successfully: exit status: 10
```

**Steps to reproduce:**
```
git clone git@github.com:starknet-id/referral_contract.git
cd referral_contract
git checkout acf032a9132052505b42a0a7cfe6ab7198c41769
scarb fetch
scarb test
```

**Other information:**
``circular_lock`` is defined line 131 of ``referral.cairo``
It is tested in `scr/tests/test_referral.cairo` line 368 in test ``test_add_rec_circular_commission``

**Comment by orizi** [comment]
Released in 2.4.0-rc* releases.
