### ISSUE TITLE
feat: Account - __validate_deploy__ error

### ISSUE THREAD

**Issue by gaetbout** [starkware-libs/cairo#4136]
# Feature Request

**Describe the Feature Request**

When creating an account, the constructor and the fn `__validate_deploy__` must have matching ending parameters:
```rust
    fn constructor(ref self: ContractState, param_a: ClassHash, param_b: Array<felt252>);
    fn __validate_deploy__(self: @ContractState, class_hash: felt252, contract_address_salt: felt252, param_a: ClassHash, param_b: Array<felt252>);
```
But this isn't enforced anywhere but in the protocol, so whenever the contract is deployed it'll be bricked anyway.

**Describe Preferred Solution**

When building an account that has both a constructor and a `__validate_deploy__` fn AND the parameters aren't matching, it shouldn't be possible to build that contract, with an error in the LSP?

**Additional Context** before finding out what the issue was

Caused me to debug my contract for quite some time.

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by orizi** [comment]
Attached PR should solve the issue.
