### ISSUE TITLE
feat: Skip formatting for single line

### ISSUE THREAD

**Issue by delaaxe** [starkware-libs/cairo#4159]
# Feature Request

**Describe the Feature Request**

Either `#[rustfmt::skip]` or something equivalent to it. Main use case is autoformatted long vertical arrays of data.

- [X] Yes
- [ ] No

**Comment by orizi** [comment]
* Requires adding the ability for attributes on statements (currently only available on items) at the parser level.
* Requires reading these in the formatter (which currently is only aware of the syntax nodes and the length of currently generated line) - and adding ability to tell all data under a certain node to have no formatting handling.
* Probably also blocking unsupported such attributes (so the only statement attribute that won't cause a diagnostic would be this one).

**Comment by delaaxe** [comment]
thanks, would it be easier with a comments-based approach?

**Comment by orizi** [comment]
meaning that this annotation would be in the comment?
It sounds more sensible to have this as an attribute IMO.

**Comment by delaaxe** [comment]
agree with your point. this is a bit too involved for me to do as a first PR. instead could you give me pointers to fix formatting of this:

```diff
-    let TxInfo{transaction_hash, signature, .. } = get_tx_info().unbox();
+    let TxInfo { transaction_hash, signature, .. } = get_tx_info().unbox();
```

**Comment by orizi** [comment]
Sorry - didn't see that one - on the first part we have work on the way solving it.
Guidance wise - `crates/cairo-lang-formatter/src/node_properties.rs` has many functions describing where to add or remove spaces.

You'd want to edit the parser tests at `crates/cairo-lang-parser/src/parser_test_data/cairo_test_files/test1.cairo` to add an expression of this type - and see the resulting actual syntax tree - and decide to update the particular nodes acordingly. (in the node_properies.rs file)

**Comment by gilbens-starkware** [comment]
Done in #4387

**Comment by 0xNeshi** [comment]
This is very useful, there should really be a mention of this somewhere in the docs. If there is, I couldn't find either on [Scarb documentation](https://docs.swmansion.com/scarb/docs/guides/formatting.html) or in [The Cairo book](https://book.cairo-lang.org/appendix-06-useful-development-tools.html?highlight=format#automatic-formatting-with-scarb-fmt) or on [cairo-lang.org](https://docs.cairo-lang.org/)
