### ISSUE TITLE
bug: `storage_base_address_from_felt252` has unexpected behaviors

### ISSUE THREAD

**Issue by enitrat** [starkware-libs/cairo#4187]
# Bug Report

**Cairo version:**
2.3.0-rc0

**Current behavior:**
The StorageBaseAddress types is defined as 
`/// Type for Starknet storage base address, a value in the range [0, 2 ** 251 - 256).`

How can the `storage_base_address_from_felt252` function return `StorageBaseAddress` instead of `Option<StorageBaseAddress>` given that a felt252 can be higher than the max `StorageBaseAddress` ?

After running some tests it looks like the values are truncated if they overflow and I'm not sure how. I find it a bit weird given that `storage_address_try_from_felt252` returns an `Option<StorageAddress>`

**Expected behavior:**
`storage_base_address_from_felt252` returns an `Option<T>` and `None` if the value overflows.

**Steps to reproduce:**
Run the following code

```rust
use starknet::{
    StorageBaseAddress, storage_base_address_from_felt252, storage_address_from_base,
    storage_address_to_felt252, storage_address_try_from_felt252, StorageAddress
};
use debug::PrintTrait;

#[test]
fn test_conversion() {
    let felt_max = 0x800000000000011000000000000000000000000000000000000000000000000;
    let storage_base_felt_max = storage_base_address_from_felt252(felt_max);
    let result = storage_address_from_base(storage_base_felt_max);
    Into::<StorageAddress, felt252>::into(result).print();
    // Result is 0x11000000000000000000000000000000000000000000000100. Where is this number from?

    let storage_address_max: felt252 =
        0x7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff;
    let storage_base_storage_address_max = storage_base_address_from_felt252(storage_address_max);
    let result = storage_address_from_base(storage_base_storage_address_max);
    Into::<StorageAddress, felt252>::into(result).print();
    // Result is 0xff. Where is this number from?

    let storage_address_max: StorageAddress = storage_address_try_from_felt252(storage_address_max)
        .unwrap();
    Into::<StorageAddress, felt252>::into(storage_address_max).print();
    // Result is 0x7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff; which is the expected one.
}
```

**Related code:**

**Other information:**

**Comment by orizi** [comment]
the input for storage_base_address_from_felt252 is expected to be the result of a hash.
therefore it cannot be bound to the range [0, 2**251 - 256).
so this function `always works for any felt` - and returns the number normalized into the range [0, 2**251 - 256). (`x % (2**251 - 256)`)
