### ISSUE TITLE
feat: implement `unwrap_or` in the OptionTrait

### ISSUE THREAD

**Issue by Eikix** [starkware-libs/cairo#4196]
# Feature Request

**Describe the Feature Request**

Hey all! 
Following this conversation on Kakarot, https://github.com/kkrt-labs/kakarot-ssj/pull/322#issuecomment-1746103394
We wanted to see if it's possible to incorporate a `unwrap_or` method in the OptionTrait.

## Describe Preferred Solution

Add one function in the OptionTrait:
`unwrap_or`

pseudo code:

```
fn unwrap_or(self: Option<T>, default: T) -> T {
    match self {
        Option::Some(x) => x,
        Option::None => default,
    } 
}
```

## Additionally, I can implement `unwrap_or_default`

```
fn unwrap_or_default<+Default<T>>(self: Option<T>) -> T {
    match self {
        Option::Some(x) => x,
        Option::None => Default::default(),
    } 
}
```

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by orizi** [comment]
feel free to open a PR - sounds good.

**Comment by Eikix** [comment]
Okay opening a PR soon (tm)
