### ISSUE TITLE
feat: public `Zero` and `One`traits

### ISSUE THREAD

**Issue by enitrat** [starkware-libs/cairo#4236]
# Feature Request
Following the discussion in #4037, I propose to implement the `Zero` and `One` traits to be used externally.
An implementation of `One` has already been proposed in #3891 but there haven't been any updates for a few months.

**Describe the Feature Request**

Therefore, I propose to continue the work and to create a `num/traits` dir, and add the `Zero` and `One` traits. 

**Describe Preferred Solution**
These traits would have an impl generic over `T, +Oneable<T>` and `T, +Zeroable<T>` to avoid code duplication - and for the types that don't implement `Oneable` or `Zeroable` like `felt252`, we can write custom impls.

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by orizi** [comment]
`Oneable` was an internal trait for secp implementation - it was not to be exported out, it should not be further exported by having defaults implemented using it.
It CAN be auto implemented from `One` if possible.

**Comment by enitrat** [comment]
Okay, then I will do it this way 👍
