### ISSUE TITLE
feat: Implementation of the `SizeOf<T>` trait

### ISSUE THREAD

**Issue by akhercha** [starkware-libs/cairo#4245]
# Feature Request

**Describe the Feature Request**

Introduction of a `SizeOf<T>` trait designed to retrieve the size in bits of various data types. 

**Describe Preferred Solution**

```rust
trait SizeOf<T> {
    /// Returns the size in bits of T. 
    fn size() -> T;
    /// Returns the size in bits of Self.
    fn size_of(self: @T) -> T;
}

impl U8SizeOf of SizeOf<u8> {
    fn size() -> u8 {
        8
    }
    fn size_of(self: @u8) -> u8 {
        U8SizeOf::size()
    }
}
```

After implemented for `u8` for example, it would be then:

```rust
assert(10_u8.size_of() == 8, 'should be 8');
// or
assert(U8SizeOf::size() == 8, 'should be 8');
```

**Related Code**

Implemented in [Kakarot::utils::num](https://github.com/kkrt-labs/kakarot-ssj/blob/main/crates/utils/src/num.cairo) for [PR #410](https://github.com/kkrt-labs/kakarot-ssj/pull/410)

The usage was:
```rust
fn shl(self: T, shift: T) -> T {
        if shift > shift.size_of() - One::one() {
            panic_with_felt252('mul Overflow');
        }
        (...)
    }
```

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**

- [X] Yes
- [ ] No

**Comment by orizi** [comment]
this is not "size" - this might be "representation bits" - "size" implies the size in memory.
but asside from that sounds fine.
