### ISSUE TITLE
bug: CASM runner assigns arbitrary contract addresses instead of using correct address computation

### ISSUE THREAD

**Issue by enitrat** [starkware-libs/cairo#4375]
# Bug Report

**Cairo version:**
2.3.1

**Current behavior:**
Currently, the casm runner assigns arbitrary addresses to contracts deployed using `deploy_syscall`, incrementing them from 0.
https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-runner/src/casm_run/mod.rs#L947-L948

**Expected behavior:**
The contract addresses should be calculated according to the specifications.
```js
contract_address := pedersen(
    “STARKNET_CONTRACT_ADDRESS”,
    deployer_address,
    salt,
    class_hash,
    constructor_calldata_hash)
```

**Other information:**
### Why this matters

> this sole thing is blocking the UDC migration to cairo 1+

> It prevents us from testing anything relying on computation of starknet addresses

I am willing to try to submit a PR if this is accepted.

**Comment by orizi** [comment]
If these are the specifications - feel free to open a PR.
Make sure to include a test.

**Comment by enitrat** [comment]
@orizi am I allowed to use the `calculate_contract_address` function from the `starknet_api` crate? Or do you not want dependencies external to the compiler? In any case, I need access to pedersen hash which is available in `starknet-crypto`. But the easiest would just be to use the battle-tested `calculate_contract_address`.

**Comment by orizi** [comment]
Generally - yes, but my issue there is that that crate is dependent on a cairo-lang-starknet crate, which introduces a cyclic dependency.
