### ISSUE TITLE
feat: source map

### ISSUE THREAD

**Issue by HappyTsing** [starkware-libs/cairo#4412]
Hello, I would like to know how to retrieve the line number in the source code corresponding to the Sierra intermediate representation code. Is there currently support for this functionality?

**Comment by mkaput** [comment]
@cptartur is pondering about this AFAIR

**Comment by cptartur** [comment]
A feature like that does not exist atm. We are currently investigating a contribution that would allow doing so, but we have no timeline. Don't think Starkware themselves are working on anything like that. 

cc @MaksymilianDemitraszek

**Comment by HappyTsing** [comment]
> A feature like that does not exist atm. We are currently investigating a contribution that would allow doing so, but we have no timeline. Don't think Starkware themselves are working on anything like that.
> 
> cc @MaksymilianDemitraszek

If I want to implement this feature for the Cairo compiler, do you have any suggestions? Could you provide a simple outline?

**Comment by MaksymilianDemitraszek** [comment]
We have recently started working on implementing this

**Comment by HappyTsing** [comment]
> We have recently started working on implementing this

Awesome, looking forward to it!!!

**Comment by orizi** [comment]
it now exists in code, our internal profiling tool is an example.
