### ISSUE TITLE
feat: `unbox_snapshot` to unbox `Box<T>` into `@T`

### ISSUE THREAD

**Issue by enitrat** [starkware-libs/cairo#4425]
# Feature Request

**Describe the Feature Request**

A libfunc/corelib function to unbox a `Box<T>` type into a `@T` type. This would allow us to not take ownership of the value inside the box when unboxing it, and would avoid unnecessary unbox-rebox operations when accessing a field of the `T` type without modifying it.

**Describe Preferred Solution**

A libfunc similar to `match_nullable_snapshot` - that converts a `Box<T>` to a `@T`.

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

I can try myself at it with some guidance

- [x] Yes
- [ ] No

**Comment by orizi** [comment]
I think instead adding a: `extern fn box_forward_snapshot<T>(value: @Box<T>) -> Box<@T>;` would be better (less actual logic).
same for: `extern fn nullable_forward_snapshot<T>(value: @Nullable<T>) -> Nullable<@T>;` - this can probably replace `match_nullable_snapshot` as well.
I'm wondering if having the opposite as well would be beneficial.

**Comment by enitrat** [comment]
> I'm wondering if having the opposite as well would be beneficial.

I don't see any specific use case for this. Do you mean `@T` into `Box<T>`?

**Comment by orizi** [comment]
no - just instead of forwarding the snapshot pulling it backwards - i indeed don't see a particular usecase.
