### ISSUE TITLE
bug: Out-of-memory (OOM) panic in Sierra deserialization leads to denial-of-service (DoS)

### ISSUE THREAD

**Issue by pventuzelo** [starkware-libs/cairo#4427]
# Out-of-memory (OOM) panic in Sierra deserialization leads to denial-of-service (DoS)

Author(s): @Fuzzinglabs (Darius & Patrick)

## Executive Summary
An attacker can cause a DoS on a node that processes Starknet contracts by sending a serialized Sierra program causing the crash. This is due to missing sanitization/verification of vector size before calling `Vec::with_capacity(size)` in `Program::deserialize`.

## Vulnerability Details

- **Severity:** Critical
- **Affected Component:** cairo/crates/cairo-lang-starknet
- **Commit:** fccf41a8ff259c437f16a6d351df8593de48b8a3

## Steps to reproduce
Compile to following
```rust
  let serialized_program: Vec<BigUintAsHex> = vec![
      BigUintAsHex {
          value: BigUint::from_str("1000000000000000000").unwrap(),
      },
      BigUintAsHex {
          value: BigUint::from_str("1000000000000000000").unwrap(),
      },
  ];

  Program::deserialize(&serialized_program);
```

## Root Cause Analysis

When deserializing vectors, the `deserialize` function first reads the length and then tries to allocate a vector with the supplied length. Passing a length that's too big causes the allocation to fail which will result in a crash.

https://github.com/starkware-libs/cairo/blob/fccf41a8ff259c437f16a6d351df8593de48b8a3/crates/cairo-lang-starknet/src/felt252_serde.rs#L370

## Detailed Behavior
```
thread 'main' panicked at library/alloc/src/raw_vec.rs:534:5:
capacity overflow
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: alloc::raw_vec::capacity_overflow
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/raw_vec.rs:534:5
   3: alloc::raw_vec::RawVec<T,A>::allocate_in
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/raw_vec.rs:177:27
   4: alloc::raw_vec::RawVec<T,A>::with_capacity_in
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/raw_vec.rs:130:9
   5: alloc::vec::Vec<T,A>::with_capacity_in
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/vec/mod.rs:670:20
   6: alloc::vec::Vec<T>::with_capacity
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/vec/mod.rs:479:9
   7: <cairo_lang_sierra::program::Program as cairo_lang_starknet::felt252_serde::Felt252Serde>::deserialize
             at /home/fuzzinglabs/Documents/cairo/crates/cairo-lang-starknet/src/felt252_serde.rs:370:37
   8: sierra_serialization::main
             at ./src/main.rs:28:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Recommendations

The `deserialize` function could check if the supplied vector length makes sense when compared to the program size and output an error result if it doesn't.

Additionally, this pattern of `Vec::with_capacity(size)` without checking the `size` value seems used multiple times in the code:
- https://github.com/starkware-libs/cairo/blob/fccf41a8ff259c437f16a6d351df8593de48b8a3/crates/cairo-lang-starknet/src/felt252_serde.rs#L382
- https://github.com/starkware-libs/cairo/blob/fccf41a8ff259c437f16a6d351df8593de48b8a3/crates/cairo-lang-starknet/src/felt252_serde.rs#L393

**Comment by orizi** [comment]
Fix PR merged - will be released at the next 2.4.0-rc4 or 2.4.0 release (whatever comes first)
