### ISSUE TITLE
feat: add codespell linter job for CI

### ISSUE THREAD

**Issue by shuoer86** [starkware-libs/cairo#4434]
# Feature Request

Add codespell  linter job for CI.

**Why**

1. There are many pull requests If you search for "fix typo".

2. It’s ultimately important to spell quality correctly when your role is in QA. It’s worth being vigilant for errors of any kind, from spelling to dead links to scripting issues. Sometimes, we will bring in bugs even crash because of typo error.

3. So we can't ignor the "fix typo" pull requests. 

**Describe Preferred Solution**

imo, add codespell linter job for CI will be a good solution.

**Comment by orizi** [comment]
Fixed in linked PR.

**Comment by shuoer86** [comment]
@orizi wow! Glad to see you add workflow in CI so quickly. Thank you very much.
