### ISSUE TITLE
bug: compiler unable to compile returns in all match arms

### ISSUE THREAD

**Issue by enitrat** [starkware-libs/cairo#4440]
# Bug Report

**Cairo version:**
2.4.0-rc2

**Current behavior:**
When using if-elses, i can perfectly do the following where the compiler is able to recognize that each branch contains a return statement, and that the function correctly returns the expected type in each branch.

```rust
fn functioning_if(input: Option<usize>) -> usize {
    if input.is_some() {
        return input.unwrap();
    } else {
        return 0;
    }
}
```

However, the equivalent doesn't work for match arms:
```rust
fn bugged_match(input: Option<usize>) -> usize {
    match input {
        Option::Some(val) => { return val; },
        Option::None => { return 0; }
    };
}
```

```
error: Unexpected return type. Expected: "core::integer::u32", found: "()".
 --> /Users/me/workspace/match_return/src/lib.cairo:5:48
fn bugged_match(input: Option<usize>) -> usize {
                                               ^
```

Naturally - I was thinking about adding one extra return statement after the match statement to clear this bug and                                                
```rust
fn bugged_match(input: Option<usize>) -> usize {
    match input {
        Option::Some(val) => { return val; },
        Option::None => { return 0; }
    };
    return core::panic_with_felt252('shouldnt ever happen');
}
```

But the compiler prevents me from compiling this - saying it's unreachable code. Which is true! But then, it should also be detected that without this extra return statement, the function correctly returns from all match arms. 

```shell
error: Unreachable code
 --> /Users/me/workspace/match_return/src/lib.cairo:10:5
    return core::panic_with_felt252('unreachable');
    ^*********************************************^
```

**Expected behavior:**
The function compiles correctly.
```rust
fn bugged_match(input: Option<usize>) -> usize {
    match input {
        Option::Some(val) => { return val; },
        Option::None => { return 0; }
    };
}
```

**Comment by orizi** [comment]
fast solve - remove `;`:
```
fn bugged_match(input: Option<usize>) -> usize {
    match input {
        Option::Some(val) => { return val; },
        Option::None => { return 0; }
    }
}
```

**Comment by enitrat** [comment]
> fast solve - remove ;:

Ah, indeed... I just noticed that my example for if statements is not equivalent because of the `;` but I don't understand the reason behind. Why would this not work if you add a `;`?

**Comment by orizi** [comment]
the `;` means it is a statement - so its type is unit.
