### ISSUE TITLE
feat: support upcast for arrays/span types

### ISSUE THREAD

**Issue by enitrat** [starkware-libs/cairo#4458]
# Feature Request

**Describe the Feature Request**

Add `upcast` support to the `Array/Span` types, to cast `Array<T>` into `Array<U>`, where T implements upcast to U.

This would make it possible to convert, for example, `Span<u8>`  to `Span<felt252>` for "free" when returning data from a function call to the expected return data of the `__execute__` function in Account Contracts.

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

I can try myself at it with proper guidance
- [x] Yes
- [ ] No

**Comment by orizi** [comment]
Cannot be supported - will break the concept of future compatibility.
Let us assume there is such a function.
Currently - Array<u32> is Array<felt252> under the hood - so the conversion will work.
In the future - we may have felt64 as the basic element. u32 will be a felt64 - but felt252 will be 4 such felts.
The cast won't be possible.

**Comment by delaaxe** [comment]
And what if the cast is not to the field element but to another range checked uint?

**Comment by orizi** [comment]
What does it change?
An array of u8s and an array of u16s may have completely different underlying representation.
