### ISSUE TITLE
bug:  gas gives unexpected results for values bigger than 64 bits 

### ISSUE THREAD

**Issue by mariari** [starkware-libs/cairo#4481]
# Bug Report

**Cairo version:**

```bash
scarb --version
scarb 2.3.1 (0c8def3aa 2023-10-31)
cairo: 2.3.1 (https://crates.io/crates/cairo-lang-compiler/2.3.1)
sierra: 1.3.0

```
**Current behavior:**
Using a 65 bit number or higher causes `scarb test` to give unexpected results for what the gas ought to be. Using a 64 bit number failure to cast

```bash
testing hello ...
running 1 tests
test hello::tests::it_works ... fail (gas usage est.: 3570)
failures:
   hello::tests::it_works - panicked with [375233589013918064796019 ('Out of gas'), ].

Error: test result: FAILED. 0 passed; 1 failed; 0 ignored
```

**Expected behavior:**

Either crash like the 64 bit version of accept numbers up until 252 bits.

**Steps to reproduce:**
```bash
scarb test
```
**Related code:**

```cairo
fn fib_rec(n: felt252, a: felt252, b: felt252) -> felt252 {
    if n == 0 {
      a
    } else {
      fib_rec(n- 1, b, a + b)
    }
}

fn fib_two(n: felt252) -> felt252 {
  fib_rec(n, 0, 1)
}

#[cfg(test)]
mod tests {
    use super::{fib_two, fib_rec};
    use debug::PrintTrait;

    #[test]
    #[available_gas(18446744073709551616)]
    fn it_works() {
        // fib_rec(10000, 0, 1).print();
        assert(fib_rec(10000, 0, 1) == 0x1ccaa6fc56480d962e6ad1673137a6b4e7baa6cfeb244fc545d22fdc05f5889, 'it works!');
    }
}
```

If you want to test the overflow then just write this instead

```rust
    #[available_gas(18446744073709551615)]
```

it overflows for any number bigger than `9223372036854775807` which is
```lisp
(1- (expt 2 63))
```

**Other information:**

**Comment by orizi** [comment]
numbers over `18446744073709551615` are not supported at main (with a diagnostic) and at 2.4.0-rc* releases in any case.

In both you can also not provide `#[available_gas(...)]` and it would work (just automatically supplies a large amount of gas).
