### ISSUE TITLE
feat: 

### ISSUE THREAD

**Issue by programmistvdzinsahirybashke** [starkware-libs/cairo#4531]
# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by orizi** [comment]
no input - assuming a mistake.
