### ISSUE TITLE
bug: `panic_with_felt252()` fails when used with a `felt252` cast from `ContractAddress`

### ISSUE THREAD

**Issue by boyuanx** [starkware-libs/cairo#4533]
# Bug Report

**Cairo version:**
2.3.1

**Current behavior:**
When using a `felt252` cast from `ContractAddress` with `panic_with_felt252()`, the panic fails with the following message:
```
thread 'tokio-runtime-worker' panicked at crates/cheatnet/src/rpc.rs:88:55:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[ERROR] task 12 panicked
```

**Expected behavior:**
The panic should panic properly and display the input `felt252` value.

**Steps to reproduce:**
Convert any `ContractAddress` into `felt252` and pass it into a `panic_with_felt252()`.

**Related code:**

```
fn test(ref self: ContractState, sender: ContractAddress) {
  let felt252Sender: felt252 = sender.into();
  panic_with_felt252(felt252Sender); // This will throw the above error
}
```

**Other information:**
The offending function is triggered during testing with `snforge`.

**Comment by orizi** [comment]
Can you add more context? I can't seem to recreate this bug with just this info.

**Comment by orizi** [comment]
I've just noticed you've run this using `snforge`  - you should probably open the bug there https://github.com/foundry-rs/starknet-foundry/issues - as this panic is generated in their code.

It is possible you can fix this in the mean time with an addition of:
`#[available_gas(10000000)]` for the specific testcase - but that is just a guess.
