### ISSUE TITLE
feat: improve consteval_int

### ISSUE THREAD

**Issue by gaetbout** [starkware-libs/cairo#4544]
# Feature Request

**Describe the Feature Request**

At the moment `consteval_int!(...);` only allows simple calculus (+, -, *, /)

It would be handy if it would allow:
```rust
const a: felt252 = consteval_int!(12 ** 2); // pow
const b: felt252 = consteval_int!(a * 2); // Referencing other constants
```

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by milancermak** [comment]
+1 on supporting `**` - it's very useful in the context of DeFi when dealing with tokens with 18 decimals (like eth). For example, we have to write 1000000000000000000 to declare 1 ETH which is error prone and adding or removing a zero in that constant can have disastrous consequences. Being able to do `consteval_int!(10 ** 18)` is way better.

**Comment by orizi** [comment]
we are not planning on supporting ** as an operator, `.pow` may be supported. (relevant rust matching discussion https://github.com/rust-lang/rfcs/issues/3047)
Referencing of other constants is going to be much more difficult - and completely out of scope for this macro.
When supported - it would probably remove the need for the consteval macro completely (as it is a placeholder while it does not exist).
In general - better const support is on the way.

**Comment by orizi** [comment]
const referencing other consts is now supported on 2.6.0, no need for consteval.
a const power function may be available in the further future.
