### ISSUE TITLE
Dummy recursive function costs 4x more than it should

### ISSUE THREAD

**Issue by feltroidprime** [starkware-libs/cairo#4635]
I deployed a cairo 1 contract here https://starkscan.co/contract/0x005bd7b20689b902f7641cc4b187fe088a95cee38c914c86d703f1412e634c7a#read-write-contract-sub-write

With the corresponding code : 

![image](https://github.com/starkware-libs/cairo/assets/96737978/ccb3c987-751c-4be2-8de7-4c06de23a82f)

With n=140 000 as input, the [tx](https://starkscan.co/tx/0x36df40f97e734630ab2440a64adde415116a62e35e9737c542f1a1676c7655d) goes to 2.94Million steps + 140 000 range checks, which is 20 steps + 1 RC per iteration.

A few concerns coming from it : 
- Why is there 1 range check per iteration? There shouldn't be any range checks in this function. Checking felt252 == 0 should cost 1 step. 
- Coding the exact same function in Cairo0, it costs precisely 700k steps, which is only 5 steps per iteration. 

![image](https://github.com/starkware-libs/cairo/assets/96737978/485f4c34-4abb-42f7-9bcf-f1850f4295fc)

Can this be improved in cairo1 to sierra to casm somehow ?

**Comment by orizi** [comment]
The rangecheck is from gas checking - not from the felt252 comparison.

**Comment by orizi** [comment]
Main possible improvement would be Loop unrolling to reduce the range checks, and the gas operations in general, which would be a large chunk of the run.

**Comment by feltroidprime** [comment]
> The rangecheck is from gas checking - not from the felt252 comparison.

Thank you for your answer. I get the overhead now. Just seen this https://www.youtube.com/watch?v=wYxUedcdVZ4

**Comment by orizi** [comment]
preliminary test of inlining reduced from the 3M to about 800K.

**Comment by orizi** [comment]
When running this now with `--gas-disabled` we get the desired 700K steps only.
Without it - we still get the expected slowdown, but the factored got reduced X2.
```
    steps: 1540027
    memory holes: 5
    builtins: ("range_check_builtin": 140001)
```

Some loop unrolling reduced the gas counted case dramatically (as all the extra operations are for gas purposes) - but this is not a common usecase currently - so no extra work is done there for the time being.

**Comment by feltroidprime** [comment]
Nice !
