### ISSUE TITLE
bug: LSP called `Result::unwrap()` on an `Err` value: DiagnosticAdded

### ISSUE THREAD

**Issue by milancermak** [starkware-libs/cairo#4637]
# Bug Report

**Cairo version:**

2.3.1

**Current behavior:**

I was looking at the [Starkgate v2.0 code](https://github.com/starknet-io/starkgate-contracts/tree/v2.0). When I open the repo in VS Code, I immediately get the following error in the Output panel:

```text
WARN   /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cairo-lang-language-server-2.3.1/src/lib.rs:351 11:44:41 Failed to find corelib path.
thread 'main' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cairo-lang-semantic-2.3.1/src/corelib.rs:551:51:
called `Result::unwrap()` on an `Err` value: DiagnosticAdded
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Caught panic in LSP worker thread.
thread 'main' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cairo-lang-semantic-2.3.1/src/corelib.rs:551:51:
called `Result::unwrap()` on an `Err` value: DiagnosticAdded
Caught panic in LSP worker thread.
thread 'main' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cairo-lang-semantic-2.3.1/src/corelib.rs:551:51:
called `Result::unwrap()` on an `Err` value: DiagnosticAdded
Caught panic in LSP worker thread.
[Error - 12:44:44] Request textDocument/semanticTokens/full failed.
  Message: Internal error
  Code: -32603 
[Error - 12:44:44] Request textDocument/semanticTokens/full failed.
  Message: Internal error
  Code: -32603 
```

**Expected behavior:**

No error, code highlighting.

**Steps to reproduce:**

Clone the StarkGate repo, use the `a4caa78` commit (`v2.0` tag).

Open e.g. `src/cairo/token_bridge.cairo` in VS Code. The error pops up right away.

**Comment by orizi** [comment]
Does it open in 2.4.0?

**Comment by maciektr** [comment]
Hi @milancermak !
The repo you have mentioned is not a Scarb project - lacks `Scarb.toml` manifest file. This means that the Cairo-LS is unable to obtain corelib from Scarb. You need to provide it manually, by downloading appropriate corelib revision from Cairo github repository, and passing it's path via `cairo1.corelibPath` setting in VSCode. 
https://github.com/starkware-libs/cairo/tree/main/vscode-cairo#corelib-path-resolution

**Comment by orizi** [comment]
If this is unrelated to the Cairo project directly, or no longer happens in newer versions, please close the issue.

**Comment by orizi** [comment]
Closing as to @maciektr response
