### ISSUE TITLE
Gas coupons

### ISSUE THREAD

**Issue by ArielElp** [starkware-libs/cairo#4679]
Today, we cannot create recursive types that depend on non-dropable types. The most noticeable (and probably only) example is `Felt252Dict` which has `Destruct` but not `Drop` (`squash` must be called before the program terminates to guarantee safety).

The problem with types like `Array<Felt252Dict>` or `Felt252Dict<Felt252Dict>` is that we cannot write `Destruct` for them, which is `no_panic` (calling destruct must not panic). The reason is that we must loop over the array and call `squash` in each iteration. To compile, the loop must call the `withdraw_gas` libfunc (to pay for the iteration), which can panic if there is insufficient gas.

Gas coupons allow us to write recursive functions which do not call `withdraw_gas`, thus making types such as `Array<Felt252Dict>` possible to write. The idea is that every function has an associated coupon type, `Foo::Coupon`, alongside new libfuncs for buying the coupon `coupon_buy()-> Foo::Coupon` and `call_with_coupon(..., __coupon: Foo::Coupon)`. The gas cost of `coupon_buy` is the cost of `Foo`, and the gas cost of `call_with_coupon` is constant (hardcoded in the compiler).

The following example shows how we can use the concept of coupons to define `Array<Felt252Dict<T>>`. 

```
type Array<T> = Array<(T, ())>;
type Array<Felt252Dict> = Array<(Felt252Dict, DictArrayDestruct::destruct::Coupon)>

pub impl ArrayImpl<T> of ArrayTrait<T, -Drop<T>> {
    fn append(ref self: Array<T>, value: T) nopanic {
        // here we buy the coupon
    }

    fn pop_front(ref self: Array<T>) -> Option<T> nopanic {
        // here we reimburse for the coupon
    }

}

impl DictArrayDestruct of Destruct<Array<Felt252Dict<u8>> {
    fn destruct(self: Array<Felt252Dict<u8>) {
        match self.pop_front() {
            Option::Some((dict, c)) => {
                dict.squash();
                self.destruct(__coupon = c);
            },
            Option::None => {},
        };
    }
}
```
Note that the basic `Array<T>` becomes an array of pairs, where the second type is a coupon, which is the unit type in cases where we don't care about coupons. The coupon for `Array<Felt252Dict>` is associated with the function `DictArrayDestruct::destruct`. Since the recursive call to destruct is done with the coupon, the compiler knows it does not need to inject a `withdraw_gas` instruction in destruct; the coupon pays for a single iteration of the `destruct` function (note that it does not attempt to cover the price of `dict_squash`, but only that of the loop, the costs for dict squashing is pre-paid on dict operations, i.e. the cost of `dict_squash` is considered to be 0 by the gas solver). By changing the `Array` type always to be an array of tuples and implementing the array trait differently only for none droppable types, we were able to define a none panicking destruct.

**Comment by orizi** [comment]
Coupons are now supported.
What is missing is high level support for a general array of destructible objects.
