### ISSUE TITLE
Adding while loops

### ISSUE THREAD

**Issue by ArielElp** [starkware-libs/cairo#4682]
Today, the language only contains the basic `loop { break(); }` syntax. We want to enrich it with standard loops.

**Comment by ArielElp** [comment]
A prerequisite for nicer loops is having loop representation in "lowered" Cairo (see the cairo-lang-lowering crate), https://github.com/starkware-libs/cairo/pull/4680 does this.

**Comment by edisontim** [comment]
Hey, would like to take this but it's my first issue on the compiler. Feel free to tell me if it's going to be too demanding

**Comment by orizi** [comment]
Released on 2.5.0.
