### ISSUE TITLE
dev: unify the API for `inv_mod` and `u256_inv_mod`

### ISSUE THREAD

**Issue by greged93** [starkware-libs/cairo#4721]
The current return value for `inv_mod` is `Option<T>`, while `u256_inv_mod` returns `Option<NonZero<u256>>`. Suggest to align them together, returning either `Option<NonZero<T>>` or `Option<u256>`.

Below is the return value of both functions:
- `u256_inv_mod`:
https://github.com/starkware-libs/cairo/blob/a666087aca1e614468cfdb8fc681fc0cf588e6b9/corelib/src/math.cairo#L104
- `inv_mod`:
https://github.com/starkware-libs/cairo/blob/a666087aca1e614468cfdb8fc681fc0cf588e6b9/corelib/src/math.cairo#L58

**Comment by orizi** [comment]
The change is caused by the different algorithm underlying both the implementations.
Therefore it isn't going to be unified.
