### ISSUE TITLE
bug: Unable to Pass Multiple Arrays to Struct in Cairo Args Runner

### ISSUE THREAD

**Issue by neotheprogramist** [starkware-libs/cairo#4773]
## Description
There is an issue with **Cairo Args Runner** when trying to pass multiple arrays to a struct. While it works fine with single array or (multiple) values, the runner throws an error when multiple arrays are passed. This issue is particularly noticeable in the `e4_struct_with_arrays` example, where instead of the expected output, an error is encountered.

## Steps to Reproduce
To reproduce this issue, follow these steps:

1. Clone the repository:
   ```bash
   git clone https://github.com/neotheprogramist/cairo-args-runner
   ```
2. Checkout:
    ```bash
    git checkout passing-more-than-one-array-issue
    ```
3. Build the program (optional - only need if any changes):
    ```bash
    cd examples/e4_struct_with_arrays/
    scarb build
    ```
4. Run the program with two arrays:
   ```bash
   echo "[[1, 2, 3], [1, 3, 9]]" | cargo run --release -- examples/e4_struct_with_arrays/target/dev/e4_struct_with_arrays.sierra.json
   ```
   Expected Result: `[6, 13]`
   Actual Result: Error message:
   ```
   ArgumentsSizeMismatch { expected: 1, actual: 2 }
   Error: RunError(FailedRunning)
   ```

## Expected Behavior
The runner should correctly process the input of multiple arrays in a struct and provide the expected output without errors.

## Actual Behavior
When passing more than one array to the struct, the runner throws an `ArgumentsSizeMismatch` error and fails to execute the program correctly.

## Additional Context
The issue seems to arise specifically in the context of struct handling with multiple arrays. This is critical for the usability of the runner in more complex Cairo programs.

## Repository Link
[GitHub Repository - cairo-args-runner](https://github.com/neotheprogramist/cairo-args-runner/tree/passing-more-than-one-array-issue)

**Comment by orizi** [comment]
The runner only supports flat information, which may include some arrays.
In your case, I have no idea how you actually pass the data into this object.
The runner only supports two types of params - which your actual param does not match:
* A simple flat struct (this will also include felt252, u8, u16 and so on)
* An array of flat objects.

**Comment by neotheprogramist** [comment]
@orizi 
The way I pass arguments in code is [here](https://github.com/neotheprogramist/cairo-args-runner/blob/passing-more-than-one-array-issue/src/bin/main.rs#L35-L37).
There are no nested arrays, and the arguments are just vector of Arg enum called [WrappedArgs](https://github.com/neotheprogramist/cairo-args-runner/blob/passing-more-than-one-array-issue/src/utils/args.rs?plain=1#L13).

The thing is that, I was wondering how structs are serialized, and as expected they are just a series of felts that are casted to the specific type.
Such example works well [Cairo Code](https://github.com/neotheprogramist/cairo-args-runner/blob/passing-more-than-one-array-issue/examples/e1_struct_with_values/src/lib.cairo#L14) and I pass to sierra simply a `vec![Arg::Value(1), Arg::Value(2), Arg::Value(3)]` [e1_struct_with_values](https://github.com/neotheprogramist/cairo-args-runner/blob/passing-more-than-one-array-issue/README.md#L28)

Passing many arrays (without wrapping them inside struct) works as well.
[Example Code](https://github.com/neotheprogramist/cairo-args-runner/blob/passing-more-than-one-array-issue/examples/e2_arrays/src/lib.cairo#L8)
[e2_arrays](https://github.com/neotheprogramist/cairo-args-runner/blob/passing-more-than-one-array-issue/README.md?plain=1#L38)

Following the pattern I wanted to do similar thing with arrays in this [example](https://github.com/neotheprogramist/cairo-args-runner/blob/passing-more-than-one-array-issue/examples/e4_struct_with_arrays/src/lib.cairo#L12). Now the input struct has array members instead of felts.
In my opinion passing `vec![Arg::Array(vec![1, 2, 3]), Arg::Array(vec![1, 3, 9])]` should result in working example [e4_struct_with_arrays](https://github.com/neotheprogramist/cairo-args-runner/blob/passing-more-than-one-array-issue/README.md?plain=1#L58) but it panics.

**Comment by orizi** [comment]
Do note this isn't serialization - this is the actual represenstation when runner the CairoVM for Cairo level objects.
This entire structure was only designed to run our tests - therefore only passing flat structs, and arrays of flat args are supported.
Of course other things are possible - but this isn't part of the scope.

**Comment by orizi** [comment]
Found something simple to allow support for this. Linked PR.
