### ISSUE TITLE
feat: --no-gas-limit option for scarb test

### ISSUE THREAD

**Issue by remybar** [starkware-libs/cairo#4824]
# Feature Request

**Describe the Feature Request**

Having a `--no-gas-check` option for `scarb test` which would deactivate gas consumption checking when running a test (whatever the `available_gas` attribute), would allow us to make a test pass before trying to improve gas usage.

Temporary increasing the `available_gas` attribute just to make the test green may be error prone if the original `available_gas` value is not correctly restored.

**Describe Preferred Solution**

A `--no-gas-check` option would be perfect.

**Describe Alternatives**

N/A

**Related Code**

N/A

**Additional Context**

In some challenges, where a test suite is provided and the corresponding code has to be written, this option would be really useful (Hi NodeGuardians ;-) ).

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [X] Yes (I can try to implement it).
- [ ] No

**Comment by maciektr** [comment]
Please note that this issue should be concerned with `cairo-test` rather than `scarb`.

**Comment by remybar** [comment]
> you can just remove the `available_gas` attribute from the test - in the newer version it supplies "infinite" gas.

That's exactly what I want to avoid when I have several failing tests ... Modifying test configuration just to check that the implementation works is not so good as UX I think.

Imagine you want to refactor some part of your code.
First, you want to be sure that the full existing test suite is ok and then you may improve your code to be sure to be as gas efficient as the `available_gas` set for the test. Or you might consider that increasing the `available_gas` value is acceptable compared to code improvements (more modularity, easier to read, whatever ...).

I would accept a lot of reasons to not implement this kind of option but the one you gave me looks strange to me :P

**Comment by orizi** [comment]
I am mostly surprised you have many tests that have `available_gas` on them, as at the beginning the default gas was just never enough for functions that did anything dynamic with gas (loops, recursion and so on) - and this is no longer required - but allowed for cases you want to specifically bound the gas of a test, which I thought was probably a more scarce usecase.

do you really have many such tests?
If it is a common use case, the request here will make more sense for me.

**Comment by orizi** [comment]
It used to be a common practice due to it being a must, but since it isn't required since a few versions ago, most tests should just drop the attribute, and the few that need it will be more explicit.

In our team we only use this attribute when we need the test to have a specific amount of gas available, which happens very rarely.
