### ISSUE TITLE
feat:  Include execution resources usage syscall

### ISSUE THREAD

**Issue by marcellobardus** [starkware-libs/cairo#4888]
# Feature Request

**Feature Request**
Currently the `get_execution_info` syscall provides the following TxInfo:
* `version`
* `account_contract_address`
* `max_fee`
* `signature`
* `transaction_hash`
* `chain_id`
* `nonce`
It does not include the original `resource_bounds` described [here](https://docs.starknet.io/documentation/architecture_and_concepts/Network_Architecture/transactions/#v3_transaction_fields).

**Preferred Solution**
It would be great to have the possibility to access this information with the syscall and also the current usage of these resources similarly to `gasleft` in solidity.

**Comment by orizi** [comment]
It actually does now.
There are now a `v2` version of the syscall `get_execution_info_v2_syscall`.
If you call `starknet::info::get_execution_info` you get the latest struct.
