### ISSUE TITLE
bug: One of the arguments does not match the expected type of the libfunc or return statement.

### ISSUE THREAD

**Issue by enitrat** [starkware-libs/cairo#4937]
# Bug Report

**Cairo version:**
2.5.0

**Current behavior:**
The following code snippet fails with 
```
Error: #7: One of the arguments does not match the expected type of the libfunc or return statement.
```
```rust
fn main() {
    loop {
        println!("again!");
    }
}
```

**Expected behavior:**
Either this should compile and run fine, or the error message should be more adapted to the error.
I know it doesn't make any sense to run this but it's purely informative.

**Comment by orizi** [comment]
The fix is only applicable when we stop trying to solve gas variables in the old style - so it will only be fixed on 2.6.0 release (which is the next sierra release).
Fixed merged into the branch that will be there.
