### ISSUE TITLE
bug: Variable Id { idx: 23 } was already renamed

### ISSUE THREAD

**Issue by enitrat** [starkware-libs/cairo#4970]
# Bug Report

**Cairo version:**
2.5.2

**Current behavior:**
Compiling the codebase works fine.
However, running `scarb test -p contracts` in the following branch fails. As such, we're blocked and cannot upgrade our codebase to 2.5 and are stuck using a nightly release.

**Expected behavior:**
There should be no issue.

**Steps to reproduce:**
Clone https://github.com/kkrt-labs/kakarot-ssj, checkout the branch of this pull request https://github.com/kkrt-labs/kakarot-ssj/pull/723 and run `scarb test -p contracts`

**Comment by orizi** [comment]
please check on 2.5.3 - should be solved on it.
