### ISSUE TITLE
feat: compile time NonZero constants

### ISSUE THREAD

**Issue by shramee** [starkware-libs/cairo#4986]
# Feature Request

**Describe the Feature Request**

Allow NonZero constants to be created at compile time. This can be done probably via a numeric literal implementation.

**Describe Preferred Solution**

```rs
const FIELDNZ: NonZero<u256> =
    21888242871839275222246405745257275088696311157297823662689037894645226208583;
```

**Describe Alternatives**
Alternative is to do a non zero try_into on every operation this costs extra unnecessary steps.

```rs
// Everytime you need NonZero field
fn field_nz() -> NonZero<u256> {
    21888242871839275222246405745257275088696311157297823662689037894645226208583_u256
        .try_into()
        .unwrap()
}
```

**Related Code**

Every div and mul op here needs NZ u256, so we create it on every call.
https://github.com/shramee/cairo_bn/blob/main/src/math/fast_mod.cairo#L51

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by orizi** [comment]
This would be release in the 2.6.0 full release (not really possible before, since it required some sierra updates)

**Comment by shramee** [comment]
![image](https://github.com/starkware-libs/cairo/assets/11048263/fc47b4d4-66b1-4625-9ee7-8aeb84ae65ea)

**Comment by orizi** [comment]
On release 2.6.0.
