### ISSUE TITLE
bug: Makes internal contract member state traits in contracts visible for testing

### ISSUE THREAD

**Issue by julio4** [starkware-libs/cairo#5044]
# Bug Report/Request

**Cairo version:** 2.5.3
**Edition:** 2023_11

**Current behavior:**

Aliased contract member state traits of contracts are not visibles, but sometime accessible with `use __member_module_xxxx::InternalContractMemberStateTrait` (for example with `LegacyMap`, but not with integers).

In generated contract code:
```
use __member_module_xxxx::InternalContractMemberStateTrait as xxxxContractMemberStateTrait;
mod __member_module_xxxx {...}
```

**Expected behavior:**

Being able to use the trait with `use Contract::xxxxContractMemberStateTrait;`, useful for testing specific state member mutations.

In generated contract code:
```
pub use __member_module_xxxx::InternalContractMemberStateTrait as xxxxContractMemberStateTrait;
pub mod __member_module_xxxx {...}
```

**Comment by orizi** [comment]
can you give a concrete example for the usage for testing?

**Comment by enitrat** [comment]
Hi @orizi, it's nice to unit test contract internals without exposing storage variables in functions. c.f. https://github.com/keep-starknet-strange/unruggable.meme/blob/4d01b4ffab13d2c70e81581d3d312ceb1cbabafc/contracts/src/tests/unit_tests/test_unruggable_memecoin.cairo#L21-L23

**Comment by piotmag769** [comment]
https://foundry-rs.github.io/starknet-foundry/testing/testing_contract_internals.html#contract_state_for_testing---state-of-test-contract
+1, we even have such example in our docs

**Comment by julio4** [comment]
Yes exactly, it's mostly for use with `contract_state_for_testing`.
Also, the `__member_module_xxxx` is visible for some types but not others.

**Comment by orizi** [comment]
the member module should definitely **not** be visible - but i accept that the trait should be.
fixing.

**Comment by orizi** [comment]
Currently being release in 2.5.4.
