### ISSUE TITLE
bug: LSP crash with starklings, prelude is not a core submodule.

### ISSUE THREAD

**Issue by N0lanV** [starkware-libs/cairo#5069]
# Bug Report

**Cairo version: 2.5.3**

**Current behavior:**
LSP worker panic with Starklings-cairo1 exercices.
```
thread 'main' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/cairo-lang-semantic-2.5.3/src/corelib.rs:57:28:
`prelude` is not a core submodule.
```

**Expected behavior:**
Working like when I create a new project

**Steps to reproduce:**
Install vscode, scarb stable, add cairo 1.0 extension, clone starklings-cairo1 and open the project.

**Other information:**
![image](https://github.com/starkware-libs/cairo/assets/109871781/d01f794a-73ec-4aa3-8c5a-37758e4915f5)

**Comment by orizi** [comment]
it is a configuration issue - please open an issue at starklings - not here.
