### ISSUE TITLE
bug: When reading a U32 from a referenced struct, an error occurs during value retrieval

### ISSUE THREAD

**Issue by HouseGray** [starkware-libs/cairo#5258]
# Bug Report
I'm not sure if it's a bug or a feature. I couldn't find a corresponding situation in the Cairo book either
**Cairo version:**
2.5.4

**Current behavior:**
it will be  error if the parameter is refer，if I change the parameter from refer to copy,it will be right.

error message: 
Mismatched types. The type `@core::integer::u32` cannot be created from a numeric literal.
**Expected behavior:**
I feel that regardless of whether copy or refer , it should be possible to use the match statement

**Steps to reproduce:**

**Related code:**
 

```
insert short code snippets here
```
fn get_data_check(data: @Data) -> bool{
match data.id {
**0** => false,
_ => true
}
}
**Other information:**

**Comment by enitrat** [comment]
`data.id` is of type `@u32`, not `u32`. you need to desnap it before

```rust
fn get_data_check(data: @DaTa) -> bool{
match *data.id {
0 => false,
_ => true
}
}
```

**Comment by HouseGray** [comment]
Sorry!It's my problem,thank you for your help
