### ISSUE TITLE
Include ether and wei units in Cairo lang 

### ISSUE THREAD

**Issue by quentin-abei** [starkware-libs/cairo#5275]
# Feature Request
Currently cairo does not support units like ether and wei. If a dev want to work with these units, he have to create constatnt value manually and work with them.
Include these standard ether units into the next cairo lang update

**Describe Preferred Solution**
Dev should be able to write 1 wei to refers the 1, or 1 ether to refer to 1*10**18; as seen in solidity 

**Related Code**
let take a defi app where user should deposit at least amount when calling a function:

```
fn deposit(ref self: ContractState, amount: u256) {

 // Here
 assert(amount >= 1 ether , 'error');
-
-
}
```

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes

**Comment by mkaput** [comment]
I think this is a cool idea to make a library with this, rather than integrate it into the language. 

Mind that Cairo by itself is blockchain-agnostic so this is not something we can make built-in

**Comment by quentin-abei** [comment]
Hello @mkaput , i'am ready to build a library for this . Just I could not deploy any contract on starknet using starkli recently.
So I'll probably need ressource for deploying contracts on testnet and mainnet and also ressource for building a library.
Thanks .

**Comment by mkaput** [comment]
> i'am ready to build a library for this .

Awesome! 😍 I think this might be a great utility for meany people, and it could be worth to make a part of [Alexandria](https://github.com/keep-starknet-strange/alexandria). As a starting point, I suggest opening a feature request in their repo (have a look at their contribution guidelines), and then @AbdelStark will guide you how to progress further.

> Just I could not deploy any contract on starknet using starkli recently. So I'll probably need ressource for deploying contracts on testnet and mainnet and also ressource for building a library. Thanks .

Cairo libraries have nothing to do with Starknet. It all happens on your local machine and you publish a GitHub repository. Here is a Scarb guide about starting a new package: https://docs.swmansion.com/scarb/docs/guides/creating-a-new-package.html

If you have any technical questions re starknet/starkli, I suggest asking on Discord.

**Comment by mkaput** [comment]
I will close this issue as this is not Cairo compiler/stdlib related.
