### ISSUE TITLE
bug: recursive types not supported entirely

### ISSUE THREAD

**Issue by glihm** [starkware-libs/cairo#5309]
# Bug Report

**Cairo version:**

2.6.3

**Current behavior:**

Let's take the following code:
```rust
#[cfg(test)]
mod test2 {
    #[derive(Copy, Drop, Serde)]
    enum Ty {
        Primitive: felt252,
        Struct: Struct,
    }

    #[derive(Copy, Drop, Serde)]
    struct Struct {
        name: felt252,
        children: Span<Member>
    }

    #[derive(Copy, Drop, Serde)]
    struct Member {
        name: felt252,
        ty: Ty
    }

    #[test]
    #[available_gas(10000000)]
    fn sierra_type_dup() {
        Ty::Struct(Struct {
            name: 'cairo',
            children: array![
                Member {
                    name: 'id',
                    ty: Ty::Primitive('felt252'),
                }, Member {
                    name: 'byte',
                    ty: Ty::Primitive('u8'),
                }
            ].span()
        });
    }
}
```
This will result in:
```
thread 'main' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/salsa-0.16.1/src/lib.rs:490:48:
Internal error, cycle detected:

DatabaseKeyIndex { group_index: 2, query_index: 48, key_index: 4 }
DatabaseKeyIndex { group_index: 2, query_index: 48, key_index: 8 }

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: `scarb metadata` exited with error
```

**Expected behavior:**

Recursive types being supported as it was initially reported by #4075. The fix in #4083 seems to work only for first level recursion.

**Steps to reproduce:**

Copy paste the given code into `lib.cairo`.
Ensure scarb version `asdf local scarb 2.6.3`.
Run the test: `scarb test`.

**Related code:**

See #4083.

**Other information:**

I would be happy to help with some guidance, not sure exactly how to tackle that in the current state of the code.

**Comment by orizi** [comment]
Checked, on `main` `dev-v2.6.3` branches, as well as with the proposed setup - all worked.
make sure that you actually get 2.6.3 in `scarb --version`.

**Comment by glihm** [comment]
Thank you for checking this out @orizi.
I still have the issue with this setup:
```toml
[package]
name = "testscarb"
version = "0.1.0"
edition = "2023_10"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "=2.6.3"

[[target.starknet-contract]]
sierra = true
casm = true
```
And
```
scarb 2.6.3 (e6f921dfd 2024-03-13)
cairo: 2.6.3 (https://crates.io/crates/cairo-lang-compiler/2.6.3)
sierra: 1.5.0
```
The error is still:
```
thread 'main' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/salsa-0.16.1/src/lib.rs:490:48:
Internal error, cycle detected:

DatabaseKeyIndex { group_index: 2, query_index: 48, key_index: 4 }
DatabaseKeyIndex { group_index: 2, query_index: 48, key_index: 8 }

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: `scarb metadata` exited with error
```
What may I be missing then?

**Comment by glihm** [comment]
> I works for me with this configuration as well. For some reason it seems your scarb setup uses an old compiler - in any case - these questions are for support, or the scarb repository (if there's an actual bug there).

Got you, thank you for confirming, will reach out to them. :pray:

**Comment by orizi** [comment]
The issue is that the layout size is inifinite - as it contains itself.
you need to wrap it in a box.
for the diagnostics part - will add proper diagnostic in a few days.

**Comment by remybar** [comment]
> The issue is that the layout size is inifinite - as it contains itself. you need to wrap it in a box. for the diagnostics part - will add proper diagnostic in a few days. (So the issue is actually the `Array` variant, the recursive `Span`s are totally fine)

Oh, great ! Thank you very much @orizi ! 🚀
