### ISSUE TITLE
feat: Add option to output SierraProgramDebugInfo in the compiler artifacts

### ISSUE THREAD

**Issue by smonicas** [starkware-libs/cairo#5311]
# Feature Request

**Describe the Feature Request**
Allow to output the `SierraProgramDebugInfo` in the compiler artifacts so third party tools can use it to map sierra to source code. I think at the moment is only possible by using the compiler as library but not by running `starknet-compile` and looking at the artifacts.

**Describe Preferred Solution**
Add a CLI option to have the `SierraProgramDebugInfo` in the artifacts.  
It would also help to add it in the `ContractClass` as currently it's done for `sierra_program_debug_info` (despite the name it's a different structure `cairo_lang_sierra::debug_info::DebugInfo`) instead of discarding it in `compile_contract_with_prepared_and_checked_db`.

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by orizi** [comment]
Please open on scarb - compilation here shouldn't include these in any case (and library support already exists)
