### ISSUE TITLE
bug: `FunctionIdAlreadyExists` Error When Using `calc_ap_changes` on a Sierra program

### ISSUE THREAD

**Issue by raphaelDkhn** [starkware-libs/cairo#5329]
# Bug Report

**Cairo version:**
```
scarb 2.6.4
cairo: 2.6.3
sierra: 1.5.0
```

**Current behavior:**

I have a Cairo program, compiled to Sierra. When I try to compute `calc_ap_changes` from [cairo-lang-sierra-ap-change](https://crates.io/crates/cairo-lang-sierra-ap-change) crate, it fails with the following error: 

```bash
Error: ProgramRegistryError(FunctionIdAlreadyExists(FunctionId { id: 7525693132902674641, debug_name: Some("orion::operators::tensor::math::gather::gather[expr84]") }))
```

**Steps to reproduce:**

 I created a [repo](https://github.com/raphaelDkhn/cairo-decision-tree/tree/cairo-2.6.3) to reproduce the error. 

1. Clone the provided repository: `git clone https://github.com/raphaelDkhn/cairo-decision-tree/tree/cairo-2.6.3`
2. Navigate to the inference directory: `cd model/inference`
3. Compile the project using Scarb: `scarb build`
4. From the repository's root, execute `cargo run` to invoke `calc_ap_changes` on the compiled Sierra file, which results in the aforementioned error.

**Related code:**
The following code snippet demonstrates how `calc_ap_changes` is invoked:

```rust
use std::fs;

use cairo_lang_sierra::program::Program;
use cairo_lang_sierra::ProgramParser;
use cairo_lang_sierra_ap_change::calc_ap_changes;

fn main() {
    let program_path = "./model/inference/target/dev/inference.sierra";
    let sierra_program_str = read_file(program_path);

    let sierra_program: Program = ProgramParser::new().parse(&sierra_program_str).unwrap();

    let _ap_change_info =
        calc_ap_changes(&sierra_program, |_, _| 0).inspect_err(|e| eprint!("Error: {:?}", e));
}

fn read_file(path: &str) -> String {
    fs::read_to_string(path).expect("Failed to read file")
}
```

**Other information:**

The `calc_ap_changes` function is crucial for the correct execution of the program within CairoVM as per the implementation referenced [here](https://github.com/lambdaclass/cairo-vm/blob/72f0baddb007a8440d9f4a49c50dea0a67275a98/cairo1-run/src/cairo_run.rs#L582). Notably, running the same Cairo program with `scarb cairo-run` does not yield this error and executes as expected, suggesting that the issue is specific to the interaction with `calc_ap_changes`.

Any insights or suggestions to address this function ID conflict would be greatly appreciated.

**Comment by orizi** [comment]
You are using the sierra textual representation - which is for internal testing purposes only - this may be the cause of the failure you are having.

Does this replicate when you are using the produced Scarb json of sierra?

Do note that looking at the error - you can see `orion::operators::tensor::math::gather::gather[expr84]` appears more than once in the sierra textual representation, I'd recommend you have a look there.

**Comment by raphaelDkhn** [comment]
It's working well with `sierra.json`, thank you!!
