### ISSUE TITLE
feat: implement `get_block_hash` in the CASM runner

### ISSUE THREAD

**Issue by enitrat** [starkware-libs/cairo#5351]
# Feature Request

**Describe the Feature Request**

Implement `get_block_hash` in the CASM runner instead of panicking.

**Describe Preferred Solution**
As per the TODO comment:

> perform a storage read. Have an arbitrary, hardcoded
    (For example, addr=1) contain the mapping from block number to block hash.

**Related Code**

https://github.com/starkware-libs/cairo/blob/fb1ba328b23623f8ae6cecf7b7a09104c0c4eb2a/crates/cairo-lang-runner/src/casm_run/mod.rs#L839-L850

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [x] No

**Comment by orizi** [comment]
Is something like the attached PR what you are looking for?

**Comment by enitrat** [comment]
yes that would be perfect :) thank you!
