### ISSUE TITLE
bug: CairoLS tends to invoke Scarb unnecessarily too frequently when editing Scarb.toml

### ISSUE THREAD

**Issue by mkaput** [starkware-libs/cairo#5354]
# Bug Report

**Cairo version:**

43afafdcc947202a918fe872288e8f601c772554

**Current behavior:**

https://github.com/starkware-libs/cairo/assets/3450050/4b733e8d-bd7f-4a52-b2b7-e1b17bf8dd21

**Expected behavior:**

The notifications' abomination should not happen.

The solution for this is to cache Scarb state. To be done during the grand rewrite.

**Steps to reproduce:**

See video.

**Other information:**

Thanks, @milancermak, for the video!

**Comment by milancermak** [comment]
Just to clarify, this happens not just with Scarb.toml, but when editing and saving any file in the workspace.

IDK if it makes a difference, but I often have multiple Code instances of `.code-workspace`s open, each workspace can/does contain more than 1 project folders.

**Comment by boyuanx** [comment]
Scarb seems to be invoked excessively for extremely simple code changes (even within the same line)

**Comment by mkaput** [comment]
I am aware of the fact that CairoLS is invoking Scarb too much, and resolving that problem should fix this particular issue.

As for multiple workspaces support, this is a thing that I believe nobody has been thinking about yet and the codebases of both the LS and VSC extensions are not writing with supporting this in mind. If this works in any way -- it does rather coincidentally than intention.

**Comment by mkaput** [comment]
Superseding this bug task with #6124 that describes a bigger feature that will fix this bug.
