### ISSUE TITLE
feat: pass args to asser macro

### ISSUE THREAD

**Issue by milancermak** [starkware-libs/cairo#5362]
# Feature Request

**Describe the Feature Request**

I wanted to write a utility function for my test suite to check that values are approximately equal, something like this:

```rust
pub fn approx<T, impl TPartialOrd: PartialOrd<T>, impl TSub: Sub<T>, impl TCopy: Copy<T>, impl TDrop: Drop<T>>(
    a: T, b: T, tolerance: T, msg: ByteArray
) {
    if a >= b {
        assert!(a - b <= tolerance, msg);
    } else {
        assert!(b - a <= tolerance, msg);
    }
}
```

The intended use would be:

```rust
let expected_balance = 1500_u64;
let balance = token.balance_of(user1);
approx(balance, expected_balance, 25, "balance mismatch");
```

In other words, I'd like to pass in the error message to my `approx` function so it can be used in the `assert!` macro. 

This is currently not possible. I'm getting a `Plugin diagnostic: Format string argument must be a string literal.` error.

Would it be possible to update the `AssertMacro` so that it supports my use case?

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by orizi** [comment]
No, it shouldn't support your test case.
You just want to replace the `msg` arg with `"{msg}"`.
