### ISSUE TITLE
feat: add rename type in sierra program

### ISSUE THREAD

**Issue by jujube** [starkware-libs/cairo#5408]
#[serde(rename = "type")]
https://github.com/starkware-libs/cairo/blob/ad6aeb70ac0ab6c6c129eb088df682705d4f1853/crates/cairo-lang-sierra/src/program.rs#L232

**Comment by orizi** [comment]
Can you add any context please?

**Comment by jujube** [comment]
Hope  ty becomes type
https://github.com/starkware-libs/cairo/blob/ad6aeb70ac0ab6c6c129eb088df682705d4f1853/crates/cairo-lang-sierra/src/test_data/fib_jumps#L1519

**Comment by orizi** [comment]
I don't think we can or should change this - as this is an existing format - this would break existing file with no real need.

**Comment by jujube** [comment]
scarb new cairo0408
cd cairo0408
scarb build
tree
.
├── Scarb.lock
├── Scarb.toml
├── src
│   └── lib.cairo
└── target
    ├── CACHEDIR.TAG
    └── dev
        └── cairo0408.sierra.json


ty in cairo0408.sierra.json  
Hope ty becomes type

**Comment by mkaput** [comment]
I understand your reasoning behind changing name of this field, but it is part of a well-established file format that **we do not want to change**. It happened as it happened and renaming it is not worth the work.
