### ISSUE TITLE
feat: better error reporting with wrong use of unwrap 

### ISSUE THREAD

**Issue by milancermak** [starkware-libs/cairo#5430]
# Feature Request

**Describe the Feature Request**

I have a simple piece of code where I made an error:

```rust
    pub fn foo() -> ContractAddress {
        0x3240581234501345134513451341345134512451234521.try_into().unwrap('no')
    }
```

I should have used `except` instead of `unwrap`, made the error while copy-pasting stuff and generally focusing on fixing something else. It took me a while to spot the mistake for two reasons.

This is how the error is reported by the compiler:

```
error: Wrong number of arguments. Expected 1, found: 2
 --> /Users/m/projects/foo/src/constants.cairo:87:9
        0x3240581234501345134513451341345134512451234521.try_into().unwrap('no')
        ^**********************************************************************^
```

And in VSCode:

<img width="607" alt="Screenshot 2024-04-17 at 11 55 51" src="https://github.com/starkware-libs/cairo/assets/184055/eb23dee7-8cfc-4b2f-915a-7e0578792d6d">

**Describe Preferred Solution**

None of the hints above pinpoint the error on the wrong use of `unwrap`. Quite contrary, they mislead me.

It would be better if the red squiggly lines were only under the unwrap('no') part of the code and if the error coming from the compiler would look something like this:

```
error: Wrong number of arguments. Expected 0, found: 1
 --> /Users/m/projects/foo/src/constants.cairo:87:9
        0x3240581234501345134513451341345134512451234521.try_into().unwrap('no')
                                                                   ^***********^
```

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [x] No

**Comment by orizi** [comment]
Moving it to be on the actual arguments - so for any case it would point to something more inner in a consistent manner.
