### ISSUE TITLE
bug: contract_address_const::<0x800000000000011000000000000000000000000000000000000000000000000> error 

### ISSUE THREAD

**Issue by zpano** [starkware-libs/cairo#5435]
# Bug Report

**Cairo version:**

cairo: 2.5.3 (https://crates.io/crates/cairo-lang-compiler/2.5.3)

**Current behavior:**

**Expected behavior:**

![image](https://github.com/starkware-libs/cairo/assets/61449410/eb3b06fc-0ba8-4b83-a5ca-8a3d119d0002)

**Related code:**
```cairo
    fn test() {
        let _ = contract_address_const::<
            0x800000000000011000000000000000000000000000000000000000000000000
        >();
    }
```

```
insert short code snippets here
```

**Other information:**
0x800000000000011000000000000000000000000000000000000000000000000 is a valid address for starknet.

**Comment by orizi** [comment]
no it isn't.
the range of valid addresses are `[1, 2^251)` - so your number is `+0x11000000000000000000000000000000000000000000000000` out of range.
