### ISSUE TITLE
sha256 support

### ISSUE THREAD

**Issue by ArielElp** [starkware-libs/cairo#5446]
In Starknet v0.13.2 we will add support for sha256. In Cairo, this means that we're adding the following two functions to the corelib:

```
pub fn compute_sha256_u32_array(
    mut input: Array<u32>, last_input_word: u32, last_input_num_bytes: u32) -> [u32; 8]

pub fn compute_sha256_byte_array(arr: @ByteArray) -> [u32; 8]
```

Under the hood, these functions will use a new sha256 syscall that will be supported on the next version of Starknet

**Comment by pol8a100** [comment]
d2d977c58444271d9c780187e93f80e5
