### ISSUE TITLE
bug: Variable was previously moved

### ISSUE THREAD

**Issue by harshal2608** [starkware-libs/cairo#5451]
# Bug Report

**Cairo version:**
2.6.3

 #[storage]
    struct Storage {
        // @notice Maps the referral code to the owner
        code_owner: LegacyMap::<ByteArray, ContractAddress>,

        // @notice Maps the owner to the referral code
        // @dev To ensure that the trader can set the code only once
        user_code: LegacyMap::<ContractAddress, ByteArray>,

        // @notice Maps the trader to the referee code
        trader_referral_codes: LegacyMap::<ContractAddress, ByteArray>,
        
        #[substorage(v0)]
        ownable: OwnableComponent::Storage,
        #[substorage(v0)]
        upgradeable_storage: UpgradeableComponent::Storage,
    }
    
    fn set_trader_referral_code(
            ref self: ContractState,
            _code: ByteArray,
        ){
            assert!(self.trader_referral_codes.read(get_caller_address()).len()==0, "ReferralStorage: trader already has a code");
            assert!(self.code_owner.read(_code).is_non_zero(), "ReferralStorage: code not found");
            assert!(self.code_owner.read(_code) != get_caller_address(), "ReferralStorage: code owner cannot set code for himself");

            let _account = get_caller_address();
            self.trader_referral_codes.write(_account, _code);
            self.emit(SetTraderReferralCode{account:_account, code: _code});  
        }
        
         #[derive(Drop, starknet::Event)]
    struct SetTraderReferralCode {
        account: ContractAddress,
        code: ByteArray,
    }
    
    Apparently I cant use _code twice in the function. It gives the error that Variable was moved previously.

**Comment by orizi** [comment]
It is correct - as `ByteArray` is non-copy.
In any case - a solution here would be to make the event `@ByteArray` instead of `ByteArray` based:
```
        let _account = get_caller_address();
        self.emit(SetTraderReferralCode{account:_account, code: @_code});
        self.trader_referral_codes.write(_account, _code);
```
