### ISSUE TITLE
bug: cannot escape curly brace in format string

### ISSUE THREAD

**Issue by milancermak** [starkware-libs/cairo#5483]
# Bug Report

**Cairo version:** 2.6.3

**Current behavior:**

I want to use `format!` to build a JSON string.

```rust
let n = 42_u8;
let json: ByteArray = format!("\{\"value\":\"{}\"\}", n);
```

However, compiling this results in an error: 

```text
error: Invalid string escaping.
 --> /Users/m/projects/foo.cairo:119:43
            let json: ByteArray = format!("\{\"value\":\"{}\"\}", n);
                                          ^********************^

error: Plugin diagnostic: Format string argument must be a string literal.
 --> /Users/m/projects/foo.cairo:119:43
            let json: ByteArray = format!("\{\"value\":\"{}\"\}", n);
                                          ^********************^
```

It looks like escaping `{` and `}` is not supported.

Ideally, it should be for cases like this. The expected behavior is that the string in `json` should be `{"value":"42"}`.

**Comment by orizi** [comment]
you are mixing two types of escaping:
note that `{` and `}` analysis for variables is post string processing - so later escaping must be added - and it is supported by `{{` and `}}`.
so you should use:
```
let n = 42_u8;
let json: ByteArray = format!("{{\"value\":\"{}\"}}", n);
```
