### ISSUE TITLE
bug: cairo test case test_ecdsa_recover_public_key fails

### ISSUE THREAD

**Issue by xiaolou86** [starkware-libs/cairo#5486]
# Bug Report
test case `test_ecdsa_recover_public_key` failed.

**Cairo version:** 

main branch

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
#[test]
fn test_ecdsa_recover_public_key() {
    let message_hash = 0x503f4bea29baee10b22a7f10bdc82dda071c977c1f25b8f3973d34e6b03b2c;
    let signature_r = 0xbe96d72eb4f94078192c2e84d5230cde2a70f4b45c8797e2c907acff5060bb;
    let signature_s = 0x677ae6bba6daf00d2631fab14c8acf24be6579f9d9e98f67aa7f2770e57a1f5;
    assert_eq(
        @ecdsa::recover_public_key(:message_hash, :signature_r, :signature_s, y_parity: false)
            .unwrap(),
        @0x7b7454acbe7845da996377f85eb0892044d75ae95d04d3325a391951f35d2ec,
        'recover_ecdsa_public_key failed'
    );
    assert(
        ecdsa::check_ecdsa_signature(
            :message_hash,
            public_key: ecdsa::recover_public_key(
                :message_hash, :signature_r, :signature_s, y_parity: true
            )
                .unwrap(),
            :signature_r,
            :signature_s
        ),
        'ecdsa returned false'
    );
}
```

**Other information:**

**Comment by xiaolou86** [comment]
I think it failed because `signature_r` should in the valid range [1, n-1], but it's not.

signature_r : 0xbe96d72eb4f94078192c2e84d5230cde2a70f4b45c8797e2c907acff5060bb
n: 0x800000000000010ffffffffffffffffb781126dcae7b2321e66a241adc64d2f

I am new to this. Free to correct me if I am wrong. 

@orizi Please help me to review.

**Comment by orizi** [comment]
I don't understand the issue - all i see is that you copied a test from the corelib which passes on our CI all the time.

**Comment by orizi** [comment]
assuming you checked the values out of Cairo context - you probably used the wrong `y_parity` value.

Closing for now - feel free to reopen with more elaboration if the issue remains.
