### ISSUE TITLE
dev: Associate Cairo logo with `.cairo` files in VS Code file explorer and file editor

### ISSUE THREAD

**Issue by misicnenad** [starkware-libs/cairo#5626]
Due to missing Logo for the official Cairo 1.0 VS Code extension and the associated `.cairo` files, my first impression when using the extension was that I downloaded a custom one made by some 3rd party instead of the official one made by StarkWare.

Displaying the official Cairo language logo next to `.cairo` files would make it clear that these are _valid_ Cairo files.
This would also make the whole VS Code extension look more professional and genuine.

- file explorer:
   - current:
![image](https://github.com/starkware-libs/cairo/assets/19427053/19ad8a6d-d6f8-4756-a1cb-80366f6d778e)
   - with icon:   
![image](https://github.com/starkware-libs/cairo/assets/19427053/11814b41-a631-4a78-b52a-6d11cbf3ef13)

- file editor:
   - current:
![image](https://github.com/starkware-libs/cairo/assets/19427053/d41d7128-9dae-4e40-82dd-a3c0a944193c)
   - with icon:   
![image](https://github.com/starkware-libs/cairo/assets/19427053/68b80288-cd2d-4a8b-bb8b-cb3f9c4a7d31)

**Comment by Utilitycoder** [comment]
I would like to work on this issue and contribute the necessary changes.

Could you please assign this issue to me and provide pointers on which files need to be updated to implement this change?

**Comment by mkaput** [comment]
The task is yours. I have no idea what has to be changed of if it's actually possible (because VSCode has a concept of icon themes) 🙃

**Comment by Utilitycoder** [comment]
I have figured out the solution to the issue. I however need a transparent icon that should be used. I think there will be an official brand guide so I don't want to use just anything on the internet. 
<img width="1440" alt="Screenshot 2024-05-26 at 19 03 39" src="https://github.com/starkware-libs/cairo/assets/66361605/8738c185-edab-4dd2-a594-018d42002739">

**Comment by misicnenad** [comment]
@Utilitycoder here's a Cairo logo with transparent background
![Cairo-logo](https://github.com/starkware-libs/cairo/assets/19427053/9644fe50-2de2-458f-a24d-5800a59af510)

**Comment by mkaput** [comment]
Thanks @misicnenad for providing it. @Utilitycoder if you'll find descaling this giving bad quality, I can ask Starkware marketing ppl for an SVG version.

**Comment by enitrat** [comment]
https://starkware.co/media-kit/ the branding kit is publicly available here
