### ISSUE TITLE
feat: provide a `Span<T>` to `Array<T>` method 

### ISSUE THREAD

**Issue by tdelabro** [starkware-libs/cairo#5631]
# Feature Request

`Span<T>` is a wrapper around `@Array<T>`. 
It should be possible to get the value out of this wrapper, either as `@Array<T>` or `Array<T>`. Or both.

Right now the only way to build back an `Array` from a `Span` is to iterate over it through `pop_front`. It is not a good DevX.

**Describe Preferred Solution**

A counterpart to the `Array::span()` method. `Span::consume -> Array` and `Span::snapshot -> @Array` maybe. 
Or implementations of the `Into` trait.

**Describe Alternatives**

 Implementations of the `Into` trait.

**Related Code**

[](https://github.com/starkware-libs/cairo/blob/68b7072783c7963e4ca17c88d9928dd5dc12db96/corelib/src/array.cairo#L4)

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

No, it's an important design decision, it should most likely be done by the project maintainers.

**Comment by orizi** [comment]
Do note that:
```
let mut arr = array![];
arr.append_span(span);
```
Should provide what you requested.
Not sure about adding a `Into` implementation - as `Into` does not sound like a heavy operation - and this action is definitely expensive.

**Comment by orizi** [comment]
Also - do note - that since (at least currently) a span is not the owner of its elements - `consumption` of a span into an array isn't actually possible.

**Comment by tdelabro** [comment]
> Not sure about adding a Into implementation - as Into does not sound like a heavy operation - and this action is definitely expensive.

I have to disagree about `Into` not being for heavy operation. You have no way to enforce it once the trait is `pub` and there is no general understanding of what is or is not a heavy operation. So this should not be a criteria when thinking about implementing `Into`. 
As you can see in the [When to implement From](https://doc.rust-lang.org/std/convert/trait.From.html#when-to-implement-from) section of the rust language, the complexity of the operation is not a criteria.

Having `From<Array<T>> of Span<T>` and `From<Span<T>> of Array<T>` being implemented as part of the corelib doesn't go against any of the criteria listed in the rust doc and most importantly enhance the programer ability to create complex generic trait with bouds like `+<Into<Array<T>>>`

**Comment by tdelabro** [comment]
> Also - do note - that since (at least currently) a span is not the owner of its elements - consumption of a span into an array isn't actually possible.

You consume the Span, not its elements.

This should do the work:
```
let mut arr = array![];
arr.append_span(span);
drop(span);
```

But I note that those implementation would only exist where `+Copy<T>` or `+Clone<T>`

**Comment by orizi** [comment]
You do not consume the span, as you cannot consume a copyable object (as any access to it would not consume the object)

**Comment by orizi** [comment]
I accept the `into` claim (mostly as there is a `Into` for `&[]` to Vec in rust).
I still am strongly against calling any function that accepts a span being called consumed - given that it doesn't consume it in any way that would make sense to the function caller.

**Comment by tdelabro** [comment]
>  I still am strongly against calling any function that accepts a span being called consumed - given that it doesn't consume it in any way that would make sense to the function caller.

From the caller's pov, because of `Copy`, it looks like it is not consumed.
But `into` does consume it if you look at the actual `Into` impl. `pop_front` is called by `append_span` onto `span. Leaving `span` empty at the end of the execution, then dropping it.
