### ISSUE TITLE
dev: rename `AddEq` to `AddAssign` and so on

### ISSUE THREAD

**Issue by tdelabro** [starkware-libs/cairo#5648]
There is no doc for `AddEq` but I assume it is the trait responsible for defining the behavior of the `+=` operator.

It seems that it is named this way because it is made up of the `+` (add) symbol and the `=` (equal) symbol.
But `Eq` references equality, like in `PatrialEq`, while the `=` in this situation is used in its "assign" meaning, not its "equality" meaning.

In Rust, it's called [AddAssign](https://doc.rust-lang.org/std/ops/trait.AddAssign.html).
In Python, we talk about ["augmented assignment"](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements).
Same for [C, C++, C#](https://en.wikipedia.org/wiki/Operators_in_C_and_C%2B%2B#Assignment_operators)

So let's not do anything out of the norm here, and quickly change the name to `AddAssign::add_assign` and so on for sub, mul, and div before it solidifies

**Comment by orizi** [comment]
you are correct - feel free to add doc if you want - but in anycase - changing names disallowed - as it was already solidified.
will consider changing upon a breaking change release.
closing for now.

**Comment by tdelabro** [comment]
@orizi are we talking major (3.0.0) breaking changes?
Do you see it happening soon?

Coz, tbh, it is a really bad look for a language to contain this mistake in it's corelib

**Comment by ArielElp** [comment]
This will have to wait for 3.0.0, so it will be some time (we need more major reasons for a breaking change). Renaming traits the can be implemented in user code is a no-no post 2.0.0 (we're not breaking user code)

**Comment by tdelabro** [comment]
Makes sense. Should we keep it closed tho, or rather re-open it and tag it `3.0.0` so that we don't forget about it when the time comes

**Comment by orizi** [comment]
Keep it closed, we have a list for that.

**Comment by tdelabro** [comment]
Internally?

**Comment by orizi** [comment]
internal.

**Comment by mkaput** [comment]
Hmm this could be done via editions, I think. This would require some magic logic in the compiler to solve cross-edition aliases/renames in the resolver, but shouldn't be a complex code to my intuition

**Comment by tdelabro** [comment]
@mkaput @orizi how often are Cairo editions released?
Rust does it every 3 years, but given Cairo is young and moving a lot faster, every 6 months or one year max seems more appropriate. 
Wdyt?

**Comment by mkaput** [comment]
Currently, editions are done when it's really needed. I don't have a strong opinion if editions should be employed to make this change vs not do it at all. Both are definitely better than Cairo 3

**Comment by orizi** [comment]
managed to do it without breakages as part of the old trait style deprecation effort.
