### ISSUE TITLE
feat: Zero derive

### ISSUE THREAD

**Issue by milancermak** [starkware-libs/cairo#5825]
# Feature Request

**Describe the Feature Request**

I'd like to have a derive for the `num::traits::zero::Zero` trait so I don't have to implement it on structs, which is just boring.

**Describe Preferred Solution**

By way of example:

```rust
#[derive(Zero)]
struct Point {
    x: u64,
    y: u64,
    z: u64
}
```

This would create the implementation of `Zero` for `Point`, sth like this:

```rust
impl PointZero of Zero<Point> {
    fn zero() -> Point {
        Point { x: Zero::zero(), y: Zero::zero(), z: Zero::zero() }
    }

    fn is_zero(self: @Point) -> bool {
        self == Point::zero()
    }

    fn is_non_zero(self: @Point) -> bool {
        self != Point::zero()
    }
```

**Additional Context**

Rust [has this](https://docs.rs/num-derive/latest/num_derive/derive.Zero.html).

Similar could be done for `num::traits::one::One` for consistency.

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by orizi** [comment]
I don't think this makes sense for a general derive.

rust *does not* have it - there is a package supplying it. writing a macro providing this is possible, and writing these should be allowed soon through scarb. but that isn't going to be part of the corelib.
