### ISSUE TITLE
Hovers on identifiers *defining* the item/variable are not working

### ISSUE THREAD

**Issue by mkaput** [starkware-libs/cairo#5826]
## Summary

When hovering over identifiers which **define** items/variables, user expects to get the same hover information as one produced when hovering over identifiers which **reference** these elements.

See examples:

| Expected | Actual |
|---|---|
| ![Image](https://github.com/starkware-libs/cairo/assets/3450050/716d89e2-0539-4746-8ce5-a104531d9c38) | ![Image](https://github.com/starkware-libs/cairo/assets/3450050/fc1240aa-7615-476b-8cec-3bde8d469ba6) _This case shows no hovers at all._ |
| ![Image](https://github.com/starkware-libs/cairo/assets/3450050/86d20ede-5256-4e72-aed9-d5534990d6b1) <img width="352" alt="image" src="https://github.com/user-attachments/assets/819ec9d4-bc0b-4f7f-b84c-d568cb091045"> | ![Image](https://github.com/starkware-libs/cairo/assets/3450050/8163bbec-3e55-414b-ab58-0b5724538b08) _This is the legacy hover implementation that we aim to remove._ |

## Proposed solution

This logic only looks for references and completely ignores cases when the identifier under the cursor is actual _name_ of the item/variable. Such condition should be added to this code:

https://github.com/starkware-libs/cairo/blob/4646ad819521338ccd92b8ebef76b96770b46ce1/crates/cairo-lang-language-server/src/lang/inspect/defs.rs#L40-L46

**Comment by Villegas2003** [comment]
Hello Marek,

I'm a software developer and a student at Universidad Cenfotec. I have experience working with various technologies, including Angular for frontend development, Springboot for backend development, and MySQL for database management. Additionally, I have a strong interest in blockchain technology and have been eager to apply my knowledge in the Web3 space.

I'm interested in contributing to the Cairo project and would like to help with issue #5826. Could you provide more details on the current status and any guidelines for contributing?

Looking forward to collaborating.

**Comment by mkaput** [comment]
Hello!

The issue is still open for taking :) I can assign it to you.

As I said, the implementation should extend the snippet provided in issue description. What I imagine, is that that `find_definition(...)?` call is replaced with `match find_definition(...)`, and in the `None` case, an extra check is added that:

1. Handles variables and params (they're not included in lookup item id array). This can be done by walking up AST for appropriate syntax node kinds and then checking if `.name()` is the same identifier as the one we have on the input.
2. Otherwise, gets the top-most `LookupItemId` and checks `.name()` equality as described.

**Comment by mkaput** [comment]
Hey @Villegas2003! Any progress on this? May I help you somehow?

**Comment by Villegas2003** [comment]
Hello @mkaput, I've been sick the past few weeks. I am going to proceed this week to release the issue. Apologies for the case.

Do you have a discord or telegram to communicate with us?

**Comment by mkaput** [comment]
We can chat on Scarb's TG channel: https://t.me/+G_YxIv-XTFlhNWU0

**Comment by mkaput** [comment]
@Villegas2003 any progress? how can I help?
