### ISSUE TITLE
bug: LS should not autocomplete private re-exports + `scarb build` should not succeed when a private export is imported

### ISSUE THREAD

**Issue by misicnenad** [starkware-libs/cairo#5859]
# Bug Report

**Cairo version:**
```
scarb 2.6.4+nightly-2024-06-22 (5deb60ac1 2024-06-22)
cairo: 2.6.4 (f3af4cb8d)
sierra: 1.5.0
```
**Current behavior:**

Compiler complains that "Item `core::starknet::deploy_syscall` is not visible in this context." in a test module, even though it one of the recommended imports by the LSP. 
![image](https://github.com/starkware-libs/cairo/assets/19427053/3ecc1dd0-8144-4bef-8a06-c9e61fcdd42a)

**Running `scarb build` in the terminal runs successfully despite this error.**

**Running `scarb cairo-test` in the terminal _fails_ with the "deploy_syscall is not visible in this context" error!**

**Expected behavior:**
 
Either:
- [ ] the language server should not list private re-exports, like `deploy_syscall` in the autocomplete dialog
- [ ] `scarb build` should fail when a private re-export is imported in a module

**Steps to reproduce:**

- create new Cairo project
- open _Scarb.toml_ and add:
```
[dependencies]
starknet = ">=2.6.3"

[dev-dependencies]
cairo_test = "2.6.4+nightly-2024-06-22"
```
- open _lib.cairo_, delete the contents and paste just the following:
```rust
#[cfg(test)]
mod tests {
    use starknet::deploy_syscall;
}
```

**Comment by mkaput** [comment]
@misicnenad I think you should import the following path instead:

```cairo
use starknet::syscalls::deploy_syscall;
```

If this is the fix for you, then the problem is LS which autocompletes private re-exports. If you confirm, then I'll re-phrase the issue.

**Comment by misicnenad** [comment]
@mkaput the issue I was describing is exactly this:
> then the problem is LS which autocompletes private re-exports

Another related issue is that running `scarb build` **succeeds**, even though this should not build.

Note: I'm aware that `use starknet::syscalls::deploy_syscall;` is the correct import path.

**Comment by misicnenad** [comment]
@mkaput I just remembered that I'd already opened a similar issue to disable recommending private exports, see https://github.com/starkware-libs/cairo/issues/5660.

Can we then close this issue?

**Comment by mkaput** [comment]
yes indeed

**Comment by maciektr** [comment]
> Another related issue is that running scarb build succeeds, even though this should not build.

`scarb build` does not compile tests. All items under `cfg(test)` are discarded on the syntactic level. This means, that when compiler gets to the part when it resolves your uses to see if they exists (and thus can emit errors) - it's already removed. 

To build tests, you can run `scarb build --test` (or similarly `scarb check --test`), which `scarb test` does under the hood. This will produce the errors.  

CC @misicnenad

**Comment by misicnenad** [comment]
@maciektr that actually makes a lot of sense. Thanks a lot!
