### ISSUE TITLE
bug: Compiler is unable to infer the type of a variable when a `ByteArray` value is being assigned to it

### ISSUE THREAD

**Issue by misicnenad** [starkware-libs/cairo#5873]
# Bug Report

**Cairo version:**
```console
scarb 2.6.4+nightly-2024-06-22 (5deb60ac1 2024-06-22)
cairo: 2.6.4 (f3af4cb8d)
sierra: 1.5.0
```

**Current behavior:**

Given the following assignment of a `ByteArray` value to a variable with no explicit type:
```rust
let bytearray_var = "some bytearray";
```
The compiler is unable to infer the type of `a` to be `ByteArray`.

But it has no problems inferring types for `felt252`, `bool` or even custom structs:
```rust
#[derive(Drop)]
struct SomeType {
    a: bool
}
fn main() {
    let felt_var = 1; // infers felt252
    let u32_var = 1_u32; // infers u32
    let bool_var = true; // infers bool
    let struct_var = SomeType { a: true }; // infers SomeType
}
```

**Expected behavior:**

The compiler should be able to infer types for variables to which `ByteArray` value is assigned.

**Steps to reproduce:**

- create new project
- open _lib.cairo_
- type `let a = "a";`
- **error appears about not being able to infer type of `a`**

**Related code:**

```rust
let bytearray_var = "some bytearray"; // errors with "Type annotations needed. Failed to infer ?0"
```

**Comment by orizi** [comment]
this is the intended behaviour - there's no default type for string literals.
if nothing in the environment enforces which type it is - it won't be known.
this is to allow other types in the future to still use string literals (such as strings, const strings, and so on)

**Comment by misicnenad** [comment]
@orizi fair point, but it's still very unintuitive behavior. By that same logic, it doesn't make sense that `let var = 1;` defaults to type `felt252` - the same value can be used by other types (`u8`, `u16, `i128` etc.).

It would be nice if the default type for string literals was defined, the same way it is for defined for number literals (felt).

**Comment by orizi** [comment]
the opposite is correct - it is more likely to make sense to not have default types at all. but since we already have it we need to conform - especially since the default type is a type that would not generally be recommended for user (as it basically the machine type).

we would not like to cause the same issue for string literals as well.

**Comment by misicnenad** [comment]
Is what you're trying to say that any default type Cairo is "bad", in that it would be better for explicit types to be mandatory?

**Comment by orizi** [comment]
`Default` != `implicit`.
default means - that in cases when there is not available information providing what type is a specific numeric variable - we would just assume it is a `felt252.
example: `let x = 3;` even if `x` is never used - that would be its type.
if we do not allow it - it will indeed fail here - but - if later `foo(x)` is called - and `foo` is defined as `fn foo(v: felt252) { ... }` - we would know `x` is a felt252, even though it is implicit.

**Comment by misicnenad** [comment]
Thanks for the explanation.

I'm still not 100% sure why assigning a string literal to a variable shouldn't make that variable `ByteArray`, _unless explicitly defined otherwise_ (the same as for felts).
But I understand that there are reasons for it, maybe I'll understand more once I do a deeper dive into the language implementation itself.

Thanks once again @orizi !
