### ISSUE TITLE
bug: VS Code extension is unable to display the type of a `felt252` variable if there's an unrelated assignment error on-screen

### ISSUE THREAD

**Issue by misicnenad** [starkware-libs/cairo#5874]
# Bug Report

**Cairo version:**
```console
scarb 2.6.4+nightly-2024-06-22 (5deb60ac1 2024-06-22)
cairo: 2.6.4 (f3af4cb8d)
sierra: 1.5.0
```
**Current behavior:**

If I create an implicit `felt252` variable (no explicit type):
```rust
let felt_var = 1;
```
and hover over it, I will see the correct and expected type, which is `felt252`.
![image](https://github.com/starkware-libs/cairo/assets/19427053/92567664-2953-4976-834f-2f06eff00ce8)

But if I add another assignment above/below this, and this assignment is wrongful, then hovering over the `_f` variable no longer displays the correct type.
E.g. for the following code:
```rust
    let _f = 1;
    let bool_var: bool = 1; // mismatched types error
```
![image](https://github.com/starkware-libs/cairo/assets/19427053/013198e2-7417-4e91-ae4b-c807fddc9ec3)

But if I specify the type of `_f`, then hovering over it displays the appropriate type:
![image](https://github.com/starkware-libs/cairo/assets/19427053/dba262e5-5cec-4762-be07-0be7005cdac0)

Interestingly, this is not an issue for non-felt252 types:
![image](https://github.com/starkware-libs/cairo/assets/19427053/102a90c6-9b85-4de1-bfb6-cf4a4468cb90)
![image](https://github.com/starkware-libs/cairo/assets/19427053/6941e0ec-142a-4ccb-af99-911f29d33215)
![image](https://github.com/starkware-libs/cairo/assets/19427053/11c28365-83d8-47b1-b0e6-a52d67588bde)

This issue also does not appear if the error on-screen is not assignment or mismatched type-related.
E.g. here's code that has a missing `;` at the end of the line - notice that the correct type is being displayed on hover:
![image](https://github.com/starkware-libs/cairo/assets/19427053/edc5503e-9cb1-4c3b-b463-d406cad7a117)

**Expected behavior:**

VS Code extension should be able to display the correct type when hovering over a variable with an implicit `felt252` type, while there's a mismatched type error, or any other assignment error on-screen.

**Steps to reproduce:**

- create new project
- open _lib.cairo_
- type:
```rust
    let _f = 1;
    let bool_var: bool = 1;
```
- hover over `_f`
- **Popup appears with content `Type: ?0`**

**Related code:**

```rust
    let _f = 1; // hovering over this variable displays `Type: ?0`
    let bool_var: bool = 1; // mismatched types
```

**Comment by orizi** [comment]
This is part of the system - since the auto-inference of variables is up to a point, some error may cause other types to not be fully known.

specifically more so in your example - only upon inference finalization we assign unknown numeric types to be `felt252`s - since finalization failed - this have not yet happened, and the type *is* actually unknown.

**Comment by misicnenad** [comment]
@orizi this is still very unintuitive behavior, it would be much better to always have the type no matter if/where some unrelated error is.
Without knowing the context you provided, this will most likely seem like a bug to other Cairo developers as well. Especially since it only occurs in a specific edge case, and in other cases this behaves as expected.
