### ISSUE TITLE
feat: Add a compiler flag to turn off inlining

### ISSUE THREAD

**Issue by javra** [starkware-libs/cairo#5896]
# Feature Request

**Describe the Feature Request**

We (Lindy Labs) would love to have a compiler flag for the Cairo to Sierra compiler which disables inlining globally, i.e. acting as every function had an `#[inline(never)]` decorator.

**Describe Preferred Solution**

Have a flag like `replace-ids` to disable inlining globally.

**Describe Alternatives**

Currently we're emulating this feature by a naïve search and replace run which adds the decorators everywhere, but that's not a very nice workflow.

**Additional Context**

We're using the generated `.sierra` file in our tool [Aegis](https://github.com/lindy-labs/aegis) in order to give formal specifications for Cairo functions and verify them in the theorem prover Lean. In order for the specs to be more modular, turning off inlining is required, otherwise treating the inlined code causes lots of repeated boiler plate code in the correctness proofs (when proving manually) or unnecessary checking time (when proving automatically).

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by orizi** [comment]
do note that `inline(always)` can never be removed - as we sometimes actually have to do it.

but for the other cases that can definitely be configured that the `should inline` heuristic will simply always return `no`.

**Comment by javra** [comment]
In what cases can't it be removed? (We already remove it in our code before extracting the Sierra that's the basis for formalization) We don't do exact semantics of gas costs, so if the semantics only differs there, we don't worry.

> but for the other cases that can definitely be configured that the should inline heuristic will simply always return no.

Sounds good :)

**Comment by orizi** [comment]
it doesn't matter - `always` means `always` (although there are specific cases where we actually have to rely on it).
if some repo wants to have proper support for this - it should not `always` something when they don't actually mean it.

**Comment by javra** [comment]
Obviously in order to produce the Sierra code that's extracted for FV purposes we'd like to ignore semantically irrelevant `inline(always)` annotations, in *all* repos, because even if the annotation makes sense for running/testing/deploying the Cairo code, it might still not make sense for Aegis.

But I see your point. I started to implement a flag that doesn't touch the functions marked as `inline(always)`.

**Comment by javra** [comment]
PR is at #5911
