### ISSUE TITLE
Insert right paren after cursor when completing funciton/method calls

### ISSUE THREAD

**Issue by mkaput** [starkware-libs/cairo#5935]
Currently, LS is completing functions/methods like this:

```rust
// before
x.<caret>

// after
x.foo(<caret>
```

Change this to work as following:

```rust
// before
x.<caret>

// after
x.foo(<caret>)
```

Code to update:

https://github.com/starkware-libs/cairo/blob/cdaceb909ccf0644b7e385669d2c48417ceb90d4/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L285

**Comment by kaksv** [comment]
Is this issue still open?

**Comment by mkaput** [comment]
There is #5956 in review that attempts to implement this

**Comment by kaksv** [comment]
Alright i had created a PR but let me look into something else.

**Comment by mkaput** [comment]
#5956 was cancelled so this is up for grabbing again

**Comment by oluwa-peski** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/cairo-compiler).

### My background and how it can be leveraged
I have experience with Rust and Cairo as well. I'm interested in contributing to the Cairo Compiler as that would provide more understanding Cairo

### How I plan on tackling this issue
I'll update the snippet in cairo/crates/cairo-lang-language-server/src/ide/completion/completions.rs that does the completion and write tests to verify

**Comment by mkaput** [comment]
@oluwa-peski feel free to submit a PR :)

I won’t be assigning anybody to this PR due to how it looked so far

**Comment by RuneRogue** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/cairo-compiler).

### My background and how it can be leveraged
I am a blockchain and DeFi developer . I am having experience of 8 months . I am currently working as a Blockchain Researcher and Developer. My Experience in programming language like Go , Rust , Java will help me to solve this issue.
