### ISSUE TITLE
Provide intention to fill trait members

### ISSUE THREAD

**Issue by mkaput** [starkware-libs/cairo#5944]
Implement the following intention in CairoLS:

![Image](https://github.com/starkware-libs/cairo/assets/3450050/b8209d79-e522-4ed4-ba72-d2acf5014e6a)

**Comment by LamsyA** [comment]
hello @mkaput  Kindly provide the link to this in the codebase.

**Comment by mkaput** [comment]
Hey! Same store as in #5945 

Here's the starting point: https://github.com/starkware-libs/cairo/blob/cdaceb909ccf0644b7e385669d2c48417ceb90d4/crates/cairo-lang-language-server/src/ide/code_actions/mod.rs#L34-L78

You can follow the implementation of unused variable intention as the hooking point. First, you need to assign an error code to this particular diagnostic; you can `grep` for it by error message.

You will need to get information about struct members. This is provided in the `SemanticGroup` (this trait-Salsa group is implemented by `AnalysisDatabase`) by this query: https://github.com/starkware-libs/cairo/blob/50d465cd4facb6742f72d3d43f87378ebd92e13f/crates/cairo-lang-semantic/src/db.rs#L233-L238

**Comment by mkaput** [comment]
@LamsyA any progress? how can I help?
