### ISSUE TITLE
dev: improve diagnostic on accounts contracts

### ISSUE THREAD

**Issue by enitrat** [starkware-libs/cairo#6040]
Having an `__execute__` in a regular contract results in:

```
warn: Plugin diagnostic: Failed to generate ABI: `__execute__` is a reserved entry point names for account contracts only.
 -->wallet.cairo:73:5
    #[abi(embed_v0)]
```

It's not straightforward to understand that the contract should be marked as `#[starknet::contract(account)]` instead. Perhaps the warning message can be improved with this hint.

**Comment by orizi** [comment]
Was merged into `dev-v2.7.0` - would be fixed at next release and then at `main` and nightly build as well.
