### ISSUE TITLE
bug: accessing member of storage struct named "address" conflicts with storage address

### ISSUE THREAD

**Issue by enitrat** [starkware-libs/cairo#6067]
# Bug Report

**Cairo version:**
2.7.0-rc3

**Current behavior:**

**Expected behavior:**

Consider the following contract
```
    #[storage]
    struct Storage {
        owner: Person,
    }
    
     #[derive(Drop, Serde, starknet::Store)]
    pub struct Person {
        address: ContractAddress,
        name: felt252,
    }
    
     fn get_owner_address(self: @ContractState) -> ContractAddress {
        self.owner.address.read()
    }
    
     fn get_owner_name(self: @ContractState) -> felt252 {
        self.owner.name.read()
    }
}
 ```
 
 It is not possible to access the `address`field of the owner: Person storage struct, as it conflicts with the storage's var actual address.
 
 Proposal: make `address` private and access it with a function `address()`.

**Comment by orizi** [comment]
Is this correct for all editions?
2024_07 as well?

**Comment by enitrat** [comment]
will double check with last edition

**Comment by orizi** [comment]
no need  -it would not work - we are making sure to have only "__special_names__" for all the transparent structure members, to not disallow actual member usages.

Thanks!
