### ISSUE TITLE
Implement `//!` comments

### ISSUE THREAD

**Issue by mkaput** [starkware-libs/cairo#6080]
Add support for `//!` comments that are handled analogously to Rust ones. Follow implementation of `///` comments.

**Comment by MayowaObisesan** [comment]
Hey @mkaput 
I'll like to take up this issue.
Can you provide more context to this issue? like where can I find the implementation of `///`

**Comment by mkaput** [comment]
https://github.com/starkware-libs/cairo/blob/e60c298fd7a10c4e40a63a066f25e972417a6847/crates/cairo-lang-doc/src/db.rs#L25

you will need to test this. up to you how you'll implement such tests

**Comment by wawel37** [comment]
Hi, would like to work on that, as it's needed inside the scarb ([issue](https://github.com/software-mansion/scarb/issues/1439)).
