### ISSUE TITLE
bug(language-server): invalid placement of diagnostics when original item is replaced

### ISSUE THREAD

**Issue by glihm** [starkware-libs/cairo#6117]
# Bug Report

**Cairo version:**

`2.7.0-rc.3`

**Current behavior:**

When a plugin generate code by replacing the original item with a new rewritten node, the diagnostics are well generated by the compiler, but the language server doesn't show it correctly in the editor panel.

<img width="562" alt="image" src="https://github.com/user-attachments/assets/9d78689c-8307-41bf-a317-4b36d6d1b5b2">

As seen in the image, the invalid statement is correctly seen by the compiler and mappings look correct, but the language server doesn't display it correctly on the editor panel.
Also, clicking on the error in `PROBLEMS` tag redirects to a file that actually contains the contract code expanded after compiler plugins passe.

<img width="686" alt="image" src="https://github.com/user-attachments/assets/87d4a914-0b59-47f1-ad63-ce6c32444eb1">

Interestingly, the diagnostics generated by the plugin itself are correctly mapped as shown in the image below:

<img width="563" alt="image" src="https://github.com/user-attachments/assets/f09b8c59-7890-4053-8b71-4145a63c849b">

**Expected behavior:**

The diagnostics generated by the compiler, inside a plugin code, must be shown correctly on the editor panel.

Also, the `go to definition` is not working in this situation (for any item).

**Steps to reproduce:**

An MRE is set here: https://github.com/glihm/cairo_plugin_demo
With:
* details in the README to setup VSCode and compiled extension.
* custom compiler.
* custom plugin.
* custom language server using the tricks to start it.

**Related code:**

Not sure of the exact location in the `lib.rs` where the problem can be. The mappings are correctly shown in the `PROBLEMS` tab, with correct lines on the file edited by the user.

Also, the starknet plugin only replaced the original item to actually remove it. But most of the time, the original item is not removed and only additional code is added.

**Other information:**

We've faced this in Dojo, and the current MRE only uses the minimal code to reproduce the problem. Also the custom compiler is here to output the expanded source code for easier debugging.

**Comment by glihm** [comment]
Thanks for the work on this @Arcticae! However, it seems that the proposed PR is not actually fixing the issue. Currently tested with `2.8.4` as before we had some compiler incompatibility that prevented the testing.

To reproduce:

1. Clone https://github.com/dojoengine/dojo-core on the branch `feat/cairo-2.8.4`.
2. Build the language server: `cargo build -r --bin dojo-language-server`.
3. Open `lib.cairo` inside `examples/dojo_simple`, and you'll see that the diagnostics are still not showing correctly when using the LS.

Would be happy to help with some pointers as it's crucial for Dojo users to have LS fully functional. 👍

**Comment by mkaput** [comment]
discussed this offline; the fix will land in Cairo 2.9
