### ISSUE TITLE
New Project Model MVP

### ISSUE THREAD

**Issue by mkaput** [starkware-libs/cairo#6124]
## Problem

The current way of getting knowledge about opened projects in CairoLS is very wrong and needs to be redone. All the issues are widely known, no need to repeat them here 🙃 

Existing source:

https://github.com/starkware-libs/cairo/blob/0f0f721f3f9d28f56cc519c4277fde67d0d03934/crates/cairo-lang-language-server/src/lib.rs#L566-L623

## Goals

Let's call a **Project Model** a system that stores what files belong to what crates/workspaces/projects and uses this information to populate `AnalysisDatabase` inputs.

1. Refreshes when `Scarb.toml`/`Scarb.lock` change. Mind that it is better to make an unnecessary refresh than not to do it and work on a stale workspace state!
2. #6235
3. Calls `scarb metadata` asynchronously, as this is a network-bound long-running process. More details in: #6128.
4. Avoids calling `scarb metadata` if another instance is already running (but if one is running: always schedule at most 1 extra run to pick any changes that could happen while the previous run was running).
5. It is capable of handling files/projects that are removed/renamed.
6. ~~Handles detached files well (i.e. one without matching `Scarb.toml`/`cairo_project.toml` well).~~ Do the same as Rust Analyzer does.
7. It gracefully deals with projects which loading fails. In such cases, avoid clearing relevant salsa inputs to preserve as much cached queries as possible. For example, a syntax error in the manifest file (this will make `scarb metadata` fail) shouldn't cause wiping of all analysis state. Check out what RA does here.
8. It is implemented in such a way, that when doing #6132 we won't have to change a lot here. Primarily, this means that this system should escape async world as early as possible.
6. _Reacts to [workspace folders](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_workspaceFolders) requests as primary source of information on what is opened._ #6127 
7. _Sends actionable notifications to the user when something fails instead of just logging errors._

## Viable implementation framework

The project model should be modelled as a black box that reacts to various events in LSP:
- Filesystem operations:
  - `on_file_opened`,
  - `on_file_changed`,
- Configuration changes: `on_config_changed`,
- Manual reloads: `reload`.

As an output of processing these events, this box should make updates to the `AnalysisDatabase` inputs with the new state of projects.

The New Project Model V2 branch has a reasonable abstraction laid out.

## References

@mkaput already made two failed attempts to implement this. I recommend checking out this code because a lot is done great here anyway. Especially, means of testing are worth checking out.

- https://github.com/starkware-libs/cairo/compare/mkaput/new-project-model-v1?expand=1
- https://github.com/starkware-libs/cairo/compare/mkaput/new-project-model-v2?expand=1

---

This task is spin off #5355

**Comment by Arcticae** [comment]
Can we clarify here:
1. What needs to be achieved
2. By what means we want to achieve it
🙏

**Comment by mkaput** [comment]
Archiving this issue as we converted it into a milestone: https://github.com/starkware-libs/cairo/milestone/3
