### ISSUE TITLE
Implement hovers for variables in the new style

### ISSUE THREAD

**Issue by Arcticae** [starkware-libs/cairo#6156]
The target is to move this functionality from "legacy hover" to our new hover logic
The final outcome should be more verbose and include the documentation, just like the `render::definition` hover

**Comment by mkaput** [comment]
I'd say, just follow what Rust Analyzer does:

<img width="352" alt="image" src="https://github.com/user-attachments/assets/819ec9d4-bc0b-4f7f-b84c-d568cb091045">

**Comment by mkaput** [comment]
this actually duplicates #5826
