### ISSUE TITLE
Implement hover for literals

### ISSUE THREAD

**Issue by Arcticae** [starkware-libs/cairo#6157]
Currently, hovering is only supported for `TerminalIdentifier`, while there are multiple `Expr`essions that are not supported there:

- Literal
- ShortString
- String
- False
- True

(possibly more?)
After hovering, we want to display the type info in the appropriate form (new hover style)

**Comment by mkaput** [comment]
For short strings/strings we might also want to show their numeric value (basically bring https://www.stark-utils.xyz/converter into LS)
