### ISSUE TITLE
Searching for Scarb installed via ASDF fails

### ISSUE THREAD

**Issue by mkaput** [starkware-libs/cairo#6163]
https://t.me/cairo_ls_support/76
https://t.me/cairo_ls_support/41

user found a workaround: https://t.me/cairo_ls_support/81

we have no reliable reproduction right now. people reported this when upgrading from 2.6.4 to 2.7.0

**Comment by mkaput** [comment]
I think there's a chance #6176 will fix this cc @Arcticae

**Comment by Arcticae** [comment]
Yes - i actually can remove the path to scarb binary and it works now with asdf

**Comment by mkaput** [comment]
ok, unassigning and connecting this issue with that PR
