### ISSUE TITLE
LS: Inline macro expand should check for `ModuleItem`s in expanded code

### ISSUE THREAD

**Issue by Draggu** [starkware-libs/cairo#6181]
Currently attribute macros are resolved first then inline ones. We should change it to work with inline macro returning code with attribute macros

**Comment by orizi** [comment]
I don't understand the bug - procedural macros run on the textual representation and reorder it, inline macros run later in the semantic run.

**Comment by mkaput** [comment]
@Draggu is this still relevant given our latest research conclusions in this area?

**Comment by Arcticae** [comment]
Inline macro expansion on top-level It's not supported in cairo, closing
