### ISSUE TITLE
bug: pop_log failed with ByteArray event key.

### ISSUE THREAD

**Issue by remybar** [starkware-libs/cairo#6186]
# Bug Report

**Cairo version:**

2.7.0

**Current behavior:**

The function `starknet::testing::pop_log` does not detect the emitted event when this event has a `ByteArray` field event key, like:
```rust
    #[derive(Drop, starknet::Event, Debug, PartialEq)]
    pub struct MyEvent {
        #[key]
        pub name: ByteArray,
        pub addr: ContractAddress,
    }
``` 

The `pop_log` function returns `None`.

**Expected behavior:**

The emitted event should be detected correctly.

**Steps to reproduce:**

I reproduced the issue in a small project: https://github.com/remybar/starknet-pop_log-bug

**Other information:**

**Comment by orizi** [comment]
you are popping the wrong event type.

`starknet::testing::pop_log` should only return contract level events.
you are trying to return an inner variant event from it.

**Comment by remybar** [comment]
> you are popping the wrong event type.
> 
> `starknet::testing::pop_log` should only return contract level events. you are trying to return an inner variant event from it.

Haaa, yes ! So I have to write `Option::Some(simple_contact::Event::MyEvent(simple_contact::MyEvent { addr: caller, name: "John Doe" }))` instead of `Option::Some(simple_contact::MyEvent { addr: caller, name: "John Doe" })` !

Thanks @orizi ! 🙏
