### ISSUE TITLE
dev: Improve diagnostics for wrong component embeddable name

### ISSUE THREAD

**Issue by barak-b-starkware** [starkware-libs/cairo#6221]
Within a starknet contract piece of code, if I use a component as follows:
```
#[abi(embed_v0)]
impl InternalName = SomeComponent::EmbeddableAsName<ContractState>;
```
and the `EmbeddableAsName` is wrong, I get and error: `Trait not found.` it appears at the top of the contract where `#[starknet::contract]` is placed.
IMO, It should imply which trait is not found or at least point to the component that caused the error.

**Comment by orizi** [comment]
Is this the only diagnostic you get?
