### ISSUE TITLE
bug: cairo-format interferes with Cairodoc

### ISSUE THREAD

**Issue by enitrat** [starkware-libs/cairo#6231]
# Bug Report

**Cairo version:**
2.7.1

**Current behavior:**
Running Cairo-format will format the `//! COMMENT` cairodoc lines

See example:
<img width="1274" alt="image" src="https://github.com/user-attachments/assets/19318f29-5b8d-46aa-afd7-e757d0e486f3">

**Comment by mkaput** [comment]
FYI `//!` comments are not supported in cairo doc yet, there are open issues for this #6080 and https://github.com/software-mansion/scarb/issues/1439
