### ISSUE TITLE
dev: move assert_eq! and others out of the `test` module hierarcy

### ISSUE THREAD

**Issue by tdelabro** [starkware-libs/cairo#6233]
`assert_eq`, `assert_le`, and so on are defined in the `corelib/src/test/test_utils.cairo`.

I would like to be able to use them in my production code (not my tests) without having to import anything whose path contains the word "test".
It is misleading, as they are just more readable wrappers of code that is totally fine to use in a non `test` context

**Comment by orizi** [comment]
it is not there on purpose.
As it actually has different meaning - as it will make the specific generated string of the comparison part of contracts - which is not a thing we want to make people do by mistake.

**Comment by tdelabro** [comment]
I don't get your point.
What would be wrong with writing
```cairo
assert_eq!(a, b, "a != b");
```
instead of 
```cairo
assert!(a == b, "a != b");
```
in non `test` code.

How come using `assert` you don't end up "making the specific generated string of the comparison part of contracts" while you will using `assert_eq!`, when `assert_eq` is just an inlined sugary wrapper over an `assert` expression.

**Comment by orizi** [comment]
because this is not the actual panic string of `assert_eq(a, b, "a != b");`.

it would actually be: (assuming `a == 1` and `b == 2`)
```
assertion `a == b` failed: a != b
a: 1
b: 2
```

**Comment by tdelabro** [comment]
How come it is not the case for `assert!(a == b, "a != b");` too?

I can't see in the code where those are treated differently:
```cairo
#[inline]
pub fn assert_eq<T, +PartialEq<T>>(a: @T, b: @T, err_code: felt252) {
    assert(a == b, err_code);
}

...

#[inline(always)]
pub fn assert(cond: bool, err_code: felt252) {
    if !cond {
        panic_with_felt252(err_code)
    }
}
```

The code reads as if both end up with the exact same actual code inlined.
