### ISSUE TITLE
Call detect_crate_for whenever project manifest file is saved

### ISSUE THREAD

**Issue by mkaput** [starkware-libs/cairo#6236]
Refreshes when `Scarb.toml`/`Scarb.lock` is saved. Mind that it is better to make an unnecessary refresh than not to do it and work on a stale workspace state!

**Comment by piotmag769** [comment]
It seems that it already works for `Scarb.toml` 🤔 At least for me

**Comment by mkaput** [comment]
but it doesn't listen for `Scarb.lock` nor `cairo_project.toml`: https://github.com/starkware-libs/cairo/blob/85275d9efa2d36dc60798f0a849477f9afc55217/crates/cairo-lang-language-server/src/lib.rs#L736

I know you have to apply this change **at least**:
https://github.com/starkware-libs/cairo/compare/main...mkaput/new-project-model-v2#diff-ab83b8926900a6d4779007745456106fcd20f62e7b951a303b1b233967074705R668-R678

**Comment by piotmag769** [comment]
Partially solved by #6316, `Scarb.lock` is todo
