### ISSUE TITLE
Send actionable notification whenever something fails in project model

### ISSUE THREAD

**Issue by mkaput** [starkware-libs/cairo#6239]
When something fails in project model code, send a notification to the user instead of just logging an error.

See all TODO comments that look like this one:
https://github.com/starkware-libs/cairo/blob/0f0f721f3f9d28f56cc519c4277fde67d0d03934/crates/cairo-lang-language-server/src/lib.rs#L583

**Comment by Arcticae** [comment]
@piotmag769 please link a PR

**Comment by piotmag769** [comment]
#6596
