### ISSUE TITLE
feat: `cairo-format` option to target a specific file.

### ISSUE THREAD

**Issue by enitrat** [starkware-libs/cairo#6260]
# Feature Request

**Describe the Feature Request**
Following #4134, for integration with external tools, `cairo-format` should have an option to take a specific file as a target, instead of formatting the entire package all at once.

For reference, with the old CairoZero `cairo-format`, we could do `cairo-format ${target}` which would format one specific file.
Forge (foundry) supports `forge fmt ${target} --check` as well. This works great for integration with lint aggregators.

**Describe Preferred Solution**

Add an _optional_ `target` argument, referring to the file to format. The command `scarb fmt ${target} -e stdout` should be valid. If a target is specfied, the name of the file being formatted is not part of the stdout.

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by enitrat** [comment]
So I was looking into how to implement this and it looks like `cairo-format` actually has this feature

```
❯ cargo run --bin cairo-format -- --help
Formats a file or directory with the Cairo formatter.
Exits with 0/1 if the input is formatted correctly/incorrectly.

Usage: cairo-format [OPTIONS] [FILES]...

Arguments:
  [FILES]...  A list of files and directories to format. Use "-" for stdin

Options:
  -c, --check                 Check mode, don't write the formatted files, just output the diff between the original and the formatted file
  -r, --recursive             Format directories content recursively
  -v, --verbose               Print verbose output
  -p, --print-parsing-errors  Print parsing errors
  -s, --sort-mod-level-items  Enable sorting the module level items (imports, mod definitions...)
  -h, --help                  Print help
  -V, --version               Print version
  ```
  
  However it's not shown when doing `scarb fmt --help`
  
  ```
  Usage: scarb fmt [OPTIONS]

Options:
  -c, --check                  Only check if files are formatted, do not write the changes to disk
  -e, --emit <EMIT>            Emit the formatted file to stdout [possible values: stdout]
  -v, --verbose...             Increase logging verbosity.
      --no-color               Do not color output
  -q, --quiet...               Decrease logging verbosity.
  -p, --package <SPEC>         Packages to run this command on, can be a concrete package name (`foobar`) or a prefix glob (`foo*`) [env: SCARB_PACKAGES_FILTER=] [default: *]
      --verbosity <VERBOSITY>  Set UI verbosity level by name. [env: SCARB_UI_VERBOSITY=]
  -w, --workspace              Run for all packages in the workspace
  -h, --help                   Print help
  ```
  
  Delegating this to the scarb team

**Comment by orizi** [comment]
indeed - should be opened on scarb. closing here.
