### ISSUE TITLE
feat: print hexadecimal values

### ISSUE THREAD

**Issue by enitrat** [starkware-libs/cairo#6261]
# Feature Request

**Describe the Feature Request**
Most of the times, the values we're working with are hashes, classes, addresses, etc. Having them displayed in decimal is not very useful as we often debug / compare hex values. I have a python script on the side that captures the output and converts all values to hexadecimal.

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by AbdelStark** [comment]
I second this strongly

**Comment by orizi** [comment]
As stated in the attached PR - `format!("{:x}", value)` is now supported, which should mostly be enough.
