### ISSUE TITLE
bug: compilation fails with no diagnostics

### ISSUE THREAD

**Issue by enitrat** [starkware-libs/cairo#6270]
# Bug Report

**Cairo version:**
2.7.1

**Current behavior:**

This function was wrongly implemented: code_hash should be `Option::None`, not `None`.

source: https://github.com/kkrt-labs/kakarot-ssj/blob/bug-no-diagnostic/crates/evm/src/model/account.cairo#L38

```
    fn new(address: Address) -> AccountBuilder {
        AccountBuilder {
            account: Account {
                address: address,
                code: [].span(),
                nonce: 0,
                balance: 0,
                selfdestruct: false,
                is_created: false,
                code_hash: None
            }
        }
    }
```

Trying to compile fails with:

```
❯ scarb build -p contracts
   Compiling lib(contracts) contracts v0.1.0 (/Users/msaug/kkrt-labs/kakarot-ssj/crates/contracts/Scarb.toml)
error: Compilation failed without any diagnostics
error: could not compile `contracts` due to previous error
```
**Expected behavior:**

There should be a compilation error with a clear diagnostic.

```
❯ scarb build
   Compiling tmp v0.1.0 (/Users/msaug/workspace/sandbox/tmp/Scarb.toml)
error: Identifier not found.
 --> /Users/msaug/workspace/sandbox/tmp/src/lib.cairo:317:28
                code_hash: None
                           ^**^
```

However, after isolating these parts, I was not able to re-trigger this issue.

Interestingly, the LS detects it:

<img width="400" alt="image" src="https://github.com/user-attachments/assets/e4515d20-3818-4b27-8888-03e3460df787">

**Comment by orizi** [comment]
This is the exact same scarb bug reported at #6264.

Please run `scarb test`.

**Comment by enitrat** [comment]
How can I know if a bug is from scarb / cairo to open an issue in the right place?

**Comment by orizi** [comment]
For this one specifically it exists somewhere in the seam between Scarb and Cairo - I closed it only because it is a duplicate.

If we decide it is only a scarb issue - would close the other one here as well.
I agree it is sometimes difficult to know.
in general - "bad diagnostic / missing diagnostic / compiler crash" tend to be here, while crate management would tend to be on scarb.
