### ISSUE TITLE
feat: allow importing all items of a module with *

### ISSUE THREAD

**Issue by enitrat** [starkware-libs/cairo#6301]
# Feature Request

**Describe the Feature Request**

Allow this feature:

```rust
fn f(){}
fn h(){}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_f(){
       f()    
    }
 }
 ``` 
 
 This would reduce a lot the amount of LOC required to simply have all the required items to perform unit tests. The requirement to handle manually all imports to day is a deterrent to implement a proper module-based structure for unit tests

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by feltroidprime** [comment]
+1

**Comment by orizi** [comment]
Done on 2.9.0 already.
