### ISSUE TITLE
LS: Investigate `IndexMap: key not found` error

### ISSUE THREAD

**Issue by Draggu** [starkware-libs/cairo#6374]
Sometimes LS reports errors like this

>thread 'main' panicked at crates/cairo-lang-defs/src/db.rs:585:15:
>IndexMap: key not found

>thread 'main' panicked at crates/cairo-lang-defs/src/db.rs:289:75:
>IndexMap: key not found

errors have different origins but this always happens when indexing.

Find out why this is happening and if is this LS or compiler error

**Comment by Arcticae** [comment]
@piotmag769 please verify if it's done

**Comment by piotmag769** [comment]
Done in #6529
