### ISSUE TITLE
bug: Language server crash (Debian Bookworm)

### ISSUE THREAD

**Issue by VVander** [starkware-libs/cairo#6382]
# Bug Report

**Cairo version:**

scarb 2.8.2 (a37b4cbfc 2024-09-09)
cairo: 2.8.2 (https://crates.io/crates/cairo-lang-compiler/2.8.2)
sierra: 1.6.0

**Current behavior:**

Language server crashes on opening (or sometimes modifying) a .cairo file. Errors like this are displayed: 
![image](https://github.com/user-attachments/assets/a0bc11bb-066a-451d-b1db-6e06b3cd4141)

This appears to be the most relevant line in the logs (full logs attached): 
```
thread 'main' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/rust-analyzer-salsa-0.17.0-pre.6/src/derived/slot.rs:301:21:
assertion failed: old_memo.revisions.changed_at <= revisions.changed_at
```

**Expected behavior:**

Language server does not crash :upside_down_face: 

**Steps to reproduce:**

Simply opening a project in my environment. I'm using a Debian Bookworm [dev container](https://containers.dev/), so the environment is easily reproduceable:

- [Dockerfile.txt](https://github.com/user-attachments/files/17017274/Dockerfile.txt)
- [setup.txt](https://github.com/user-attachments/files/17017278/setup.txt)

**Other information:**

Full logs: 
[langserver_log.txt](https://github.com/user-attachments/files/17017230/langserver_log.txt)

**Comment by Arcticae** [comment]
Should be fixed with #6319 (to be released with next cairo release)
Closing
