### ISSUE TITLE
LS: Conflicting dependencies in packages

### ISSUE THREAD

**Issue by Arcticae** [starkware-libs/cairo#6391]
## Given:
- package A (opened in VSC with LS)
- package B (a dependency of A)
- package C (a dev dependency of both A and B, but in different versions ver. A/ ver. B)

## Scenario:
1. Navigate to tests of A (GOTO to dev dependency works correctly, analysis returns correct types)
2. Navigate to B (package is resolved, the C dep is loaded with ver. B)
3. Errors in A (can) appear because of differing versions (C ver. B was loaded instead of C ver. A)

## Example
This error can appear in a very simple setup, where you have a dep on OpenZeppelin, it tests with snfoundry 0.27.0, and you do with 0.30.0 (which is totally fine from scarb/snforge perspective - it runs correctly)

The example above appears here:
https://github.com/Sniezka1927/starknet-sc/commit/6e8a95cb68316f47a09c675aabc004ac8fc6a84f

**Comment by mkaput** [comment]
@Arcticae please test whether this task is still relevant

**Comment by piotmag769** [comment]
Verified that it was solved with discriminator field
