### ISSUE TITLE
bug: Wrongly mapped diagnostics in LS

### ISSUE THREAD

**Issue by Arcticae** [starkware-libs/cairo#6394]
The diagnostics are being refreshed for VFS files again, which leads to wrongly mapping them to VFS files instead of user code

Example:

![image](https://github.com/user-attachments/assets/d65aaa37-9c53-4980-90d7-4afe65602862)

**Comment by orizi** [comment]
I would not consider it `Wrongly` mapped - it is just also mapped for the VFS file.

we can rather easily make it actually point to the error within the generated file if it was opened (by stopping the remapping upon getting to the generated file)
