### ISSUE TITLE
feat: prevent usage of enums without a default variant in storage

### ISSUE THREAD

**Issue by enitrat** [starkware-libs/cairo#6422]
I think enums without a default variant should throw an error at compile time if they try to derive `starknet::Store` - otherwise, attempting a storage read on an uninitialized slot will cause a runtime panic. 

See description in https://github.com/cairo-book/cairo-book/issues/990

**Comment by orizi** [comment]
But why is that an issue specifically? it is the decision of the contract writer to know they only are reading valid values.

adding a diagnostic now may even be more confusing - even possibly marking any of the *existing* keys as `#[default]` causing a storage layout change.

(not saying no - just want to make sure the cure is better than the disease)

**Comment by enitrat** [comment]
>  it is the decision of the contract writer to know they only are reading valid values.

I consider it an issue because I don't think reading a value from storage should default to a panic if that value is not set. By ensuring a default variant exists, you are leveraging the compiler so that:
- You catch eventual errors at compile time by forcing a variant to act as the default one - if required, the contract creator can just add a `None` variant that fulfills this role.
- You force the definition of a type associated to an empty storage
- You can "clear" an enum in storage by resetting it to the default variant
- Contract creator might not now about this default panic scenario (as reported in the issue) - I actually did not even know about this.
