### ISSUE TITLE
feat: function pointers

### ISSUE THREAD

**Issue by enitrat** [starkware-libs/cairo#6452]
A great feature for us at Kakarot, that would reduce step usage by ~5% would be to have a way to have a const-array filled with function pointers, and be able to do something like:

```
fn execute_opcode(opcode_number: u8){
  let function_ptr = OPCODES[opcode_number];
  return function_ptr();
}
```

currently we do like

```
fn execute_opcode(opcode_number: u8){
        if opcode == 0x00 {
            // STOP
            return Result::Ok(self.exec_stop());
        }
        if opcode == 0x01 {
            // ADD
            return self.exec_add();
        }
        if opcode == 0x02 {
            // MUL
            return self.exec_mul();
        }
}
```

which, when executing thousands of opcodes, can represent a non-marginal part of the computation.

**Comment by feltroidprime** [comment]
match pattern is more optimized than a sequence of ifs from my xp

**Comment by enitrat** [comment]
> match pattern is more optimized than a sequence of ifs from my xp

indeed, looks like its about ~ twice better (40k -> 20k steps in my reference profiling)

**Comment by orizi** [comment]
as @feltroidprime said - for the specific usecase -
```
match value {
  0 => self.handle_0(),
  1 => self.handle_1(),
  2 => self.handle_2(),
  3 => self.handle_3(),
  _ => panic!("unsupported"),
}
```
would be more efficient in the cases you have many opcodes.
function pointers would be a lot more work - and are not planned any time soon (unlike closures which are really close to being released).
