### ISSUE TITLE
VSCode statusbar widget

### ISSUE THREAD

**Issue by mkaput** [starkware-libs/cairo#6474]
Add statusbar widget that:
1. would report currently used Scarb/Cairo/Sierra version (i.e. scarb --version output), similar to the [one available in Ruby extension](https://code.visualstudio.com/docs/languages/ruby#_check-your-installation)
2. would report LS state, like Rust Analyzer

![Image](https://github.com/starkware-libs/cairo/assets/3450050/8bee4e1b-7bfa-441e-b43a-9f65b408d693)

![Image](https://github.com/starkware-libs/cairo/assets/3450050/8e35fa3c-e240-4d4f-8975-426e4689dddb)

**Comment by marcuspang** [comment]
@mkaput I'm currently just displaying version in the tooltip, is there anything else you would like to add?

Clicking on it brings you to the LSP logs too, similar to rust-analyzer

https://github.com/starkware-libs/cairo/pull/6497

**Comment by mkaput** [comment]
that's awesome! @Arcticae is working on a system of publishing LS status, so nothing more to work on currently 😄
