### ISSUE TITLE
feat: Add a link for a recommented VSCode extension somewhere

### ISSUE THREAD

**Issue by alcueca** [starkware-libs/cairo#6539]
# Feature Request

**Describe the Feature Request**

There have been a few supply chain attacks lately in VSCode extensions, but a VSCode extension for syntax highlighting helps a lot. It would be nice for newcomers to know which ones are safe or recommended

**Describe Preferred Solution**

A link somewhere, maybe in the tutorial, maybe in resources, that points out which VSCode Cairo syntax highligting extension is safe or preferred.

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

Yes

**Comment by mkaput** [comment]
looks like it's already linked in the Cairo Book: https://book.cairo-lang.org/ch01-01-installation.html#installing-the-vscode-extension
