### ISSUE TITLE
Compiler: Common macros don't have docstrings

### ISSUE THREAD

**Issue by integraledelebesgue** [starkware-libs/cairo#6541]
Macros like `panic!`, `assert!` or `assert_eq!` don't have docstrings we could show in their hovers.

**Comment by poolcleaner6** [comment]
Could you clarify which specific traits should have the use statements added in the Quick Fix? I'm interested in understanding the scope of this fix

**Comment by integraledelebesgue** [comment]
> Could you clarify which specific traits should have the use statements added in the Quick Fix? I'm interested in understanding the scope of this fix

I'm talking about hover displays that appear in the IDE. 

`print!` macro has a nice docstring that we display when user points at it with their cursor:
<img width="683" alt="obraz" src="https://github.com/user-attachments/assets/f872c8d9-9c95-4437-9652-4c8cf0c6ce2d">

On a contrary, `panic!`, `assert_eq!` and many others don't:
<img width="97" alt="obraz" src="https://github.com/user-attachments/assets/2b2d025d-51c7-4b5b-92c6-10943e4689e4">

Those macros lack docstrings because their corresponding representations in compiler use default implementation of `documentation` method from [this trait](https://github.com/starkware-libs/cairo/blob/974329af8965f750c27b677d84d973372bafbfe5/crates/cairo-lang-defs/src/plugin.rs#L148).
See [`print!` implementation](https://github.com/starkware-libs/cairo/blob/974329af8965f750c27b677d84d973372bafbfe5/crates/cairo-lang-semantic/src/inline_macros/print.rs#L68) vs. [`panic!` implementation](https://github.com/starkware-libs/cairo/blob/974329af8965f750c27b677d84d973372bafbfe5/crates/cairo-lang-semantic/src/inline_macros/panic.rs#L74)

**Comment by GradleD** [comment]
The function now checks for {} placeholders within the format string. If found, it prepares to handle formatted arguments.
rust
if format_str.find(['{', '}']).is_some() 

Processing Additional Arguments: The function collects additional arguments (skipping the first one, which is the format string) and attempts to extract their string values. If any argument cannot be extracted, the function returns false.

for arg in arguments.iter().skip(1) { // Skip the first argument (the format string)
    if let Some(arg_str) = try_extract_unnamed_arg(db, arg).and_then(|arg| arg.string_value(db)) {
        formatted_args.push(arg_str);
    } else {
        return false; // Invalid argument type
    }
}

**Comment by ryzen-xp** [comment]
Can I try solving this issue?

**Comment by mkaput** [comment]
PRs welcome 😃

**Comment by nehkee** [comment]
Would love to tackle this!

**Comment by Another-DevX** [comment]
GM.
I'll work on this, maybe you can assign to me this issue?

**Comment by mkaput** [comment]
@Another-DevX we're not assigning external contributors in this repo. Just submit PRs

**Comment by Another-DevX** [comment]
Got it!

**Comment by Krishn1412** [comment]
Could I try solving this?
