### ISSUE TITLE
Bug: Text edits for module imports break formatting

### ISSUE THREAD

**Issue by integraledelebesgue** [starkware-libs/cairo#6545]
# Bug Report

**Cairo version:**
2.9.0-dev.0 (`main`, `b9b90c55030315a5b997ccfb771f07e46e141ae9`)

**Current behavior:**

When providing completions of trait methods, LS automatically imports appropriate traits.
However, text edit happening upon auto-import destroys the code in terms of format.

Suppose we have following code:
```rs
mod some_module {
    pub trait SomeTrait<T> {
        fn foo(self: @T);
    }

    impl Ehh of SomeTrait<felt252> {
        fn foo(self: @felt252) {}
    }
}

mod some_other_module {
    fn bar() {
        let x = 0;
        x.fo<cursor>  // our cursor is here
    }
}
```

LS completes `foo` method and imports `SomeTrait`, resulting in the following code:

 ```rs
mod some_other_module {
    use super::SomeTrait;
fn bar() {
        let x = 0;
        x.foo()
    }
}
```

**Expected behavior:**

`fn` definition statement should be indented and perhaps separated from `use` statement by an empty line.

**Comment by Arcticae** [comment]
Closing in favor of #6584
