### ISSUE TITLE
bug: defining a struct by its member names in a different order than the definition is swapping field values 

### ISSUE THREAD

**Issue by feltroidprime** [starkware-libs/cairo#6623]
# Bug Report

**Cairo version:**

2.8.4

**Current behavior:**

Defining structs by their member names in a different order than the one in the struct definition is not respecting the member names when accessing them later on.

**Expected behavior:**

struct members should follow argument names, the compiler should re-order them when a struct is created with explicit members names, otherwise it can be extremely misleading. 

**Steps to reproduce:**

```
#[cfg(test)]
mod tests {
    struct S {
        a: u64,
        b: u64,
    }

    const X: S = S { b: 31, a: 252, };


    #[test]
    fn test_const() {
        println!("a : {:?}", X.a); // outputs '31'  (expected 252)
        println!("b : {:?}", X.b); // outputs  '252'  (expected 31)
    }
}

```

**Comment by orizi** [comment]
Thanks for the report!
Note this is a bug that only occurs in consts definition - in any case attached fixing PR.
