### ISSUE TITLE
bug: LegacyMap

### ISSUE THREAD

**Issue by gaetbout** [starkware-libs/cairo#6735]
# Bug Report

**Cairo version:** 2.8.2

**Current behavior:** Trying to ignore the warning of a LegacyMap

**Expected behavior:** It should ignore the warning

**Steps to reproduce:**
Have a contract with storage:
```rust
    #[storage]
    struct Storage {
        my_map: LegacyMap<felt252, felt252>,
    }
    ```
When compiling it, it says: 
```
warn: Usage of deprecated feature `"deprecated_legacy_map"` with no `#[feature("deprecated_legacy_map")]` attribute. Note: "Use `starknet::storage::Map` instead."
```
But it doesn't seem to be working (Or I am miss-using it, but couldn't find any example)

**Comment by orizi** [comment]
can you add the actual failing replacement code?

**Comment by gaetbout** [comment]
Not sure I follow? You mean an example repo?

**Comment by orizi** [comment]
"But it doesn't seem to be working (Or I am miss-using it, but couldn't find any example)"

What did you actually do?

**Comment by gaetbout** [comment]
I tried putting 
`#[feature("deprecated_legacy_map")]` a bit everywhere, and some variant of it like `#[deprecated_legacy_map]`. But the warning was always there after running `scarb build`

**Comment by orizi** [comment]
yeah - i see there is some bug with the handling of the attribute - at least in old editions - will take care of it.

in any case - you can just use `starknet::storage::Map` - it is the exactly the same - just no longer considered legacy.

**Comment by gaetbout** [comment]
Will do then thanks!

**Comment by gaetbout** [comment]
That was quick 👍
